function fig = spacePicker()
% modified version of Matt's spaceconsole
% allows picking of space
% must call modified globals_GUI first
% then desired locations are found in GUI.locations1
% Nov 27, 2001

global GUI
global H

% define figure
H.pickerfig = figure('Color',[0.8 0.8 0.8], ...
	'DoubleBuffer','on', ...
   'MenuBar', 'none',...
	'Name','Space Picker', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
   'Position',[800 600 395 300],...					%[5 180 395 300],...
   'Resize', 'off',...
	'ResizeFcn','doresize(gcbf)', ...
	'Tag','SpacePicker', ...
   'ToolBar','none', ...
   'Units', 'pixels', ...
	'DefaultaxesCreateFcn','plotedit(gcbf,''promoteoverlay''); ' ...
    );

% select points box
uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0 0.75 0.99], ...
   'ListboxTop',0, ...
	'Position',[2 163 60 42], ...
	'String','                                 Select Pts.', ...
	'Style','text', ...
	'Tag','StaticText5', ...
    'UserData','[ ]' ...
    );

% +/- pt buttons
H.addpoint = uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0.752 0.752 0.752], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[10 188 15 15], ...
	'String','+', ...
	'Tag','add_point1',...
    'Callback','SetInfo_spacePicker' ...
    );
H.delpoint = uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0.752 0.752 0.752], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[35 188 15 15], ...
	'String','-', ...
	'Tag','delete_point1',...
    'Callback','SetInfo_spacePicker' ...
    );


H.removeEdges = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
	'Units','pixels', ...
	'Position',[1 30 90 15], ...
	'String','remove edges?', ...
	'Callback','SetInfo_spacePicker;' ...
    );

% use last locations pushbutton
H.UseLastLocations = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
	'Units','pixels', ...
	'Position',[1 10 90 15], ...
	'String','use last locs?', ...
	'Callback','SetInfo_spacePicker;' ...
    );

% error message
H.picker_error = uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'FontSize',12, ...
	'BackgroundColor',[.1 0.2 0.8], ...
    'ForegroundColor','yellow', ...
    'FontWeight','bold',...
	'Position',[2 220 100 60], ...
	'String','YOU MUST ENTER LOCATIONS', ...
    'Style','text',...
    'Visible','off' ...
    );

% define axes
axes('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'ButtonDownFcn','spaceaxisX2CB', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'FontSize',8, ...
	'Position',[130 46 230 230], ...
	'Tag','spaceaxes', ...
	'XColor',[0 0 0], ...
	'XGrid','on', ...
	'XLim',[-90 90], ...
	'XLimMode','manual', ...
	'XTick',[-90:30:90], ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YGrid','on', ...
	'YLim',[-90 90], ...
	'YLimMode','manual', ...
	'YTick',[-90:30:90], ...
	'YTickMode','manual', ...
    'ZColor',[0 0 0] ...
    );

% all button
H.allPB = uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[136 252 18 18], ...
	'String','All', ...
	'Tag','Pushbutton4',...
    'Callback','SetInfo_spacePicker' ...
    );

% clear button
H.clearPB = uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[136 52 30 18], ...
	'String','Clear', ...
	'Tag','Pushbutton4',...
    'Callback','SetInfo_spacePicker' ...
    );

% choose resolution of points
H.resolution = uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0.752 0.752 0.7529], ...
	'ListboxTop',0, ...
    'Position',[284 52 70 18], ...
	'String',['Maximum       ';'5 deg.        ';'10 deg. offset';'10 deg.       ';'20 deg. offset';'20 deg.       ';'9 Locations   '], ...
	'Style','popupmenu', ...
	'Tag','SpaceResMenu', ...
    'Value',1,...
    'Callback','SetInfo_spacePicker' ...
    );

uicontrol('Parent',H.pickerfig, ...
	'Units','pixels', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'ListboxTop',0, ...
	'Position',[285 72 65 15], ...
	'String','Resolution:', ...
	'Style','text', ...
    'Tag','StaticText2' ...
    );

SetInfo_spacePicker;
if nargout > 0, fig = H.pickerfig; end