%space: the GUI for space tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;
GUI.locations1 = [];
GUI.locations2 = [];
% to start things off:
XStimParams.itdalone_flag = 0;
XStimParams.ildalone_flag = 0;
XStimParams.ABLalone_flag = 0;
XStimParams.space_flag = 1;

F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.spacefig'))
   temp = get(H.fig,'Position');
   F.space_l = temp(3) - 300; 
   F.space_wd = 400; 
   F.space_ht = 900;
   H.spacefig = figure('Units','pixels',...
      'Position',[F.space_l 100 F.space_wd F.space_ht],...
      'Name','Virtual Auditory  space Measurement',...
      'NumberTitle','off');
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'Stimuli written to disk before playing out.');

%reminder
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'Inv Filters in DSPs: use *.std HRIRs');

%Specify HRTF and Location files
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify Files');

%Fully-cued HRTF file
F.tot_ht = F.tot_ht + F.ind_ht;
H.spacefilepb = uicontrol('Parent',H.spacefig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[2 F.space_ht-F.tot_ht 195 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select Fully-cued Filter File',...
   'Callback','setInfo_space');
uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'Fully-cued Test');
H.spaceflag = uicontrol('Parent',H.spacefig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[315 F.space_ht-F.tot_ht 30 F.ind_ht],...
   'Value',XStimParams.space_flag,...
   'Callback','setInfo_space');
F.tot_ht = F.tot_ht + F.ind_ht;
H.spacefilehdr = uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Position',[0 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'Fully-cued HRTF File:');
H.spacefile = uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Position',[120 F.space_ht-F.tot_ht F.space_wd-120 F.ind_ht],...
   'HorizontalAlignment','left',...
   'ForegroundColor','blue',...
   'String', FN.space_std);
uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'ABL-alone Test');
H.space_ABLaloneflag = uicontrol('Parent',H.spacefig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[315 F.space_ht-F.tot_ht 30 F.ind_ht],...
   'Value',XStimParams.ABLalone_flag,...
   'Callback','setInfo_space');

%ILDAlone filter file
F.tot_ht = F.tot_ht + F.ind_ht;
H.space_ildalonepb = uicontrol('Parent',H.spacefig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[2 F.space_ht-F.tot_ht 195 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select ILD-alone Filter File',...
   'Callback','setinfo_space');
uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'ILD-alone Test');
H.space_ildaloneflag = uicontrol('Parent',H.spacefig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[315 F.space_ht-F.tot_ht 30 F.ind_ht],...
   'Value',XStimParams.ildalone_flag,...
   'Callback','setInfo_space');
F.tot_ht = F.tot_ht + F.ind_ht;
H.space_ildalonefilehdr = uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Position',[0 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'ILD-alone File:');
H.space_ildalonefile = uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Position',[100 F.space_ht-F.tot_ht F.space_wd-100 F.ind_ht],...
   'HorizontalAlignment','left',...
   'ForegroundColor','blue',...
   'String', FN.ildalone_std);

%ITDAlone filter file
F.tot_ht = F.tot_ht + F.ind_ht;
H.space_itdalonepb = uicontrol('Parent',H.spacefig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[2 F.space_ht-F.tot_ht 195 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select ITD-alone Filter File',...
   'Callback','setinfo_space');
uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'ITD-alone Test');
H.space_itdaloneflag = uicontrol('Parent',H.spacefig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[315 F.space_ht-F.tot_ht 30 F.ind_ht],...
   'Value',XStimParams.itdalone_flag,...
   'Callback','setInfo_space');
F.tot_ht = F.tot_ht + F.ind_ht;
H.space_itdalonefilehdr = uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Position',[0 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'ITD-alone File:');
H.space_itdalonefile = uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Position',[100 F.space_ht-F.tot_ht F.space_wd-100 F.ind_ht],...
   'HorizontalAlignment','left',...
   'ForegroundColor','blue',...
   'String', FN.itdalone_std);

F.tot_ht = F.tot_ht + F.ind_ht*2;
%Set Stimulus Parameters
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Stimulus Parameters');
F.tot_ht = F.tot_ht + F.ind_ht;    


uicontrol('Parent',H.spacefig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[2 F.space_ht-F.tot_ht 110 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
   	'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Choose Stim Type');
H.space_stim_type = uicontrol('Parent',H.spacefig,...
   'Style','popup',...
   'Units','pixels',...
   'Position',[112 F.space_ht-F.tot_ht 110 F.ind_ht],...
   'BackgroundColor','white',...
   'String',...
   'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|None',...
   'Value',get(H.stim_type,'Value'),...
   'Callback','setinfo_space');


H.space_stimFNpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[222 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'FN',...
   'Callback','setinfo_space');
H.space_stimFN = uicontrol('Parent',H.spacefig,...
   	'Style','text',...
   	'Units','pixels',...
   	'Position',[242 F.space_ht - F.tot_ht F.space_wd-242 F.ind_ht],...
    'ForegroundColor','blue',...
   	'String', FN.stim);

F.tot_ht = F.tot_ht + F.ind_ht;
H.space_DynamicRangepb = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[222 F.space_ht-F.tot_ht F.space_wd-222 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'push for High Dynamic Range',...
   'Callback','setinfo_space');

F.tot_ht = F.tot_ht + F.ind_ht;
H.space_NBstackpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 150 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','black',...
   'String', 'Bands for NBNoise Stack',...
   'Callback','NBNoiseStackBands');

H.space_DynamicRangeTxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[222 F.space_ht-F.tot_ht F.space_wd-222 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
   'String', 'SPL now 20dB below normal');

F.tot_ht = F.tot_ht + F.ind_ht;
H.space_bandtxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 205 F.ind_ht],...
   'String', 'Bandwidth for BPNoise (octaves)');
H.space_bandwidth = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[205 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandwidth),...
   'Callback','SetBandWidth');

% current freq
H.space_bandtxt(3) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 155 F.ind_ht],...
   'String', 'current frequency:');
H.space_curr_freq = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.curr_freq),...
   'Callback','setinfo_space');


F.tot_ht = F.tot_ht + F.ind_ht;
H.space_bandtxt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 155 F.ind_ht],...
   'String', 'Bandlimits for NBNoise');
H.space_bandlimits1 = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandlimits(1)),...
   'Callback','SetBandLimits');
H.space_bandlimits2 = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[240 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandlimits(2)),...
   'Callback','SetBandLimits');

%ABL (atten)
F.tot_ht = F.tot_ht + 2*F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Atten (dB):');
H.space_ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','SetInfo_space');
% hold ITD?
H.space_ITDtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[165 F.space_ht-F.tot_ht 115 F.ind_ht],...
   'String', 'Hold ITD constant',...
   'BackgroundColor',[.8 .8 .8]);
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[300 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', 'ITD (us):');
H.space_ITD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[360 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.curr_ITD),...
   'Callback','SetInfo_space');

%DUR
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Stim Dur (ms):');
H.space_DUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_stimdur),...
   'Callback','SetInfo_space');

%Hold ILD?
H.space_ILDtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[165 F.space_ht-F.tot_ht 115 F.ind_ht],...
   'String', 'Hold ILD constant',...
   'BackgroundColor',[.8 .8 .8]);
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[300 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'String', 'El');
H.space_el = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[320 F.space_ht-F.tot_ht 30 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.el),...
   'Callback','SetInfo_space');
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[350 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'String', 'Az');
H.space_az = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[370 F.space_ht-F.tot_ht 30 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.az),...
   'Callback','SetInfo_space');

%ISI
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ISI (ms):');
H.space_ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.test_ISI));
%NumReps
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', '# Reps:');
H.space_numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setinfo_space');

   % modulate  sound
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'Sq wave'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'File'
            mod_num = 4;
        case 'None'
            mod_num = 5;
        otherwise
            mod_num = 5;
    end
    uicontrol(        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.space_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   Modulation:');
    H.spacetestmod_type = uicontrol(        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.space_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|Sq wave|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setInfo_space');
    H.spacetestmod_txt = uicontrol(        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', 'Freq:');
    H.spacetestmod_freq = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[220 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setInfo_space');
    
    H.spacetestmod_txtA = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.space_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'depth');
    H.spacetestmod_depth = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setInfo_space');

F.tot_ht = F.tot_ht + F.ind_ht;

    H.spacetestmod_txtB = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.space_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'phase');
    H.spacetestmod_phase = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setInfo_space');
    
    H.spacetestmod_pb = uicontrol(        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.space_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setInfo_space');


% Only build files?? (do not play them out)
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[15 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'ONLY Build Files?');
H.space_buildOnly = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[135 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'Callback','setInfo_space');
    
%%%%%%%%%%%
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

F.tot_ht = F.tot_ht + F.ind_ht;

% increment test number
H.space_inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[250 F.space_ht-F.tot_ht 140 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_space');


%Engage TEST
H.engagespace = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_space');

%Record Data?
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Record Data?');
H.space_recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[185 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'Callback','setInfo_space');
F.tot_ht = F.tot_ht + F.ind_ht;
H.spacedata_FN = uicontrol('Style','text',...
   'Units','pixels',...
   'ForegroundColor','blue',...
   'Position',[85 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', FN.data);

%Reset
F.tot_ht = F.tot_ht + F.ind_ht;
H.resetspace = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback','Reset_space');

%Pause TEST
F.ind_ht = 20; 
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.pausespace = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht*2],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exitspace = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_space');

%Status bar
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.space_status = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Status: setting parameters');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Remaining Reps:');
H.space_remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', get(H.space_numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', 'Trials:');
H.space_remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[206 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', '');

%Plotting
F.ind_ht = 20; 
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.space_plotpsd = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 175 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Plot PSD');

H.space_plotwts = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 175 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Plot weights after ILA');

end %end GUI specification

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
   disp('Cannot initialize a primary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end

SetInfo_space;