% McSpace2: the GUI for Space tests using stimuli simuliar to Dean and McAlpine's
% calc's a new stim on each rep and saves ACpower sequence to DATA file
%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;
GUI.locations1 = [];
GUI.locations2 = [];
% to start things off:
XStimParams.itdalone_flag = 0;
XStimParams.ildalone_flag = 0;
XStimParams.ABLalone_flag = 0;
XStimParams.space_flag = 1;
XStimParams.focalSPL = [0 30];

F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &&...
      ~exist1('H.ablfig') &&...
      ~exist1('H.itdfig') &&...
      ~exist1('H.ildfig') &&...
      ~exist1('H.ildfreqfig') &&...
      ~exist1('H.McSpace2fig'))
   temp = get(H.fig,'Position');
   F.space_l = temp(3) - 300; 
   F.space_wd = 400; 
   F.space_ht = 900;
   H.McSpace2fig = figure('Units','pixels',...
      'Position',[F.space_l 100 F.space_wd F.space_ht],...
      'Name','HRTF-based Space Measurement with McAlpine stimuli',...
      'NumberTitle','off');
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Virtual Auditory Space Measurement');

%reminder
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'Spatial Filters in DSPs: use *.eq HRIRs');

%Specify HRTF and Location files
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify Files');

%Fully-cued HRTF file
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_filepb = uicontrol('Parent',H.McSpace2fig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[2 F.space_ht-F.tot_ht 195 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select Fully-cued Filter File',...
   'Callback','setInfo_McSpace2');
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_filehdr = uicontrol('Parent',H.McSpace2fig,...
   'Style','text',...
   'Position',[0 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'Fully-cued HRTF File:');
H.McSpace2_file = uicontrol('Parent',H.McSpace2fig,...
   'Style','text',...
   'Position',[120 F.space_ht-F.tot_ht F.space_wd-120 F.ind_ht],...
   'HorizontalAlignment','left',...
   'ForegroundColor','blue',...
   'String', FN.space_std);

F.tot_ht = F.tot_ht + F.ind_ht*2;
%Set Stimulus Parameters
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Stimulus Parameters');
F.tot_ht = F.tot_ht + F.ind_ht;    

uicontrol('Parent',H.McSpace2fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[2 F.space_ht-F.tot_ht 110 F.ind_ht],...
   	'BackgroundColor','red',...
   	'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Choose Stim Type');
H.McSpace2_stim_type = uicontrol('Parent',H.McSpace2fig,...
   'Style','popup',...
   'Units','pixels',...
   'Position',[112 F.space_ht-F.tot_ht 110 F.ind_ht],...
   'BackgroundColor','white',...
   'String',...
   'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|BBN - LNN|None',...
   'Value',get(H.stim_type,'Value'),...
   'Callback','setInfo_McSpace2');

H.McSpace2_stimFNpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[222 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'FN',...
   'Callback','setInfo_McSpace2');

H.McSpace2_stimFN = uicontrol('Parent',H.McSpace2fig,...
   	'Style','text',...
   	'Units','pixels',...
   	'Position',[242 F.space_ht - F.tot_ht F.space_wd-215 F.ind_ht],...
    'ForegroundColor','blue',...
   	'String', FN.stim);

F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_repeatmodeTxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[5 F.space_ht-F.tot_ht 100 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
   'String', 'same stim each rep?');
H.McSpace2_repeatmode = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[107 F.space_ht-F.tot_ht 15 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
    'Value', 0, ...
   'Callback','setInfo_McSpace2');

H.McSpace2_DynamicRangepb = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[222 F.space_ht-F.tot_ht F.space_wd-222 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'push for High Dynamic Range',...
   'Callback','setinfo_McSpace2');
F.tot_ht = F.tot_ht + F.ind_ht;

H.McSpace2_DynamicRangeTxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[222 F.space_ht-F.tot_ht F.space_wd-222 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
   'String', 'SPL now 20dB below normal');

% curr_freq
H.McSpace2_freqtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 125 F.ind_ht],...
   'String', 'center frequency (Hz):');
H.McSpace2_freq = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[125 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.curr_freq),...
   'Callback','setInfo_McSpace2');

F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_bwtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 205 F.ind_ht],...
   'String', 'Bandwidth for BPNoise (octaves)');
H.McSpace2_bandwidth = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[205 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandwidth),...
   'Callback','SetBandWidth');
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_bltxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 155 F.ind_ht],...
   'String', 'Bandlimits for NBNoise');
H.McSpace2_bandlimits(1) = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandlimits(1)),...
   'Callback','SetBandLimits');
H.McSpace2_bandlimits(2) = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[240 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandlimits(2)),...
   'Callback','SetBandLimits');

%ABL (atten)
F.tot_ht = F.tot_ht + 2*F.ind_ht;
H.McSpace2_ABLtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Atten (dB):');
H.McSpace2_ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','setInfo_McSpace2');

%DUR
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_DURtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Stim Dur (ms):');
H.McSpace2_DUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_stimdur),...
   'Callback','setInfo_McSpace2');

% ramppts supplementary text
H.McSpace2_rampptstxt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[160 F.space_ht-F.tot_ht 230 40],...
   'BackgroundColor',[.8 .8 .8], ...
   'ForegroundColor',[1 .5 .5], ...
   'FontSize',12,...
   'String', 'suppl text');

%ISI
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_ISItxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ISI (ms):');
H.McSpace2_ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.test_ISI));

% text for choosing McTestType
H.McSpace2_TestTypetxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[145 F.space_ht-F.tot_ht 255 F.ind_ht],...
   'String', 'TstType:  SPL   AMdepth: -lin  -dB   AMperiod: -lin -dB');

%NumReps
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_numrepstxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', '# Reps:');
H.McSpace2_numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setInfo_McSpace2');

H.McSpace2_McTestType(1) = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[195 F.space_ht-F.tot_ht 15 F.ind_ht],...
   'Callback','setInfo_McSpace2');
H.McSpace2_McTestType(2) = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[275 F.space_ht-F.tot_ht 15 F.ind_ht],...
   'Callback','setInfo_McSpace2');
H.McSpace2_McTestType(3) = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[295 F.space_ht-F.tot_ht 15 F.ind_ht],...
   'Callback','setInfo_McSpace2');
H.McSpace2_McTestType(4) = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[365 F.space_ht-F.tot_ht 15 F.ind_ht],...
   'Callback','setInfo_McSpace2');
H.McSpace2_McTestType(5) = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[385 F.space_ht-F.tot_ht 15 F.ind_ht],...
   'Callback','setInfo_McSpace2');

   % modulate  sound
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'Sq wave'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'File'
            mod_num = 4;
        case 'None'
            mod_num = 5;
        otherwise
            mod_num = 5;
    end
    uicontrol(        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.space_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   Modulation:');
    H.McSpace2_mod_type = uicontrol(        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.space_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|Sq wave|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setInfo_McSpace2');
    H.McSpace2_mod_txt(1) = uicontrol(        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', 'Freq:');
    H.McSpace2_mod_freq = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[220 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setInfo_McSpace2');
    
    H.McSpace2_mod_txt(2) = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.space_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'depth');
    H.McSpace2_mod_depth = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setInfo_McSpace2');

    F.tot_ht = F.tot_ht + F.ind_ht;
    H.McSpace2_mod_txt(3) = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[10 F.space_ht-F.tot_ht 200 F.ind_ht],...
        'BackgroundColor',[1 .5 .5], ...
        'ForegroundColor',[.4 .4 1], ...
        'FontSize',12,...
        'Visible','off',...
        'String', 'use BBN - LNN ??');

    H.McSpace2_mod_txt(4) = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.space_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'phase');
    H.McSpace2_mod_phase = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.space_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setInfo_McSpace2');

    H.McSpace2_mod_pb = uicontrol(        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.space_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setInfo_McSpace2');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
  %%%% SETup SPLs for first regime
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLtxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'SetUp SPLs for regime one');
  
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLtxt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 140 F.ind_ht],...
   'FontSize',10,...
   'String', 'focal-range SPL');

H.McSpace2_SPLtxt(3) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[300 F.space_ht-F.tot_ht 90 F.ind_ht],...
   'FontSize',10,...
   'String', 'AM freq');

H.McSpace2_SPLtxt(4) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[150 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'FontSize',10,...
   'String', 'randomize SPLs?');

H.McSpace2_rndSPLs = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[275 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'Value',1,...
   'Callback','setInfo_McSpace2');

%SPL FOCAL-range lower-SPL slider   (slider#1)
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLslider(1) = uicontrol('Style','slider',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd-60 F.ind_ht *.75],...
   'BackgroundColor','blue',...
   'Min',0,'Max',30,...
   'SliderStep',[1/31 5/31],...
   'Value',XStimParams.focalSPL(1),...
   'Callback','setInfo_McSpace2');
H.McSpace2_SPLslider_txt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[F.space_wd-60 F.space_ht-F.tot_ht 60 F.ind_ht*.75],...
   'FontSize',8,...
   'String', [num2str(XStimParams.focalSPL(1)) ' dB']);
%SPL FOCAL-range upper-SPL slider  (slider#2)
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLslider(2) = uicontrol('Style','slider',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd-60 F.ind_ht*.75],...
   'BackgroundColor','red',...
   'Min',0,'Max',30,...
   'SliderStep',[1/31 5/31],...
   'Value',XStimParams.focalSPL(2),...
   'Callback','setInfo_McSpace2');
H.McSpace2_SPLslider_txt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[F.space_wd-60 F.space_ht-F.tot_ht 60 F.ind_ht*.75],...
   'FontSize',8,...
   'String', [num2str(XStimParams.focalSPL(2)) ' dB']);
    
  % FOCAL total probability
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_focalProbtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 150 F.ind_ht],...
   'String', 'FOCAL total probability');
H.McSpace2_focalProb = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', num2str(XStimParams.focalProb),...
   'Callback','setInfo_McSpace2');

  % SPL increment for regime one
H.McSpace2_SPLinc_txt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[240 F.space_ht-F.tot_ht 50 F.ind_ht],...
   'String', 'SPL inc');
H.McSpace2_SPLinc(1) = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[295 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', num2str(XStimParams.SPLinc(1)),...
   'Callback','setInfo_McSpace2');

% epoch duration
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_epoch_durationtxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 150 F.ind_ht],...
   'String', 'epoch duration (msec)');
H.McSpace2_epoch_duration = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', num2str(XStimParams.epoch_duration(1)),...
   'Callback','setInfo_McSpace2');

% ramppts (added Jun 21, 2007)
H.McSpace2_rampptstxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[240 F.space_ht-F.tot_ht 50 F.ind_ht],...
   'String', 'ramppts : ');
H.McSpace2_ramppts = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[295 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', num2str(XStimParams.ramppts),...
   'Callback','setInfo_McSpace2');

% regime duration
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_regime_durationtxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 150 F.ind_ht],...
   'String', 'regime duration (msec)');
H.McSpace2_regime_duration = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', num2str(XStimParams.regime_duration(1)),...
   'Callback','setInfo_McSpace2');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  %%%% SETup SPLs for second regime  
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLtxt2(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'SetUp SPLs for regime two');
  
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLtxt2(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 140 F.ind_ht],...
   'FontSize',10,...
   'String', 'focal-range SPL');


H.McSpace2_SPLtxt2(3) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[300 F.space_ht-F.tot_ht 90 F.ind_ht],...
   'FontSize',10,...
   'String', 'AM freq');

%SPL FOCAL-range lower-SPL slider   (slider#1)
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLslider2(1) = uicontrol('Style','slider',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd-60 F.ind_ht *.75],...
   'BackgroundColor','blue',...
   'Min',0,'Max',30,...
   'SliderStep',[1/31 5/31],...
   'Value',XStimParams.focalSPL2(1),...
   'Callback','setInfo_McSpace2');
H.McSpace2_SPLslider_txt2(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[F.space_wd-60 F.space_ht-F.tot_ht 60 F.ind_ht*.75],...
   'FontSize',8,...
   'String', [num2str(XStimParams.focalSPL2(1)) ' dB']);
%SPL FOCAL-range upper-SPL slider  (slider#2)
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_SPLslider2(2) = uicontrol('Style','slider',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd-60 F.ind_ht*.75],...
   'BackgroundColor','red',...
   'Min',0,'Max',30,...
   'SliderStep',[1/31 5/31],...
   'Value',XStimParams.focalSPL2(2),...
   'Callback','setInfo_McSpace2');
H.McSpace2_SPLslider_txt2(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[F.space_wd-60 F.space_ht-F.tot_ht 60 F.ind_ht*.75],...
   'FontSize',8,...
   'String', [num2str(XStimParams.focalSPL2(2)) ' dB']);
    
  % FOCAL total probability
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_focalProbtxt2 = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 150 F.ind_ht],...
   'String', 'FOCAL total probability');
H.McSpace2_focalProb2 = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', num2str(XStimParams.focalProb2),...
   'Callback','setInfo_McSpace2');

  % SPL increment for regime two
H.McSpace2_SPLinc_txt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[240 F.space_ht-F.tot_ht 50 F.ind_ht],...
   'String', 'SPL inc');
H.McSpace2_SPLinc(2) = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[295 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', num2str(XStimParams.SPLinc(2)),...
   'Callback','setInfo_McSpace2');


% regime duration
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_regime_durationtxt2(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 150 F.ind_ht],...
   'String', 'regime duration (msec)');
H.McSpace2_regime_duration2 = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', num2str(XStimParams.regime_duration(2)),...
   'Callback','setInfo_McSpace2');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%% RUN Test    
F.tot_ht = F.tot_ht + F.ind_ht*1.5;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

F.tot_ht = F.tot_ht + F.ind_ht;
% increment test number
H.McSpace2_inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[250 F.space_ht-F.tot_ht 140 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_McSpace2');

%Engage TEST
H.engage_McSpace2 = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_McSpace2');

%Record Data?
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Record Data?');
H.McSpace2_recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[185 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'Callback','setInfo_McSpace2');
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_data_FN = uicontrol('Style','text',...
   'Units','pixels',...
   'ForegroundColor','blue',...
   'Position',[85 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', FN.data);

%Reset
F.tot_ht = F.tot_ht + F.ind_ht;
H.resetMcSpace2 = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback','Reset_McSpace2');

%Pause TEST
F.ind_ht = 20; 
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.pauseMcSpace2 = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht*2],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exitMcSpace2 = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_McSpace2');

%Status bar
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.McSpace2_status = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Status: setting parameters');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Remaining Reps:');
H.McSpace2_remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', get(H.McSpace2_numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', 'Trials:');
H.McSpace2_remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[206 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', '');

% analyse cycle-by-cycle Vstrength
F.tot_ht = F.tot_ht + F.ind_ht;
H.McSpace2_analVstr = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'Analyse Vstr',...
   'Callback','anal_cycleVstr');

end %end GUI specification

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end

setInfo_McSpace2;