%ILDFreq: the GUI for ILD-frequency tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

pos_incr = 20;
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.spacefig') &...
      ~exist1('H.ildalonefig'))
   Xstim_control_pos = get(H.fig,'Position');
   ildfreqfig_l = Xstim_control_pos(3) - 300; ildfreqfig_wd = 350; ildfreqfig_ht = 950;
   H.ildfreqfig = figure('Units','pixels',...
      'Position',[ildfreqfig_l 0 ildfreqfig_wd ildfreqfig_ht],...
      'Name','ILD-Frequency Measurement',...
      'NumberTitle','off');
tot_ht = 0;
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht ildfreqfig_wd ind_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'ILD-Frequency Measurement');

%Frequency Information
ind_ht = 20; tot_ht = tot_ht + ind_ht + 20;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht ildfreqfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify Frequency Parameters');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'Low Freq:');
ind_ht = 20;
H.lowfreq = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.lofreq),...
   'Callback','SetFreqStep');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'High Freq:');
ind_ht = 20;
H.highfreq = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.hifreq),...
   'Callback','SetFreqStep');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'Num Freqs:');
ind_ht = 20;
H.numfreqs = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.numfreqs),...
   'Callback','SetFreqStep');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'Freq Step:');
ind_ht = 20;
low_freq  = str2num(get(H.lowfreq,'String'));
high_freq = str2num(get(H.highfreq,'String'));
numfreqs = str2num(get(H.numfreqs,'String'));
H.stepfreq = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(round((high_freq-low_freq)/(numfreqs-1))));


%ILD Information
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht ildfreqfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify ILD Parameters');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'Low ILD:');
ind_ht = 20;
H.lowild = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.loild),...
   'Callback','SetILDStep');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'High ILD:');
ind_ht = 20;
H.highild = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.hiild),...
   'Callback','SetILDStep');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'Num ILDs:');
ind_ht = 20;
H.numilds = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.numilds),...
   'Callback','SetILDStep');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', 'ILD Step:');
ind_ht = 20;
low_ild  = str2num(get(H.lowild,'String'));
high_ild = str2num(get(H.highild,'String'));
numilds = str2num(get(H.numilds,'String'));
H.stepild = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[82 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str((high_ild-low_ild)/(numilds-1)));

%Other Stimulus Parameters
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht ildfreqfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Remaining Parameters');
%ITD
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 110 ind_ht],...
   'String', 'ITD (us):');
ind_ht = 20;
H.ITD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_ITD));
%ABL
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 110 ind_ht],...
   'String', 'ABL (dB):');
ind_ht = 20;
H.ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_ABL));
%DUR
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 110 ind_ht],...
   'String', 'Stim Dur (ms):');
ind_ht = 20;
H.DUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_stimdur));
%ISI
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 110 ind_ht],...
   'String', 'ISI (ms):');
ind_ht = 20;
H.ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.test_ISI));
%NumReps
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 110 ind_ht],...
   'String', '# Reps:');
ind_ht = 20;
H.numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 ildfreqfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','SetRepText');

%Engage TEST
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.engageildfreq = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_ILDFreq');

%Record Data?
ind_ht = 20;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 ildfreqfig_ht-tot_ht 100 ind_ht],...
   'String', 'Record Data?');
H.recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[190 ildfreqfig_ht-tot_ht 30 ind_ht]);

%Reset
ind_ht = 20;
H.resetildfreq = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[ildfreqfig_wd-100 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset');

%Pause TEST
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.pauseildfreq = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
ind_ht = 20;
H.exitildfreq = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[ildfreqfig_wd-100 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_ILDFreq');

%Build/Play Trials
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.buildplay = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 175 ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'Build/Play Status');

%Remaining Reps and Trials
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 175 ind_ht],...
   'String', 'Reps Remaining:');
H.remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[177 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', get(H.numreps,'String'));
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 175 ind_ht],...
   'String', 'Trials Remaining:');
H.remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[177 ildfreqfig_ht-tot_ht 80 ind_ht],...
   'String', '');

%Plotting
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.plotpsd = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 ildfreqfig_ht-tot_ht 175 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Plot PSD');

end %end GUI specification

stimuli_dir = FN.temp_stim_path;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 10000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end
