%InitSession: Callback for pushbutton InitSess

F.InitSess_fig_ht = 200;
F.InitSess_fig_wd = 300;
F.tot_ht = 10;
F.pos_incr = 20;
F.ind_ht = 20; F.tot_ht = F.tot_ht + F.ind_ht;
H.initsessfig = figure('Position',[300 300 F.InitSess_fig_wd F.InitSess_fig_ht],...
   'Name','Initialize Session',...
   'NumberTitle','off');

%Bird Number
uicontrol('Parent',H.initsessfig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[0 F.InitSess_fig_ht-F.tot_ht 200 F.ind_ht],...
   'FontSize',6,...
   'String','Bird Number');
H.birdnuminit = uicontrol('Parent',H.initsessfig,...
   'Style','edit',...
   'Units','pixels',...
   'Position',[205 F.InitSess_fig_ht-F.tot_ht 75 F.ind_ht],...
   'FontSize',8,...
   'String',num2str(XStimParams.bird_number));

%Side of Brain

%Session Number

%Recording Site
ind_ht = 20; F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Parent',H.initsessfig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[0 F.InitSess_fig_ht-F.tot_ht 200 F.ind_ht],...
   'FontSize',6,...
   'String','Recording_Site');
H.recording_site_init = uicontrol('Parent',H.initsessfig,...
   'Style','edit',...
   'Units','pixels',...
   'Position',[205 F.InitSess_fig_ht-F.tot_ht 75 F.ind_ht],...
   'FontSize',8,...
   'String',XStimParams.recording_site);

%Test Number
F.ind_ht = 20; F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Parent',H.initsessfig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[0 F.InitSess_fig_ht-F.tot_ht 200 F.ind_ht],...
   'FontSize',6,...
   'String','Test Number');
H.testnum_init = uicontrol('Parent',H.initsessfig,...
   'Style', 'edit',...
   'Units', 'pixels',...
   'Position', [205 F.InitSess_fig_ht-F.tot_ht 75 F.ind_ht],...
   'FontSize', 8,...
   'String', num2str(XStimParams.testnum));

%Set params to Defaults
F.ind_ht = 20; F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Parent',H.initsessfig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[0 F.InitSess_fig_ht-F.tot_ht 200 F.ind_ht],...
   'FontSize',6,...
   'String','Reset to Default Params');
H.paramdefaults = uicontrol('Parent',H.initsessfig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[205 F.InitSess_fig_ht-F.tot_ht 75 F.ind_ht],...
   'FontSize',8,...
   'Value',0);

%Initialize GO
F.ind_ht = 20;F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
H.initsessgo = uicontrol('Parent',H.initsessfig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.InitSess_fig_ht-F.tot_ht 125 F.ind_ht],...
   'FontSize',8,...
   'Value',0,...
   'String','Initialize settings',...
   'Callback','InitXStimParams');

%Initialize Cancel
F.ind_ht = 20;
H.initsesscancel = uicontrol('Parent',H.initsessfig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[F.InitSess_fig_wd-80 F.InitSess_fig_ht-F.tot_ht 75 F.ind_ht],...
   'FontSize',8,...
   'Value',0,...
   'String','Cancel!',...
   'Callback','close(H.initsessfig)');