%RSSTest: the GUI for RSS tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

pos_incr = 20;
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.spacefig') &...
      ~exist1('H.ildalonefig') &...
      ~exist1('H.rssfig'))
   Xstim_control_pos = get(H.fig,'Position');
   rsstestfig_l = Xstim_control_pos(3) - 300; rsstestfig_wd = 350; rsstestfig_ht = 950;
   H.rssfig = figure('Units','pixels',...
      'Position',[rsstestfig_l 0 rsstestfig_wd rsstestfig_ht],...
      'Name','RSS Test',...
      'NumberTitle','off');
tot_ht = 0;
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht rsstestfig_wd ind_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'RSS Measurement');

%RSS Information
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht rsstestfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify RSS Parameters');

%RSS file
ind_ht = 20; tot_ht = tot_ht + ind_ht + 10;
H.rssfilehdr = uicontrol('Parent',H.rssfig,...
   'Style','text',...
   'Position',[0 fig_ht-tot_ht fig_wd ind_ht],...
   'String', 'RSS File:');
ind_ht = 20; tot_ht = tot_ht + ind_ht;
H.rssfile = uicontrol('Parent',H.rssfig,...
   'Style','text',...
   'Position',[0 fig_ht-tot_ht fig_wd ind_ht],...
   'String', FN.rss);
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Parent',H.rssfig,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[2 fig_ht-tot_ht 195 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select Earphone Filter File',...
   'Callback','rssfilediagbox');


%Other Stimulus Parameters
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht rsstestfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Remaining Parameters');
%ITD
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 110 ind_ht],...
   'String', 'ITD (us):');
ind_ht = 20;
H.ITD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 rsstestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_ITD));
%ABL
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 110 ind_ht],...
   'String', 'ABL (dB):');
ind_ht = 20;
H.ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 rsstestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_ABL));
%ISI
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 110 ind_ht],...
   'String', 'ISI (ms):');
ind_ht = 20;
H.ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 rsstestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.test_ISI));
%NumReps
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 110 ind_ht],...
   'String', '# Reps:');
ind_ht = 20;
H.numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 rsstestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','SetRepText');

%Engage TEST
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.engagersstest = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_rsstest');

%Record Data?
ind_ht = 20;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 rsstestfig_ht-tot_ht 100 ind_ht],...
   'String', 'Record Data?');
H.recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[190 rsstestfig_ht-tot_ht 30 ind_ht]);

%Reset
ind_ht = 20;
H.resetrsstest = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[rsstestfig_wd-100 rsstestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset');

%Pause TEST
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.pausersstest = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
ind_ht = 20;
H.exitrsstest = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[rsstestfig_wd-100 rsstestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_rsstest');

%Build/Play Trials
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.buildplay = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 175 ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'Build/Play Status');

%Remaining Reps and Trials
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 175 ind_ht],...
   'String', 'Reps Remaining:');
H.remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[177 rsstestfig_ht-tot_ht 80 ind_ht],...
   'String', get(hnumreps,'String'));
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 175 ind_ht],...
   'String', 'Trials Remaining:');
H.remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[177 rsstestfig_ht-tot_ht 80 ind_ht],...
   'String', '');

%Plotting
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
H.plotpsd = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 rsstestfig_ht-tot_ht 175 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Plot PSD');

end %end GUI specification

eval(['stimuli_dir = ' FN.home 'RSS-Test\Stimuli\;' ]);

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 10000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end
