%BMLD.m
%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

if isempty(XStimParams.locations)
    XStimParams.locations = [0 0];
end
if isempty(XStimParams.locations1)
    XStimParams.locations1 = [0 -40];
end

XStimParams.reset_flag = 0;

F.pos_incr = 20;
F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.BMLDfig'))
    temp = get(H.fig,'Position');
    F.BMLD_l = temp(3) - 300; 
    F.BMLD_wd = 400; 
    F.BMLD_ht = 900;
    H.BMLDfig = figure('Units','pixels',...
        'Position',[F.BMLD_l 100 F.BMLD_wd F.BMLD_ht],...
        'Name','BMLD Measurement (virtual or ITD)',...
        'NumberTitle','off');
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', 'BMLD virtual or ITD');
    %reminder
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'String', 'Earphone Inverse Filters loaded separately to DSPs');
    %more info
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'String', 'Source#1 constant (usu. masker)    Source#2 variable SPL (usu. signal)');
    
    %Specify HRTF and Location files
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Specify Files');
    
    %Fully-cued HRTF file
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.spacefilepb = uicontrol('Parent',H.BMLDfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.BMLD_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Select Fully-cued Filter File',...
        'Callback','setInfo_BMLD');
    
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.BMLD_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Fully-cued Test');
    H.spaceflag = uicontrol('Parent',H.BMLDfig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'Value',(XStimParams.space_flag),...
        'Callback','setInfo_BMLD');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.spacefilehdr = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Position',[0 F.BMLD_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Fully-cued HRTF File:');
    H.spacefile = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Position',[120 F.BMLD_ht-F.tot_ht F.BMLD_wd-120 F.ind_ht],...
        'HorizontalAlignment','left',...
        'ForegroundColor','blue',...
        'String', FN.space_std);
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Position',[250 F.BMLD_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'uses ITD if un-checked');
    
    
    F.tot_ht = F.tot_ht + F.ind_ht + F.ind_ht;
    %Other Stimulus Parameters
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Parameters for Source #1 (constant ABL)');
    F.tot_ht = F.tot_ht + F.ind_ht;
    
 %%%% STIMULUS #1
 % Stimulus1 types: popupmenu
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht - F.tot_ht 60 F.ind_ht],...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', '1st Stim:');
    H.BMLD_stim_type = uicontrol('Parent',H.BMLDfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[60 F.BMLD_ht-F.tot_ht 120 F.ind_ht],...
        'BackgroundColor','white',...
        'String',...
        'Tone|Gammatone|...|...|BandPassed Noise|NarrowBand Noise|...|BroadBand Noise|File|None',...
        'Value',get(H.stim_type,'Value'),...
        'Callback','setinfo_BMLD');
    
    % only one will be displayed, either
    H.BMLD_stim_filenamepb = uicontrol('Parent',H.BMLDfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[180 F.BMLD_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Callback','setinfo_BMLD');
    H.BMLD_stim_filename = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[205 F.BMLD_ht-F.tot_ht 105 F.ind_ht],...
        'ForegroundColor','blue',...
        'String', FN.stim);
    % or
    H.BMLD_freq_txt = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[180 F.BMLD_ht-F.tot_ht 90 F.ind_ht],...
        'Visible','off',...
        'String', 'Frequency');
    H.BMLD_freq = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Visible','off',...
        'Position',[270 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.freq(1)),...
        'Callback','setinfo_BMLD');
        
    % modulate 1st sound
    F.tot_ht = F.tot_ht + F.ind_ht;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'File'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'None'
            mod_num = 4;
        otherwise
            mod_num = 1;
    end
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.BMLD_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   Modulation:');
    H.BMLD_mod_type = uicontrol('Parent',H.BMLDfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.BMLD_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setinfo_BMLD');
    H.BMLD_mod_txt = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.BMLD_ht-F.tot_ht 50 F.ind_ht],...
        'String', 'Mod Freq: ');
    H.BMLD_mod_freq = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[230 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setinfo_BMLD');
    
    H.BMLD_mod_txtA = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[270 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'depth');
    H.BMLD_mod_depth = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[300 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setinfo_BMLD');
    H.BMLD_mod_txtB = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[340 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'phase');
    H.BMLD_mod_phase = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[370 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setinfo_BMLD');
    
    H.BMLD_mod_pb = uicontrol('Parent',H.BMLDfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.BMLD_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setinfo_BMLD');
    
     
    % bandwidths
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 110 F.ind_ht],...
        'String', 'Bandwidth(oct):');
    H.bandwidth1 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[112 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.bandwidth(1)),...
        'Callback','setinfo_BMLD');
        
    % bandlimits
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[160 F.BMLD_ht-F.tot_ht 50 F.ind_ht],...
        'String', 'bandlimits:');
    H.bandlimits1 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[212 F.BMLD_ht-F.tot_ht 50 F.ind_ht],...
        'String', num2str(XStimParams.bandlimits(1)),...
        'Callback','setinfo_BMLD');
    H.bandlimits2 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[262 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.bandlimits(2)),...
        'Callback','setinfo_BMLD');
       
    %ABL
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Fixed Atten');
    H.ABL = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.curr_ABL),...
        'Callback', 'setinfo_BMLD');
    
    %%%%%%% STIMULUS #2
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Parameters for source #2 (variable ABL)');
    
    % Stimulus2 types: popupmenu
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht - F.tot_ht 60 F.ind_ht],...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', '2nd Stim:');
    H.BMLD_stim_type2 = uicontrol('Parent',H.BMLDfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[60 F.BMLD_ht-F.tot_ht 120 F.ind_ht],...
        'BackgroundColor','white',...
        'String',...
        'Tone|Gammatone|...|...|BandPassed Noise|NarrowBand Noise|...|BroadBand Noise|File|None',...
        'Value',get(H.stim_type2,'Value'),...
        'Callback','setinfo_BMLD');
    
    % only one will be visible, either:
    H.BMLD_stim_filename2pb = uicontrol('Parent',H.BMLDfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[180 F.BMLD_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Callback','setinfo_BMLD');
    H.BMLD_stim_filename2 = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[205 F.BMLD_ht-F.tot_ht 105 F.ind_ht],...
        'ForegroundColor','blue',...
        'String', FN.stim2);
    % or
    H.BMLD_freq2_txt = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[180 F.BMLD_ht-F.tot_ht 90 F.ind_ht],...
        'Visible','off',...
        'String', 'Frequency');
    H.BMLD_freq2 = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Visible','off',...
        'Position',[270 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.freq(2)),...
        'Callback','setinfo_BMLD');
        
    % modulate 2nd sound
    F.tot_ht = F.tot_ht + F.ind_ht;
    switch XStimParams.mod_type2
        case 'Tone'
            mod_num = 1;
        case 'File'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'None'
            mod_num = 4;
        otherwise
            mod_num = 1;
    end
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.BMLD_ht - F.tot_ht 80 F.ind_ht],...
        'String', '  Modulation:');
    H.BMLD_mod_type2 = uicontrol('Parent',H.BMLDfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.BMLD_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setinfo_BMLD');
    H.BMLD_mod_txt2 = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.BMLD_ht-F.tot_ht 50 F.ind_ht],...
        'String', 'Mod Freq:');
    H.BMLD_mod_freq2 = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[230 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(2)),...
        'Callback','setinfo_BMLD');
    H.BMLD_mod_txtA2 = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[270 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'depth');
    H.BMLD_mod_depth2 = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[300 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(2)),...
        'Callback','setinfo_BMLD');
    H.BMLD_mod_txtB2 = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[340 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'phase');
    H.BMLD_mod_phase2 = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[370 F.BMLD_ht-F.tot_ht 30 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(2)),...
        'Callback','setinfo_BMLD');
    
    H.BMLD_mod_pb2 = uicontrol('Parent',H.BMLDfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.BMLD_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setinfo_BMLD');

       F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 110 F.ind_ht],...
        'String', 'Bandwidth(oct):');
    H.bandwidth2 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[112 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.bandwidth(2)),...
        'Callback','setinfo_BMLD');
     
       % bandlimits
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[160 F.BMLD_ht-F.tot_ht 50 F.ind_ht],...
        'String', 'bandlimits:');
    H.bandlimits3 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[212 F.BMLD_ht-F.tot_ht 50 F.ind_ht],...
        'String', num2str(XStimParams.bandlimits(3)),...
        'Callback','setinfo_BMLD');
    H.bandlimits4 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[262 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.bandlimits(4)),...
        'Callback','setinfo_BMLD');
         
    
    % RELATIVE ABLs for source#2 (variable)
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Low ABL (<=0):');
    H.lowabl = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.loabl),...
        'Callback','setinfo_BMLD');
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'High ABL (>=0):');
    H.highabl = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.hiabl),...
        'Callback','setinfo_BMLD');
    
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[150 F.BMLD_ht-F.tot_ht 100 F.ind_ht],...
        'String', 'Arbitrary ABLs (+/-):');
    H.aritrary_abls = uicontrol('Parent',H.BMLDfig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[250 F.BMLD_ht-F.tot_ht 20 F.ind_ht],...
        'Callback','setinfo_BMLD');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.ablvector_txt = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[150 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'ABL vector:');
    H.ablvector = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[210 F.BMLD_ht-F.tot_ht 135 F.ind_ht],...
        'String', num2str(XStimParams.abls),...
        'Callback','setinfo_BMLD');

    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Num ABLs:');
    H.numabls = uicontrol('Parent',H.BMLDfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.numabls),...
        'Callback','setinfo_BMLD');

    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'ABL Step:');
    H.stepabl = uicontrol('Parent',H.BMLDfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 60 F.ind_ht]);
    
   
    
  %%%% locations for each source  
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Locations for each source');
    
        
    F.tot_ht = F.tot_ht + F.ind_ht;
    % loc1
    H.loc1_txt(1) = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Source 1: Elev');
    H.loc1(1) = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[80 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.locations(1,1)),...
        'Callback','setinfo_BMLD');
    H.loc1_txt(2) = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[125 F.BMLD_ht-F.tot_ht 75 F.ind_ht],...
        'String', ' Azim');
    H.loc1(2) = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[200 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.locations(1,2)),...
        'Callback','setinfo_BMLD');
    
    % loc2
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.loc2_txt(1) = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Source 2: Elev');
    H.loc2(1) = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[80 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.locations1(1,1)),...
        'Callback','setinfo_BMLD');
    H.loc2_txt(2) = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[125 F.BMLD_ht-F.tot_ht 75 F.ind_ht],...
        'String', ' Azim');
    H.loc2(2) = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[200 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.locations1(1,2)),...
        'Callback','setinfo_BMLD');
    
    
     uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[260 F.BMLD_ht-F.tot_ht-F.ind_ht*.5 100 F.ind_ht*1.5],...
        'String', 'play src#2 at each loc?');
      H.each_loc = uicontrol('Parent',H.BMLDfig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[365 F.BMLD_ht-F.tot_ht 15 F.ind_ht],...
        'Value',(XStimParams.each_loc),...
        'Callback','setInfo_BMLD');

    
    % ITD for source1
     F.tot_ht = F.tot_ht + F.ind_ht;
   H.ITD_txt(1) = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'ITD1(us):');
    H.ITD(1) = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.curr_ITD),...
        'Callback', 'setinfo_BMLD');
    % ITD for source2
    H.ITD_txt(2) = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[140 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'ITD2(us):');
    H.ITD(2) = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[202 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ITD2),...
        'Callback', 'setinfo_BMLD');
    F.tot_ht = F.tot_ht + F.ind_ht;
    

    
    
     % run control
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'General Parameters');
    
    %DUR
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Stim Dur (ms):');
    H.DUR = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.curr_stimdur),...
        'Callback','setinfo_BMLD');
    
       %ISI
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[140 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'ISI (ms):');
    H.ISI = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[202 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.test_ISI),...
        'Callback', 'setinfo_BMLD');

    %NumReps
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[250 F.BMLD_ht-F.tot_ht 60 F.ind_ht],...
        'String', '# Reps:');
    H.numreps = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[312 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.numreps),...
        'Callback','setinfo_BMLD');
 
        
    % run control
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Run Control');
    
    %Engage TEST
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.engageBMLD = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','green',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'ENGAGE',...
        'Callback','Engage_BMLD');
    
    %Record Data?
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.BMLD_ht-F.tot_ht 100 F.ind_ht],...
        'String', 'Record Data?');
    H.recorddata = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[185 F.BMLD_ht-F.tot_ht 20 F.ind_ht],...
        'Callback', 'setinfo_BMLD');
    % increment test number
    H.inc_testnum = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[250 F.BMLD_ht-F.tot_ht 140 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', 'INCREMENT testnum',...
        'Callback','setInfo_BMLD');

    F.tot_ht = F.tot_ht + F.ind_ht;
    H.recorddata_FN = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.BMLD_ht-F.tot_ht 100 F.ind_ht],...
        'String', FN.data);
    
    
    %Pause TEST
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.pauseBMLD = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[10 F.BMLD_ht-F.tot_ht-F.ind_ht 100 2*F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontSize',18,...
        'FontWeight','bold',...
        'String', 'Pause');
    
    %Reset
    H.resetBMLD = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[200 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','cyan',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Reset',...
        'Callback','Reset_BMLD');
    
    %Exit
    H.exitBMLD = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[F.BMLD_wd-100 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','yellow',...
        'FontWeight','bold',...
        'String', 'EXIT',...
        'Callback','Exit_BMLD');
    
    %Build/Play Trials
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    H.status = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht F.BMLD_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Status: setting parameters');
    
    %Remaining Reps and Trials
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.BMLD_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Remaining reps:');
    H.remreps = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[122 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', get(H.numreps,'String'));
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[164 F.BMLD_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Trials:');
    H.remtrials = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[246 F.BMLD_ht-F.tot_ht 40 F.ind_ht],...
        'String', '');
    
end %end GUI specification

stimuli_dir = FN.temp_stim_path;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
    disp('Cannot initialize a secondary process')
    return;
end

if(S232('APlock', 100, 0) == 0)
    disp('Cannot acquire lock on AP2 Card')
    s232('S2close');
    return;
end

if(S232('XBlock', 100, 0) == 0)
    disp('Cannot acquire lock on X Bus')
    s232('APunlock', 0);
    s232('S2close');
    return;
end

SetInfo_BMLD;