%ITDTest2: the GUI for ITD tests

%*******************************************************************************
%	The Graphical User Interface
% this version allows differing filenames for each ear
%*******************************************************************************

XStimParams.reset_flag = 0;

pos_incr = 20;
%Figure window
if(~exist1('H..searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.spacefig') &...
      ~exist1('H.ildalonefig'))
   Xstim_control_pos = get(H.fig,'Position');
   itdtestfig_l = Xstim_control_pos(3) - 300; itdtestfig_wd = 350; itdtestfig_ht = 850;
   H.itdfig = figure('Units','pixels',...
      'Position',[itdtestfig_l 0 itdtestfig_wd itdtestfig_ht],...
      'Name','ITD Test',...
      'NumberTitle','off');
tot_ht = 0;
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht itdtestfig_wd ind_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'ITD2 Measurement - allows 2 FNames');

%ITD Information
tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht itdtestfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify ITD Parameters');
tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 80 ind_ht],...
   'String', 'Low ITD:');
H.lowitd = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.loitd),...
   'Callback','setinfo_itd2');
tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 80 ind_ht],...
   'String', 'High ITD:');
H.highitd = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.hiitd),...
   'Callback','setinfo_itd2');
tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 80 ind_ht],...
   'String', 'Num ITDs:');
H.numitds = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.numitds),...
   'Callback','setinfo_itd2');
tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 80 ind_ht],...
   'String', 'ITD Step:');

H.stepitd = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-tot_ht 60 ind_ht]);


% change filenames
tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht itdtestfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Filenames');

tot_ht = tot_ht + ind_ht;
H.itd_FNpb(1) = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[10 itdtestfig_ht-tot_ht 100 ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'pick FN.stim1',...
   'Callback','setinfo_itd2');
H.itd_FNpb(2) = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[120 itdtestfig_ht-tot_ht 100 ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'pick FN.stim2',...
   'Callback','setinfo_itd2');

tot_ht = tot_ht + ind_ht;
H.itd_FNtxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[10 itdtestfig_ht-tot_ht 100 ind_ht],...
   'BackgroundColor',[.8 .8 .8],...
   'ForegroundColor','blue',...
   'String', FN.stim);
H.itd_FNtxt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[120 itdtestfig_ht-tot_ht 100 ind_ht],...
   'BackgroundColor',[.8 .8 .8],...
   'ForegroundColor','blue',...
   'String', FN.stim2);



%Other Stimulus Parameters
ind_ht = 20; tot_ht = tot_ht + ind_ht + pos_incr;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht itdtestfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Remaining Parameters');
%Freq
if 0
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 110 ind_ht],...
   'String', 'Frequency (Hz):');
ind_ht = 20;
H.freq = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_freq),...
   'Callback','setinfo_itd2');
end

%ILD
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 110 ind_ht],...
   'String', 'ILD (dB):');
ind_ht = 20;
H.ILD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_ILD),...
   'Callback','setinfo_itd2');
%ABL
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 110 ind_ht],...
   'String', 'ABL (dB):');
ind_ht = 20;
H.ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','setinfo_itd2');
%DUR
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 110 ind_ht],...
   'String', 'Stim Dur (ms):');
ind_ht = 20;
H.DUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.curr_stimdur),...
   'Callback','setinfo_itd2');
%ISI
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 110 ind_ht],...
   'String', 'ISI (ms):');
ind_ht = 20;
H.ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.test_ISI),...
   'Callback','setinfo_itd2');
%NumReps
ind_ht = 20; tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 110 ind_ht],...
   'String', '# Reps:');
ind_ht = 20;
H.numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-tot_ht 60 ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setinfo_itd2');

% increment test number
H.inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[200 itdtestfig_ht-tot_ht 140 ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setinfo_itd2');

   % modulate  sound
    tot_ht = tot_ht + ind_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'File'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'None'
            mod_num = 4;
        otherwise
            mod_num = 1;
    end
    uicontrol(        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 itdtestfig_ht - tot_ht 80 ind_ht],...
        'String', '   Modulation:');
    H.ITDtest2mod_type = uicontrol(        'Style','popup',...
        'Units','pixels',...
        'Position',[80 itdtestfig_ht-tot_ht 100 ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setinfo_itd2');
    H.ITDtest2mod_txt = uicontrol(        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 itdtestfig_ht-tot_ht 40 ind_ht],...
        'String', 'Freq:');
    H.ITDtest2mod_freq = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[220 itdtestfig_ht-tot_ht 40 ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setinfo_itd2');
    
    H.ITDtest2mod_txtA = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 itdtestfig_ht-tot_ht 30 ind_ht],...
        'String', 'depth');
    H.ITDtest2mod_depth = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 itdtestfig_ht-tot_ht 40 ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setinfo_itd2');

    tot_ht = tot_ht + ind_ht;

    H.ITDtest2mod_txtB = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 itdtestfig_ht-tot_ht 30 ind_ht],...
        'String', 'phase');
    H.ITDtest2mod_phase = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 itdtestfig_ht-tot_ht 40 ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setinfo_itd2');
    
    H.ITDtest2mod_pb = uicontrol(        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 itdtestfig_ht-tot_ht 25 ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setinfo_itd2');

%
tot_ht = tot_ht + ind_ht*2;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht itdtestfig_wd ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

%Engage TEST
tot_ht = tot_ht + ind_ht;
H.engageITDtest2 = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_ITDtest2');

%Record Data?
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 itdtestfig_ht-tot_ht 100 ind_ht],...
   'String', 'Record Data?');
H.recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[190 itdtestfig_ht-tot_ht 30 ind_ht]);
H.recorddata_FN = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 itdtestfig_ht-(tot_ht+ind_ht) 100 ind_ht],...
   'String', FN.data);

%Reset
H.resetITDtest2 = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[itdtestfig_wd-100 itdtestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback', 'reset_ITDtest2');

%Pause TEST
tot_ht = tot_ht + ind_ht*2;
H.pauseITDtest2 = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exitITDtest2 = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[itdtestfig_wd-100 itdtestfig_ht-tot_ht 80 ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_ITDtest2');

%Build/Play Trials
tot_ht = tot_ht + ind_ht + pos_incr;
H.buildplay = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 175 ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'Build/Play Status');

%Remaining Reps and Trials
tot_ht = tot_ht + ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 100 ind_ht],...
   'String', 'Remaining reps:');
H.remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 itdtestfig_ht-tot_ht 40 ind_ht],...
   'String', get(H.numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 itdtestfig_ht-tot_ht 80 ind_ht],...
   'String', 'Trials:');
H.remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[226 itdtestfig_ht-tot_ht 40 ind_ht],...
   'String', '');

%Plotting
tot_ht = tot_ht + ind_ht + pos_incr;
H.plotpsd = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-tot_ht 175 ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Plot PSD');

end %end GUI specification

stimuli_dir = FN.temp_stim_path;
setinfo_itd2;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 10000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end
