%ITDTest: the GUI for ITD tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;

F.pos_incr = 20;
%Figure window
if(~exist1('H..searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.spacefig') &...
      ~exist1('H.ildalonefig'))
   Xstim_control_pos = get(H.fig,'Position');
   itdtestfig_l = Xstim_control_pos(3) - 300; itdtestfig_wd = 350; itdtestfig_ht = 950;
   H.itdfig = figure('Units','pixels',...
      'Position',[itdtestfig_l 0 itdtestfig_wd itdtestfig_ht],...
      'Name','ITD Test',...
      'NumberTitle','off');
F.tot_ht = 0;
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...'Parent',H.fig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht itdtestfig_wd F.int_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'ITD Measurement');

%ITD Information
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht itdtestfig_wd F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify ITD Parameters');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'Low ITD:');
H.lowitd = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.loitd),...
   'Callback','setInfo_ITD');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'High ITD:');
H.highitd = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.hiitd),...
   'Callback','setInfo_ITD');

uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[150 itdtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Arbitrary ITDs:');
H.aritrary_itds = uicontrol('Parent',H.itdfig,...
'Style','checkbox',...
   'Units','pixels',...
   'Position',[250 itdtestfig_ht-F.tot_ht 20 F.int_ht],...
   'Callback','setInfo_itd');
F.tot_ht = F.tot_ht + F.int_ht;
H.itdvector_txt = uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[150 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', 'ITD vector:');
H.itdvector = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[210 itdtestfig_ht-F.tot_ht 135 F.int_ht],...
   'String', num2str(XStimParams.itds),...
   'Callback','setInfo_ITD');




%F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'Num ITDs:');
H.numitds = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.numitds),...
   'Callback','setInfo_ITD');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'ITD Step:');

H.stepitd = uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[82 itdtestfig_ht-F.tot_ht 60 F.int_ht]);

%Other Stimulus Parameters
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht itdtestfig_wd F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Remaining Parameters');
%Freq
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'Frequency (Hz):');
F.int_ht = 20;
H.itd_freq = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_freq));
%ILD
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'ILD (dB):');
F.int_ht = 20;
H.itd_ILD = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_ILD));
%ABL
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'ABL (dB):');
F.int_ht = 20;
H.itd_ABL = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_ABL));
%DUR
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'Stim Dur (ms):');
F.int_ht = 20;
H.itd_DUR = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_stimdur));
%ISI
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'ISI (ms):');
F.int_ht = 20;
H.itd_ISI = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.test_ISI));
%NumReps
F.int_ht = 20; F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', '# Reps:');
F.int_ht = 20;
H.itd_numreps = uicontrol('Parent',H.itdfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 itdtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','SetInfo_itd');

% increment test number
H.itd_inc_testnum = uicontrol('Parent',H.itdfig,...
    'Style','pushbutton',...
   'Units','pixels',...
   'Position',[200 itdtestfig_ht-F.tot_ht 140 F.int_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_itd');

   % modulate  sound
    F.tot_ht = F.tot_ht + F.int_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'File'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'None'
            mod_num = 4;
        otherwise
            mod_num = 1;
    end
    uicontrol('Parent',H.itdfig,...        
        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 itdtestfig_ht - F.tot_ht 80 F.int_ht],...
        'String', '   Modulation:');
    H.itdtestmod_type = uicontrol('Parent',H.itdfig,...        
        'Style','popup',...
        'Units','pixels',...
        'Position',[80 itdtestfig_ht-F.tot_ht 100 F.int_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setInfo_itd');
    H.itdtestmod_txt = uicontrol('Parent',H.itdfig,...        
        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 itdtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', 'Freq:');
    H.itdtestmod_freq = uicontrol('Parent',H.itdfig,...        
        'Style','edit',...
        'Units','pixels',...
        'Position',[220 itdtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setInfo_itd');
    
    H.itdtestmod_txtA = uicontrol('Parent',H.itdfig,...       
        'Style','text',...
        'Units','pixels',...
        'Position',[260 itdtestfig_ht-F.tot_ht 30 F.int_ht],...
        'String', 'depth');
    H.itdtestmod_depth = uicontrol('Parent',H.itdfig,...        
        'Style','edit',...
        'Units','pixels',...
        'Position',[290 itdtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setInfo_itd');

    F.tot_ht = F.tot_ht + F.int_ht;

    H.itdtestmod_txtB = uicontrol('Parent',H.itdfig,...        
        'Style','text',...
        'Units','pixels',...
        'Position',[260 itdtestfig_ht-F.tot_ht 30 F.int_ht],...
        'String', 'phase');
    H.itdtestmod_phase = uicontrol('Parent',H.itdfig,...      
        'Style','edit',...
        'Units','pixels',...
        'Position',[290 itdtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setInfo_itd');
    
    H.itdtestmod_pb = uicontrol('Parent',H.itdfig,...       
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 itdtestfig_ht-F.tot_ht 25 F.int_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setInfo_itd');

    % Only build files?? (do not play them out)
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[15 itdtestfig_ht-F.tot_ht 120 F.int_ht],...
   'String', 'ONLY Build Files?');
H.itd_buildOnly = uicontrol('Parent',H.itdfig,...
'Style','checkbox',...
   'Units','pixels',...
   'Position',[135 itdtestfig_ht-F.tot_ht 20 F.int_ht],...
   'Callback','setInfo_itd');

%%%%%%%%%%
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht itdtestfig_wd F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

%Engage TEST
F.tot_ht = F.tot_ht + F.int_ht;
H.engageitdtest = uicontrol('Parent',H.itdfig,...
    'Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_itdtest');

%Record Data?
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[85 itdtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Record Data?');
H.itd_recorddata = uicontrol('Parent',H.itdfig,...
    'Style','checkbox',...
   'Units','pixels',...
   'Position',[185 itdtestfig_ht-F.tot_ht 20 F.int_ht]);
H.itd_recorddata_FN = uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[85 itdtestfig_ht-(F.tot_ht+F.int_ht) 100 F.int_ht],...
   'String', FN.data);

%Reset
H.resetitdtest = uicontrol('Parent',H.itdfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[itdtestfig_wd-100 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback', 'reset_ITDtest');

%Pause TEST
F.tot_ht = F.tot_ht + F.int_ht*2;
H.pauseitdtest = uicontrol('Parent',H.itdfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exititdtest = uicontrol('Parent',H.itdfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[itdtestfig_wd-100 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_itdtest');

%Build/Play Trials
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
H.itd_buildplay = uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 175 F.int_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'Build/Play Status');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Remaining reps:');
H.itd_remreps = uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[102 itdtestfig_ht-F.tot_ht 40 F.int_ht],...
   'String', get(H.itd_numreps,'String'));
uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[144 itdtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'Trials:');
H.itd_remtrials = uicontrol('Parent',H.itdfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[226 itdtestfig_ht-F.tot_ht 40 F.int_ht],...
   'String', '');

%Plotting
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
H.itd_plotpsd = uicontrol('Parent',H.itdfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 itdtestfig_ht-F.tot_ht 175 F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Plot PSD');

end %end GUI specification

stimuli_dir = FN.temp_stim_path;
setInfo_ITD;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 10000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end
