%LRsounds: the GUI for playing sounds to left adn right ear. Nothing fancy.

%*******************************************************************************
%	The Graphical User Interface
% this version allows differing filenames for each ear
%*******************************************************************************

XStimParams.reset_flag = 0;
dur(1) = XStimParams.curr_stimdur;
dur(2) = XStimParams.curr_stimdur;

%Figure window
if ~exist1('H.LRsoundsfig')
   Xstim_control_pos = get(H.fig,'Position');
   F.x0 = Xstim_control_pos(3) - 300; 
   F.width = 350; F.height = 800;
   H.LRsoundsfig = figure('Units','pixels',...
      'Position',[F.x0 50 F.width F.height],...
      'Name','LRsounds Test',...
      'NumberTitle','off');
F.current_height = 0;
F.inc_height = 20; 
F.current_height = F.current_height + F.inc_height;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height F.width F.inc_height],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'LRsounds Measurement');

% set files to play
F.current_height = F.current_height + F.inc_height;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height F.width F.inc_height],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'stimulus FNs');

% stimbuilderpb
F.current_height = F.current_height + F.inc_height;
H.LR_stimbuilderpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[20 F.height-F.current_height 100 F.inc_height],...
   'BackgroundColor','green',...
   'ForegroundColor','blue',...
   'String', 'Engage Stimbuilder',...
   'Callback','setinfo_LRsounds');

% LR stim FN
F.current_height = F.current_height + F.inc_height*1.2;
H.LR_stimFNpb(1) = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[20 F.height-F.current_height 55 F.inc_height],...
   'BackgroundColor','red',...
   'ForegroundColor','black',...
   'String', 'FN-left',...
   'Callback','setinfo_LRsounds');
H.LR_stimFN = uicontrol('Style','text',...
   	'Units','pixels',...
   	'Position',[75 F.height-F.current_height 100 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
    'ForegroundColor','blue',...
   	'String', FN.stim);
H.LR_stimFNpb(2) = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[180 F.height-F.current_height 55 F.inc_height],...
   'BackgroundColor','red',...
   'ForegroundColor','black',...
   'String', 'FN-right',...
   'Callback','setinfo_LRsounds');
H.LR_stimFN(2) = uicontrol('Style','text',...
   	'Units','pixels',...
   	'Position',[235 F.height-F.current_height 100 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
    'ForegroundColor','blue',...
   	'String', FN.stim2);

% zero padding
F.current_height = F.current_height + F.inc_height*1.5;
H.LR_silencetxt(1) = uicontrol('Style','text',...
   	'Units','pixels',...
   	'Position',[0 F.height-F.current_height 80 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
    'ForegroundColor','black',...
   	'String', 'lead silence (ms)');
H.LR_silence_lead = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[90 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.silence_lead),...
   'Callback','setinfo_LRsounds');
H.LR_silencetxt(2) = uicontrol('Style','text',...
   	'Units','pixels',...
   	'Position',[160 F.height-F.current_height 80 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
    'ForegroundColor','black',...
   	'String', 'trail silence (ms)');
H.LR_silence_trail = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[240 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.silence_trail),...
   'Callback','setinfo_LRsounds');


%%%%%%% set parameters to loop through
F.current_height = F.current_height + F.inc_height*1.5;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height F.width F.inc_height],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Stimulus Parameters to test');

% hrtfFN
F.current_height = F.current_height + F.inc_height;
H.LR_hrtfFNpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[20 F.height-F.current_height 100 F.inc_height],...
   'BackgroundColor','green',...
   'ForegroundColor','blue',...
   'String', 'Select hrtf FN',...
   'Callback','setinfo_LRsounds');
H.LR_hrtfFN = uicontrol('Style','text',...
   'Position',[120 F.height-F.current_height 100 F.inc_height],...
    'BackgroundColor',[.8 .8 .8],...
  'ForegroundColor','blue',...
   'String', FN.space_std);
H.LR_hrtftxt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[230 F.height-F.current_height-F.inc_height*.5 60 F.inc_height*1.5],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'using ephone file');

% spacepickerpb
F.current_height = F.current_height + F.inc_height;
H.LR_spacepickerpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[20 F.height-F.current_height 100 F.inc_height],...
   'BackgroundColor','green',...
   'ForegroundColor','blue',...
   'String', 'Engage spacepicker',...
   'Callback','setinfo_LRsounds');


% ITD / ILD / ABL
F.current_height = F.current_height + F.inc_height*2;
H.LR_txt(1) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 60 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'SET ?');
H.LR_txt(2) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[70 F.height-F.current_height 50 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'ITD (us)');
H.LR_setITD = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'BackgroundColor',[.8 .8 .8],...
   'Value', 1, ...
   'Position',[120 F.height-F.current_height 15 F.inc_height],...
   'Callback','setinfo_LRsounds');
H.LR_txt(3) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[140 F.height-F.current_height 50 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'ILD (dB)');
H.LR_setILD = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'BackgroundColor',[.8 .8 .8],...
   'Value', 1, ...
   'Position',[190 F.height-F.current_height 15 F.inc_height],...
   'Callback','setinfo_LRsounds');
H.LR_txt(4) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[210 F.height-F.current_height 50 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'ABL (dB)');
H.LR_setABL = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'BackgroundColor',[.8 .8 .8],...
   'Value', 1, ...
   'Position',[260 F.height-F.current_height 15 F.inc_height],...
   'Callback','setinfo_LRsounds');

% set values
F.current_height = F.current_height + F.inc_height;
H.LR_txt(5) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 60 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'Set value:');
H.ITD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[70 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.curr_ITD),...
   'Callback','setinfo_LRsounds');
H.ILD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[140 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.curr_ILD),...
   'Callback','setinfo_LRsounds');
H.ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[210 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','setinfo_LRsounds');

% low values
F.current_height = F.current_height + F.inc_height;
H.LR_txt(6) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 60 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'Low value:');
H.loitd = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[70 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.loitd),...
   'Callback','setinfo_LRsounds');
H.loild = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[140 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.loild),...
   'Callback','setinfo_LRsounds');
H.loabl = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[210 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.loabl),...
   'Callback','setinfo_LRsounds');

% high values
F.current_height = F.current_height + F.inc_height;
H.LR_txt(7) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 60 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'High value:');
H.hiitd = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[70 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.hiitd),...
   'Callback','setinfo_LRsounds');
H.hiild = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[140 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.hiild),...
   'Callback','setinfo_LRsounds');
H.hiabl = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[210 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.hiabl),...
   'Callback','setinfo_LRsounds');

% number of values
F.current_height = F.current_height + F.inc_height;
H.LR_txt(8) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 60 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'N values :');
H.numitds = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[70 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.numitds),...
   'Callback','setinfo_LRsounds');
H.numilds = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[140 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.numilds),...
   'Callback','setinfo_LRsounds');
H.numabls = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[210 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.numabls),...
   'Callback','setinfo_LRsounds');

% step sizes
F.current_height = F.current_height + F.inc_height;
H.LR_txt(9) = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 60 F.inc_height],...
   'BackgroundColor',[.8 .8 .8],...
   'String', 'Stepsize:');
H.stepitd = uicontrol('Style','text',...
   'Units','pixels',...
   'BackgroundColor',[.7 .7 .7],...
   'Position',[70 F.height-F.current_height 60 F.inc_height]);
H.stepild = uicontrol('Style','text',...
   'Units','pixels',...
   'BackgroundColor',[.7 .7 .7],...
   'Position',[140 F.height-F.current_height 60 F.inc_height]);
H.stepabl = uicontrol('Style','text',...
   'Units','pixels',...
   'BackgroundColor',[.7 .7 .7],...
   'Position',[210 F.height-F.current_height 60 F.inc_height]);



%%%%%%%% Other Stimulus Parameters
F.current_height = F.current_height + F.inc_height*2;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height F.width F.inc_height],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Remaining Parameters');

%DUR
F.current_height = F.current_height + F.inc_height;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 110 F.inc_height],...
   'String', 'stim duration (ms):');
H.DUR = uicontrol('Style','text',...
   'Units','pixels',...
   'BackgroundColor',[.7 .7 .7],...
   'Position',[112 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.curr_stimdur));

%ISI
F.current_height = F.current_height + F.inc_height;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 110 F.inc_height],...
   'String', 'ISI (ms):');
H.ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.test_ISI),...
   'Callback','setinfo_LRsounds');

%NumReps
F.current_height = F.current_height + F.inc_height;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 110 F.inc_height],...
   'String', '# Reps:');
H.numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[112 F.height-F.current_height 60 F.inc_height],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setinfo_LRsounds');

%%%%%%%%% Run test
F.current_height = F.current_height + F.inc_height*2;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height F.width F.inc_height],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');
% increment test number
F.current_height = F.current_height + F.inc_height;
H.inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[200 F.height-F.current_height 140 F.inc_height],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setinfo_LRsounds');


%Engage TEST
F.current_height = F.current_height + F.inc_height*2;
H.engage_LRsounds = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 80 F.inc_height],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_LRsounds');

%Record Data?
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 F.height-F.current_height 100 F.inc_height],...
   'String', 'Record Data?');
H.recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[190 F.height-F.current_height 30 F.inc_height]);
H.recorddata_FN = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 F.height-(F.current_height+F.inc_height) 100 F.inc_height],...
   'String', FN.data);

%Reset
H.resetLRsounds = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.width-100 F.height-F.current_height 80 F.inc_height],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback', 'reset_LRsounds');

%Pause TEST
F.current_height = F.current_height + F.inc_height*2;
H.pauseLRsounds = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 80 F.inc_height],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exitLRsounds = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.width-100 F.height-F.current_height 80 F.inc_height],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_LRsounds');

%Build/Play Trials
F.current_height = F.current_height + F.inc_height*2;
H.buildplay = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 175 F.inc_height],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'Build/Play Status');

%Remaining Reps and Trials
F.current_height = F.current_height + F.inc_height;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.height-F.current_height 100 F.inc_height],...
   'String', 'Remaining reps:');
H.remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 F.height-F.current_height 40 F.inc_height],...
   'String', get(H.numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 F.height-F.current_height 80 F.inc_height],...
   'String', 'Trials:');
H.remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[226 F.height-F.current_height 40 F.inc_height],...
   'String', '');

end %end GUI specification

stimuli_dir = FN.temp_stim_path;
setinfo_LRsounds;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 10000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end