%ILDTest: the GUI for ILD tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;

F.pos_incr = 20;
F.tot_ht = 0;
F.int_ht = 20;
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.spacefig') &...
      ~exist1('H.ildalonefig'))
   Xstim_control_pos = get(H.fig,'Position');
   ildtestfig_l = Xstim_control_pos(3) - 300; ildtestfig_wd = 350; ildtestfig_ht = 950;
   H.ildfig = figure('Units','pixels',...
      'Position',[ildtestfig_l 0 ildtestfig_wd ildtestfig_ht],...
      'Name','ILD Test',...
      'NumberTitle','off');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht ildtestfig_wd F.int_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'ILD Measurement');

%ILD Information
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht ildtestfig_wd F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify ILD Parameters');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'Low ILD:');
H.lowild = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[82 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.loild),...
   'Callback','setInfo_ild');

uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[150 ildtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Arbitrary ILDs:');
H.aritrary_ilds = uicontrol('Parent',H.ildfig,...
'Style','checkbox',...
   'Units','pixels',...
   'Position',[250 ildtestfig_ht-F.tot_ht 20 F.int_ht],...
   'Callback','setInfo_ild');
F.tot_ht = F.tot_ht + F.int_ht;
H.ildvector_txt = uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[150 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', 'ILD vector:');
H.ildvector = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[210 ildtestfig_ht-F.tot_ht 135 F.int_ht],...
   'String', num2str(XStimParams.ilds),...
   'Callback','setInfo_ILD');




%F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'High ILD:');
H.highild = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[82 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.hiild),...
   'Callback','setInfo_ild');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'Num ILDs:');
H.numilds = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[82 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.numilds),...
   'Callback','setInfo_ild');
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'ILD Step:');
H.stepild = uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[82 ildtestfig_ht-F.tot_ht 60 F.int_ht]);

%Other Stimulus Parameters
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht ildtestfig_wd F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Remaining Parameters');
%Freq
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'Frequency (Hz):');

H.ild_freq = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_freq));
%ITD
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'ITD (usec):');

H.ild_ITD = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_ITD));
%ABL
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'ABL (dB):');

H.ild_ABL = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_ABL));
%DUR
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'Stim Dur (ms):');

H.ild_DUR = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.curr_stimdur));
%ISI
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', 'ISI (ms):');

H.ild_ISI = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.test_ISI));
%NumReps
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 110 F.int_ht],...
   'String', '# Reps:');

H.ild_numreps = uicontrol('Parent',H.ildfig,...
    'Style','edit',...
   'Units','pixels',...
   'Position',[112 ildtestfig_ht-F.tot_ht 60 F.int_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setInfo_ILD');

% increment test number
H.ild_inc_testnum = uicontrol('Parent',H.ildfig,...
    'Style','pushbutton',...
   'Units','pixels',...
   'Position',[200 ildtestfig_ht-F.tot_ht 140 F.int_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_ILD');

% use ILD-shape?
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;

uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[85 ildtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Use ILD shape?');
H.useildshape = uicontrol('Parent',H.ildfig,...
    'Style','checkbox',...
   'Units','pixels',...
   'Position',[185 ildtestfig_ht-F.tot_ht 20 F.int_ht],...
   'Callback','setInfo_ILD');



   % modulate  sound
    F.tot_ht = F.tot_ht + F.int_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'File'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'None'
            mod_num = 4;
        otherwise
            mod_num = 1;
    end
    uicontrol('Parent',H.ildfig,...
    'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 ildtestfig_ht - F.tot_ht 80 F.int_ht],...
        'String', '   Modulation:');
    H.ildtestmod_type = uicontrol('Parent',H.ildfig,...
    'Style','popup',...
        'Units','pixels',...
        'Position',[80 ildtestfig_ht-F.tot_ht 100 F.int_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setInfo_ild');
    H.ildtestmod_txt = uicontrol('Parent',H.ildfig,...
            'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 ildtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', 'Freq:');
    H.ildtestmod_freq = uicontrol('Parent',H.ildfig,...
            'Style','edit',...
        'Units','pixels',...
        'Position',[220 ildtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setInfo_ild');
    
    H.ildtestmod_txtA = uicontrol( 'Parent',H.ildfig,...
           'Style','text',...
        'Units','pixels',...
        'Position',[260 ildtestfig_ht-F.tot_ht 30 F.int_ht],...
        'String', 'depth');
    H.ildtestmod_depth = uicontrol(   'Parent',H.ildfig,...
         'Style','edit',...
        'Units','pixels',...
        'Position',[290 ildtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setInfo_ild');

    F.tot_ht = F.tot_ht + F.int_ht;

    H.ildtestmod_txtB = uicontrol(  'Parent',H.ildfig,...
       'Style','text',...
        'Units','pixels',...
        'Position',[260 ildtestfig_ht-F.tot_ht 30 F.int_ht],...
        'String', 'phase');
    H.ildtestmod_phase = uicontrol('Parent',H.ildfig,...
           'Style','edit',...
        'Units','pixels',...
        'Position',[290 ildtestfig_ht-F.tot_ht 40 F.int_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setInfo_ild');
    
    H.ildtestmod_pb = uicontrol( 'Parent',H.ildfig,...
       'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 ildtestfig_ht-F.tot_ht 25 F.int_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setInfo_ild');
 
% Only build files?? (do not play them out)
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[15 ildtestfig_ht-F.tot_ht 120 F.int_ht],...
   'String', 'ONLY Build Files?');
H.ild_buildOnly = uicontrol('Parent',H.ildfig,...
    'Style','checkbox',...
   'Units','pixels',...
   'Position',[135 ildtestfig_ht-F.tot_ht 20 F.int_ht],...
   'Callback','setInfo_ild');

F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht ildtestfig_wd F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');


%Engage TEST
F.tot_ht = F.tot_ht + F.int_ht;
H.engageildtest = uicontrol('Parent',H.ildfig,...
    'Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_ildtest');

%Record Data?

uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[85 ildtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Record Data?');
H.ild_recorddata = uicontrol('Parent',H.ildfig,...
    'Style','checkbox',...
   'Units','pixels',...
   'Position',[185 ildtestfig_ht-F.tot_ht 20 F.int_ht]);
H.ild_recorddata_FN = uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[85 ildtestfig_ht-(F.tot_ht+F.int_ht) 100 F.int_ht],...
   'String', FN.data);

%Reset

H.resetildtest = uicontrol('Parent',H.ildfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[ildtestfig_wd-100 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback','reset_ILDtest');

%Pause TEST
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
H.pauseildtest = uicontrol('Parent',H.ildfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit

H.exitildtest = uicontrol('Parent',H.ildfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[ildtestfig_wd-100 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_ildtest');

%Build/Play Trials
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
H.ild_buildplay = uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 175 F.int_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'Build/Play Status');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.int_ht;
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 100 F.int_ht],...
   'String', 'Remaining reps:');
H.ild_remreps = uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[102 ildtestfig_ht-F.tot_ht 40 F.int_ht],...
   'String', get(H.ild_numreps,'String'));
uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[144 ildtestfig_ht-F.tot_ht 80 F.int_ht],...
   'String', 'Trials:');
H.ild_remtrials = uicontrol('Parent',H.ildfig,...
    'Style','text',...
   'Units','pixels',...
   'Position',[226 ildtestfig_ht-F.tot_ht 40 F.int_ht],...
   'String', '');

%Plotting
F.tot_ht = F.tot_ht + F.int_ht + F.pos_incr;
H.plotpsd = uicontrol('Parent',H.ildfig,...
    'Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 ildtestfig_ht-F.tot_ht 175 F.int_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Plot PSD');

end %end GUI specification

stimuli_dir = FN.temp_stim_path;
setInfo_ild;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 10000) == 0)
   disp('Cannot initialize a secondary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end
