%Control: the GUI for the program suite XStim

clear

Globals_tdt;
Globals_mii;
Globals_var;
Globals_GUI

global H
global F

if exist([ FN.current_path  'XStimParams_current.mat' ],'file')
    eval(['load ', FN.current_path  'XStimParams_current'])
else
    global XStimParams
    XStimParams_func;
end

if exist([ FN.current_path  'FN_current.mat' ],'file')
    eval(['load ', FN.current_path  'FN_current'])
end

Globals_FN_update;      % update FN to current XStimParams.bird_number

%Figure window
F.Xind_ = .03;
F.Xtot_ht = 0;
scrn=get(0,'ScreenSize');
F.scrn_ht=scrn(4)-scrn(2);
F.scrn_wd=scrn(3)-scrn(1);
F.X_lt=scrn(1)+round(.05*F.scrn_wd); F.X_btm = scrn(2) + round(.05*F.scrn_ht);
F.X_wd=round(.45*F.scrn_wd); F.X_ht = round(.9*F.scrn_ht);
H.fig = figure('Units','pixels',...
   'Position',[F.X_lt F.X_btm F.X_wd F.X_ht],...
   'Name','XStim Control',...
   'NumberTitle','off');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht 1 F.Xind_],...
   'ForegroundColor','green',...
   'BackgroundColor','black',...
   'FontWeight','bold',...
   'FontSize',12,...
   'String', 'XStim Control');

%Display parameters
F.Xtot_ht = F.Xtot_ht + 1.2*F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'HorizontalAlignment','left',...
   'String', '   Session Specs:');
% Display datafilename
H.xstim_recorddata_FN = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'ForegroundColor','blue',...
   'HorizontalAlignment','center',...
   'String', FN.data);
% EXIT pushbutton
H.initsess = uicontrol('Parent',H.fig,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .35 F.Xind_],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontSize',8,...
   'HorizontalAlignment','left',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback', 'exitXstim');

% bird number
F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Bird Number');
H.controlbirdnumber = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'String', num2str(XStimParams.bird_number),...
   'Callback','setInfo_Xstim');

% increment test number
H.Xstim_inctestnum = uicontrol('Parent',H.fig,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht-F.Xind_ .35 F.Xind_],...
   'BackgroundColor','white',...
   'ForegroundColor','blue',...
   'FontSize',10,...
   'String', 'Increment testnum',...
   'Callback', 'setInfo_Xstim');

% Recording site
F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Recording Site');
H.recording_site = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'String', num2str(XStimParams.recording_site),...
   'Callback','setInfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_;

% test number
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Test Number');
H.testnum = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'String', num2str(XStimParams.testnum),...
   'Callback','setInfo_Xstim'); 

%Recording Site Information
F.Xtot_ht = F.Xtot_ht + 1.2*F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'HorizontalAlignment','left',...
   'String', '  Recording Site Specs:');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'String', 'Anterior/Posterior Position',...
   'HorizontalAlignment','left',...
   'Callback','setInfo_Xstim');

H.ap_pos = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'String', num2str(XStimParams.ap_pos));
F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Medial/Lateral Position');

H.ml_pos = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'String', num2str(XStimParams.ml_pos),...
   'Callback','setInfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .35 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Depth');

H.depth = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.37 1-F.Xtot_ht .2 F.Xind_],...
   'String', num2str(XStimParams.depth),...
   'Callback','setInfo_Xstim');

%Test types: popupmenu
F.Xtot_ht = F.Xtot_ht + 1.2*F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Choose Test Type');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.test_type = uicontrol('Parent',H.fig,...
   'Style','popup',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .4 F.Xind_],...
   'BackgroundColor','white',...
   'value', 1,...
   'String', ['None|Search for Cells|ABL|ITD|ILD|FREQ|McSpace|Mc2Source|Space|' ...
            'Space2|Space3|2Source|AltIR|AM|ITD2|ITD_decorr|Composite|BMLD|' ...
            'LRsounds|Adapt1|Adapt2|Space4|McSpace2|FilePerRep|LongSAMs|' ...
            'MaskedSpace|PE_env|SpaceRIR|AdaptedSpace'],...
   'Callback','setInfo_Xstim');

%First Stimulus types: popupmenu
F.Xtot_ht = F.Xtot_ht - F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Choose 1st Stimulus Type');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.stim_type = uicontrol('Parent',H.fig,...
   'Style','popup',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'BackgroundColor','white',...
   'String',...
   'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|BBN-LNN|None',...
   'Callback','Stimulus_type1');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.stim_filename = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','black',...
   'String', FN.stim);
if get(H.stim_type,'Value')==9
   set(H.stim_filename,'Enable','on');
else
   set(H.stim_filename,'Enable','off');   
end

%Second Stimulus types: popupmenu
F.Xtot_ht = F.Xtot_ht + 1.2*F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Choose 2nd Stimulus Type');
F.Xtot_ht = F.Xtot_ht + F.Xind_;

% current stim duration
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'stim1 dur (ms)');
H.Xstim_curr_stimdur = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.23 1-F.Xtot_ht .15 F.Xind_],...
   'BackgroundColor','white',...
   'String', XStimParams.curr_stimdur,...
   'Callback','setinfo_Xstim');

% stimtype2
H.stim_type2 = uicontrol('Parent',H.fig,...
   'Style','popup',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'BackgroundColor','white',...
   'String',...
   'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|BBN-LNN|None',...
   'Callback','Stimulus_type2');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.stim_filename2 = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','black',...
   'String', FN.stim2);
if get(H.stim_type2,'Value')==9
   set(H.stim_filename2,'Enable','on');
else
   set(H.stim_filename2,'Enable','off');   
end

% leading silence dur
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'silence_lead (ms)');
H.Xstim_silence_lead = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.23 1-F.Xtot_ht .15 F.Xind_],...
   'BackgroundColor','white',...
   'String', XStimParams.silence_lead,...
   'Callback','setinfo_Xstim');

%Third Stimulus types: popupmenu
F.Xtot_ht = F.Xtot_ht + F.Xind_;
% trailing silence dur
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'silence_trail (ms)');
H.Xstim_silence_trail = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.23 1-F.Xtot_ht .15 F.Xind_],...
   'BackgroundColor','white',...
   'String', XStimParams.silence_trail,...
   'Callback','setinfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Choose 3rd Stimulus Type');

% test_ISI
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'test ISI (ms)');
H.Xstim_test_ISI = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.23 1-F.Xtot_ht .15 F.Xind_],...
   'BackgroundColor','white',...
   'String', XStimParams.test_ISI,...
   'Callback','setinfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_;

% stim_type3
H.stim_type3 = uicontrol('Parent',H.fig,...
   'Style','popup',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'BackgroundColor','white',...
   'String',...
   'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|BBN-LNN|None',...
   'Callback','Stimulus_type3');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.stim_filename3 = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.6 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','black',...
   'String', FN.stim3);
if get(H.stim_type3,'Value')==9
   set(H.stim_filename3,'Enable','on');
else
   set(H.stim_filename3,'Enable','off');   
end

%Earphone filter file for non-space tests
F.Xtot_ht = F.Xtot_ht + F.Xind_*1.2;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .46 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Earphone File for non-space tests: ');
H.ephonefile = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'ForeGroundColor','blue',...
   'Position',[.46 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', FN.ephone);
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.8 1-F.Xtot_ht .11 F.Xind_],...
   'String', 'Use it?');
H.ephoneuseit = uicontrol('Parent',H.fig,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.91 1-F.Xtot_ht .06 F.Xind_],...
   'Value',XStimParams.ephone_flag,...
   'Callback','setinfo_Xstim');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.ephonepb = uicontrol('Parent',H.fig,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.01 1-F.Xtot_ht .44 F.Xind_],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select Earphone Filter File',...
   'Callback','setinfo_Xstim');

%Earphone filter file2 for space tests
F.Xtot_ht = F.Xtot_ht + F.Xind_*1.2;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .46 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'Earphone File for space tests: ');
H.ephonefile2 = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'ForeGroundColor','blue',...
   'Position',[.46 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', FN.ephone2);
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.ephonepb2 = uicontrol('Parent',H.fig,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.01 1-F.Xtot_ht .44 F.Xind_],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select Earphone Filter File2',...
   'Callback','setinfo_Xstim');

%Loc filter file - for presentation through 1 specified virtual location
F.Xtot_ht = F.Xtot_ht + F.Xind_*1.2;
H.locfilehdr = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .46 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', 'HRTF File for one location:');
H.locfile = uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'ForeGroundColor','blue',...
   'Position',[.46 1-F.Xtot_ht .23 F.Xind_],...
   'HorizontalAlignment','left',...
   'String', FN.loc);
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.8 1-F.Xtot_ht .11 F.Xind_],...
   'String', 'Use it?');
H.locuseit = uicontrol('Parent',H.fig,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',[.91 1-F.Xtot_ht .06 F.Xind_],...
   'Value',XStimParams.loc_flag,...
   'Callback','setinfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .2 F.Xind_],...
   'String', 'Azimuth');
H.locAZ = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.2 1-F.Xtot_ht .1 F.Xind_],...
   'BackgroundColor','white',...
   'String', XStimParams.loc_azel(1),...
   'Callback','setinfo_Xstim');
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[.3 1-F.Xtot_ht .2 F.Xind_],...
   'String', 'Elevation:');
H.locEL = uicontrol('Parent',H.fig,...
   'Style','edit',...
   'Units','normalized',...
   'Position',[.5 1-F.Xtot_ht .1 F.Xind_],...
   'BackgroundColor','white',...
   'String', XStimParams.loc_azel(2),...
   'Callback','setinfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.locpb = uicontrol('Parent',H.fig,...
   'Style','pushbutton',...
   'Units','normalized',...
   'Position',[.01 1-F.Xtot_ht .44 F.Xind_],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Select Location Filter File',...
   'Callback','setinfo_Xstim');


% Diary entry
F.Xtot_ht = F.Xtot_ht + F.Xind_*1.2;
H.diaryEntry = uicontrol('Style','pushbutton',...
   'Units','normalized',...
   'Position',[.465 1-F.Xtot_ht .27 F.Xind_],...
   'BackgroundColor','green',...
   'ForegroundColor','blue',...
   'String', 'diary entry',...
   'Callback','setinfo_Xstim');

%Data Analysis Tools: popupmenu
F.Xtot_ht = F.Xtot_ht + F.Xind_*1.2;
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Data Analysis Tools');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.datatools = uicontrol('Parent',H.fig,...
   'Style','popup',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .4 F.Xind_],...
   'BackgroundColor','white',...
   'String', ...
   'Calculate ILDalone weights|ILDAlone Multiple Regression',...
   'Callback','datatools');

H.S2closepb = uicontrol('Style','pushbutton',...
   'Units','normalized',...
   'Position',[.465 1-F.Xtot_ht .27 F.Xind_],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'S2close',...
   'Callback','setinfo_Xstim');

F.Xtot_ht = F.Xtot_ht + F.Xind_*1.2;
H.ClearStimspb = uicontrol('Style','pushbutton',...
   'Units','normalized',...
   'Position',[.465 1-F.Xtot_ht .27 F.Xind_],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'Clear Stimuli',...
   'Callback','setinfo_Xstim');


%HELP: popupmenu
uicontrol('Parent',H.fig,...
   'Style','text',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .4 F.Xind_],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Help');
F.Xtot_ht = F.Xtot_ht + F.Xind_;
H.Xstim_help = uicontrol('Parent',H.fig,...
   'Style','popup',...
   'Units','normalized',...
   'Position',[0 1-F.Xtot_ht .4 F.Xind_],...
   'BackgroundColor','white',...
   'String', ...
   'Timing Hangups|HRTF files',...
   'Callback','Xstim_help');

set(H.fig,'HandleVisibility','off');
eval(['save ' FN.current_path 'H_xstim H;']);

testtype = get(H.test_type,'String');
for s=1:size(testtype,1)
   if(strcmp(testtype(s,:),XStimParams.test_type))
      set(H.test_type,'Value',s);
   end
end

stim_type = get(H.stim_type,'String');
for s=1:size(stim_type,1)
   if(strcmp(stim_type(s,:),XStimParams.stim_type))
      set(H.stim_type,'Value',s);
   end
end

clear testtype stim_type


setInfo_Xstim