function [] = XStimParams_func()
%Function to specify the basic XStimParams structure
%and set the default values
global FN
global XStimParams

Globals_var;

XStimParams = struct(...
   'bird_number',				0,...
   'side_of_brain',             'L',...
   'session_num',				1,...
   'recording_site',			1,...
   'ap_pos',					0,...
   'ml_pos',					0,...
   'depth',						0,...
   'testnum',					0,...
   'numreps',					3,...
   'curr_freq',                 6500,...
   'curr_ITD',					0,...
   'curr_ILD',					0,...
   'curr_ABL',					-70,...
   'curr_stimdur',              100,...
   'curr_stimdur2',             900,...
   'search_ISI',				500,...
   'test_ISI',					100,...
   'lofreq',					2000,...
   'hifreq',					11000,...
   'numfreqs',					21,...
   'loitd',						-250,...
   'hiitd',						250,...
   'numitds',					100,...
   'itds',                      [],...
   'loild',						-30,...
   'hiild',						30,...
   'numilds',					16,...
   'ilds',                      [],...
   'loabl',						-110,...
   'hiabl',						-30,...
   'numabls',					15,...
   'abls',                      [],...
   'num_NBNoiseStackBands',	    1,...
   'spec_NBNoiseStackBands',	[2000 3000],...
   'bandwidth',				[1/3 1/3 1/3], ...
   'bandlimits',			[2000 11000 2000 11000 2000 11000],...
   'locations',				[],...
   'offset_az',				[0 -30 30],...
   'offset_el',				[0 30 30],...
   'space_flag',			1,...
   'ABLequal_flag',         0,...
   'ildalone_flag',         0,...
   'itdalone_flag',         0,...
   'ABLalone_flag',         0,...
   'ephone_flag',			0,...
   'loc_azel',				[0 0],...
   'loc_flag',				0,...
   'test_type',				'Space',...
   'McTestType',            '',...
   'stim_type',				'Tone',...
   'stim_type2',			'None',...
   'stim_type3',			'None',...
   'mod_type',				'Tone',...
   'mod_type2',				'Tone',...
   'mod_type3',				'Tone',...
   'mod_freq',				[55 75 90],...
   'mod_depth',				[.5 .5 .5],...
   'mod_phase',             [0 0 0],...
   'mod_dB',                40,...
   'factor',				[.5 .5 1],...
   'freq',                  [5000 5000 5000],...
   'picker_flag',				1,...
   'use_saveHRTFflag',          0,...
   'use_saveALTflag',          0,...
   'silence_lead',              100,...
   'silence_mid',               500,...
   'silence_trail',             100,...
   'ramppts',                   0, ...
   'az',                        0,...
   'el',                        0,...
   'useILDshape',               0, ...
   'reset_flag',                0, ...
   'GUIspaceres',              'max', ...
   'HiDynamicRange',            0, ...
   'bandlimits1',				[], ...
   'bandlimits2',				[], ...
   'locations1',                [], ...
   'locations2',                [], ...
   'buildOnly',                 0, ...
   'focalSPL',                  [0 30], ...
   'focalProb',                 1, ...
   'epoch_duration',            [50 50], ...
   'focalSPL2',                 [0 30], ...
   'focalProb2',                1, ...
   'SPLinc',                    [1 1], ...
   'rndSPLs',                   1,...
   'regime_duration',           [2000 2000], ...
   'source1_SPL',               15, ...
   'source1_ISI',               10, ...
   'offEpochs',                 19, ...
   'onEpochs',                  21, ...
   'repeatmode',                0, ...
   'SPL1',                      21, ...
   'SPL2',                      [1 11 31 41], ...
   'probeFlag',                 [1 0], ...
   'mu',                        [30 30 30 60], ...
   'sigma',                     [3 40 3 3], ...
   'ramp',                      1, ...
   'probe_add_dB',              0, ...
   'mask_add_dB',               0, ...
   'HRTF_FN',                   '', ...
   'RIRpts2use',                1000);

eval(['save ' FN.current_path 'XStimParams_default XStimParams']);
eval(['save ' FN.current_path 'XStimParams_current XStimParams']);



if 0 
   'Mag_octlistBIN',            zeros(1,29),...
   'Phase_octlistBIN',          zeros(1,29),...
   'Twelths_to_combine',        1, ...
   'alter_left',                1,...
   'alter_right',               1,...
   'alterMag',                  1,...
   'alterMag_Minbandlimits',    4000,...
   'alterMag_Maxbandlimits',    8000,...
   'alterMag_dB',               10,...
   'alterPhase',                0,...
   'alterPhase_Minbandlimits',  4000,...
   'alterPhase_Maxbandlimits',  8000,...
   'alterPhase_rad',            pi,...
   'alter_setbands',            0,...

    'ThreeStims',                0, ...
   'ITD',						[0 0 0], ...
   'az2',                       0,...
   'el2',                       0,...
   'az3',                       0,...
   'el3',                       0,...
   'stimfile',					'',...
   'SilentDelay',              0, ...
   'uncorrel',                 0, ...
   'SilentLag',                0, ...
   'randOnsetPerms',           0, ...
   'DelayMods',                [0 0 0 0], ...
   'DelayTimes',               [-200 -100 -50 -20 -10 -5 -2 -1 1 2 5 10 20 50 100 200], ...
   'ramp_timeS_on',            [1 2.5 5 10 20 50], ...
   'ramp_timeS_off',           [1 2.5 5 10 20 50], ...
   'lag_seg_ext',              [0 30 NaN], ...
   'OnOff_mode',               1, ...
   'Delay_default',            1,...
   'sub_locations',			    [], ...
end