%PlayFile: the GUI for Play a File tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;
GUI.locations1 = [];
GUI.locations2 = [];
% to start things off:
XStimParams.itdalone_flag = 0;
XStimParams.ildalone_flag = 0;
XStimParams.ABLalone_flag = 0;
XStimParams.PlayFile_flag = 1;

F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.PlayFilefig'))
   temp = get(H.fig,'Position');
   F.PlayFile_l = temp(3) - 300; 
   F.PlayFile_wd = 400; 
   F.PlayFile_ht = 900;
   H.PlayFilefig = figure('Units','pixels',...
      'Position',[F.PlayFile_l 100 F.PlayFile_wd F.PlayFile_ht],...
      'Name','Play a File Measurement',...
      'NumberTitle','off');
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht F.PlayFile_wd F.ind_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Play a File Measurement');

%reminder
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht F.PlayFile_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'NO Filters and NO HRIRs');

%Specify HRTF and Location files
F.tot_ht = F.tot_ht + F.ind_ht;

%Fully-cued HRTF file
F.tot_ht = F.tot_ht + F.ind_ht;
F.tot_ht = F.tot_ht + F.ind_ht;

%ILDAlone filter file
F.tot_ht = F.tot_ht + F.ind_ht;
F.tot_ht = F.tot_ht + F.ind_ht;

%ITDAlone filter file
F.tot_ht = F.tot_ht + F.ind_ht;
F.tot_ht = F.tot_ht + F.ind_ht;

F.tot_ht = F.tot_ht + F.ind_ht*2;
%Set Stimulus Parameters
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht F.PlayFile_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Set Stimulus Parameters');
F.tot_ht = F.tot_ht + F.ind_ht;    


uicontrol('Parent',H.PlayFilefig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[2 F.PlayFile_ht-F.tot_ht 110 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
   	'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Choose Stim Type');
H.PlayFile_stim_type = uicontrol('Parent',H.PlayFilefig,...
   'Style','popup',...
   'Units','pixels',...
   'Position',[112 F.PlayFile_ht-F.tot_ht 110 F.ind_ht],...
   'BackgroundColor','white',...
   'String',...
   'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|None',...
   'Value',get(H.stim_type,'Value'),...
   'Callback','setinfo_PlayFile');


H.PlayFile_stimFNpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[222 F.PlayFile_ht-F.tot_ht 20 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'FN',...
   'Callback','setinfo_PlayFile');
H.PlayFile_stimFN = uicontrol('Parent',H.PlayFilefig,...
   	'Style','text',...
   	'Units','pixels',...
   	'Position',[242 F.PlayFile_ht - F.tot_ht F.PlayFile_wd-242 F.ind_ht],...
    'ForegroundColor','blue',...
   	'String', FN.stim);

F.tot_ht = F.tot_ht + F.ind_ht;
H.PlayFile_NoScalingpb = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[2 F.PlayFile_ht-F.tot_ht 200 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'push for No Stim Scaling',...
   'Callback','setinfo_PlayFile');

H.PlayFile_DynamicRangepb = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[222 F.PlayFile_ht-F.tot_ht F.PlayFile_wd-222 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'String', 'push for High Dynamic Range',...
   'Callback','setinfo_PlayFile');

F.tot_ht = F.tot_ht + F.ind_ht;
H.PlayFile_DynamicRangeTxt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[222 F.PlayFile_ht-F.tot_ht F.PlayFile_wd-222 F.ind_ht],...
   	'BackgroundColor',[.8 .8 .8],...
   'String', 'SPL now 20dB below normal');

F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 205 F.ind_ht],...
   'String', 'Bandwidth for BPNoise (octaves)');
H.PlayFile_bandwidth = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[205 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandwidth),...
   'Callback','SetBandWidth');
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 155 F.ind_ht],...
   'String', 'Bandlimits for NBNoise');
H.PlayFile_bandlimits1 = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[155 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandlimits(1)),...
   'Callback','SetBandLimits');
H.PlayFile_bandlimits2 = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[240 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','white',...
   'String', num2str(XStimParams.bandlimits(2)),...
   'Callback','SetBandLimits');

%ABL (atten)
F.tot_ht = F.tot_ht + 2*F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Atten (dB):');
H.PlayFile_ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','SetInfo_PlayFile');
% ITD?
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ITD (us):');
H.PlayFile_ITD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ITD),...
   'Callback','SetInfo_PlayFile');

%DUR
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Stim Dur (ms):');
H.PlayFile_DUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_stimdur),...
   'Callback','SetInfo_PlayFile');

% ILD?
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ILD');
H.PlayFile_ILD = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ILD),...
   'Callback','SetInfo_PlayFile');

%ISI
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ISI (ms):');
H.PlayFile_ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.test_ISI));
%NumReps
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'String', '# Reps:');
H.PlayFile_numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setinfo_PlayFile');

   % modulate  sound
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'Sq wave'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'File'
            mod_num = 4;
        case 'None'
            mod_num = 5;
        otherwise
            mod_num = 5;
    end
    uicontrol(        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.PlayFile_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   Modulation:');
    H.PlayFiletestmod_type = uicontrol(        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.PlayFile_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|Sq wave|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setInfo_PlayFile');
    H.PlayFiletestmod_txt = uicontrol(        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.PlayFile_ht-F.tot_ht 40 F.ind_ht],...
        'String', 'Freq:');
    H.PlayFiletestmod_freq = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[220 F.PlayFile_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setInfo_PlayFile');
    
    H.PlayFiletestmod_txtA = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.PlayFile_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'depth');
    H.PlayFiletestmod_depth = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.PlayFile_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setInfo_PlayFile');

F.tot_ht = F.tot_ht + F.ind_ht;

    H.PlayFiletestmod_txtB = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.PlayFile_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'phase');
    H.PlayFiletestmod_phase = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.PlayFile_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setInfo_PlayFile');
    
    H.PlayFiletestmod_pb = uicontrol(        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.PlayFile_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setInfo_PlayFile');


%%%%%%%%%%%
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht F.PlayFile_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

F.tot_ht = F.tot_ht + F.ind_ht;

% increment test number
H.PlayFile_inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[250 F.PlayFile_ht-F.tot_ht 140 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_PlayFile');


%Engage TEST
H.engagePlayFile = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_PlayFile');

%Record Data?
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 F.PlayFile_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Record Data?');
H.PlayFile_recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[185 F.PlayFile_ht-F.tot_ht 20 F.ind_ht],...
   'Callback','setInfo_PlayFile');
F.tot_ht = F.tot_ht + F.ind_ht;
H.PlayFiledata_FN = uicontrol('Style','text',...
   'Units','pixels',...
   'ForegroundColor','blue',...
   'Position',[85 F.PlayFile_ht-F.tot_ht 100 F.ind_ht],...
   'String', FN.data);

%Reset
F.tot_ht = F.tot_ht + F.ind_ht;
H.resetPlayFile = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.PlayFile_wd-100 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback','Reset_PlayFile');

%Pause TEST
F.ind_ht = 20; 
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.pausePlayFile = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 80 F.ind_ht*2],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exitPlayFile = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.PlayFile_wd-100 F.PlayFile_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_PlayFile');

%Status bar
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.PlayFile_status = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht F.PlayFile_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Status: setting parameters');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.PlayFile_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Remaining Reps:');
H.PlayFile_remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 F.PlayFile_ht-F.tot_ht 40 F.ind_ht],...
   'String', get(H.PlayFile_numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 F.PlayFile_ht-F.tot_ht 60 F.ind_ht],...
   'String', 'Trials:');
H.PlayFile_remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[206 F.PlayFile_ht-F.tot_ht 40 F.ind_ht],...
   'String', '');

end %end GUI specification

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
   disp('Cannot initialize a primary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end

SetInfo_PlayFile;