%NBNoiseStackBands: script to set the frequency bands for the NarrowBand Noise Stack

if(exist1('H.num_NBNoiseStackBands'))
   XStimParams.num_NBNoiseStackBands = str2num(get(H.num_NBNoiseStackBands,'String'));
   if(XStimParams.num_NBNoiseStackBands > 20)
      XStimParams.num_NBNoiseStackBands = 20;
      set(H.num_NBNoiseStackBands,'String',num2str(XStimParams.num_NBNoiseStackBands));
   end
else
   XStimParams.num_NBNoiseStackBands = size(XStimParams.spec_NBNoiseStackBands,1);
end

if(exist1('H.NBNoiseStackBands'))
   close(H.NBNoiseStackBands);
   clear H.NBNoiseStackBands;
end

fig_ht = 500;
fig_wd = 300;
tot_ht = 10;
pos_incr = 20;
ind_ht = 20; tot_ht = tot_ht + ind_ht;
H.NBNoiseStackBands = figure('Position',[300 300 fig_wd fig_ht],...
   'Name','Select Bands for NBNoise Stack',...
   'NumberTitle','off');

%Number of bands
uicontrol('Parent',H.NBNoiseStackBands,...
   'Style','text',...
   'Units','pixels',...
   'Position',[0 fig_ht-tot_ht 75 ind_ht],...
   'FontSize',6,...
   'String','# of Bands');
H.num_NBNoiseStackBands = uicontrol('Parent',H.NBNoiseStackBands,...
   'Style','edit',...
   'Units','pixels',...
   'Position',[105 fig_ht-tot_ht 75 ind_ht],...
   'FontSize',8,...
   'String',num2str(XStimParams.num_NBNoiseStackBands),...
   'Callback','NBNoiseStackBands');

%Band specifications
ind_ht = 20;tot_ht = tot_ht + ind_ht + pos_incr;
for bandnum = 1:XStimParams.num_NBNoiseStackBands
   uicontrol('Parent',H.NBNoiseStackBands,...
      'Style','text',...
      'Position',[0 fig_ht-tot_ht 75 ind_ht],...
      'FontSize',8,...
      'String',['Band # ' num2str(bandnum) ': ']);
   if(bandnum <= size(XStimParams.spec_NBNoiseStackBands,1))
      H.spec_NBNoiseStackBands(bandnum) = uicontrol('Parent',H.NBNoiseStackBands,...
         'Style','edit',...
         'Position',[105 fig_ht-tot_ht 100 ind_ht],...
         'FontSize',8,...
         'String',[num2str(XStimParams.spec_NBNoiseStackBands(bandnum,1)) '  ' num2str(XStimParams.spec_NBNoiseStackBands(bandnum,2))]);
   else
      H.spec_NBNoiseStackBands(bandnum) = uicontrol('Parent',H.NBNoiseStackBands,...
         'Style','edit',...
         'Position',[105 fig_ht-tot_ht 100 ind_ht],...
         'FontSize',8,...
         'String',[num2str(XStimParams.spec_NBNoiseStackBands(1,1)) '  ' num2str(XStimParams.spec_NBNoiseStackBands(1,2))]);
   end
   tot_ht = tot_ht + ind_ht;
end

%Accept specified bands
ind_ht = 20;tot_ht = tot_ht + ind_ht + pos_incr;
H.accept_NBNoiseStackBands = uicontrol('Parent',H.NBNoiseStackBands,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 fig_ht-480 75 ind_ht],...
   'FontSize',8,...
   'Value',0,...
   'String','OK!',...
   'Callback','accept_NBNoiseStackBands');

%Cancel specified bands
ind_ht = 20;
H.cancel_NBNoiseStackBands = uicontrol('Parent',H.NBNoiseStackBands,...
   'Style','pushbutton',...
   'Units','pixels',...
   'Position',[fig_wd-80 fig_ht-480 75 ind_ht],...
   'FontSize',8,...
   'Value',0,...
   'String','Cancel!',...
   'Callback','close_hNBNoiseStackBands');