figure

dlist = dir;

hbrowser = uicontrol('Style','popupmenu',...
   'Units','pixels',...
   'Position',[100 100 100 20],...
   'ButtonDownFcn','form_directory_list',...
   'String',str2mat(dlist(1:length(dlist)).name),...
   'Callback','sel_browser_item');