%%% update log to xstim - begun March 4, 2003

% March 4, 2003: discovered and fixed problem in 2source (kip):
%       locind has dimensions of (Nsources x Nlocs)
%   when constructing files, however, the extra rows generated by Nsources > 1 was neglected
%   therefore, the index (locind(randseq(trialnum))) was incorrect and the files (whose names are indexed to source1)
%   would have had the wrong locations.  Although the fix is easy (locind(1,randseq(trialnum))), there does
%   not seem to be any way to recover the old data.  The recall of files when playing should call the
%   same (mistaken) locations as when they were written.  The recorded locations in DATA, however, are the INTENDED
%   locations (at least the ones that elicited spikes).
%   Stim files are now routinely erased at the beginning of each test to eliminate possible problems of mistaken calls.

% March 18, 2003: reworked scaling in all tests 
%   to make scaling responsive to mom(signal,2) instead of max(signal)
%   therefore also changed tdt.scalefactor from 15000 to 2000
%   sounds are now slightly louder (<6 dB), but more consistent across tests
% ALSO: in space, eliminated DC-offset before convolution with HRTFs - so now space == altIR (0)

% June 1, 2003: in 2-source:
%   problem with make_env that always used mod_freq and mod_depth
%   from stimulus number1 (so all stims had same mod depth and freq)
%   changed to use input param1,param2 to carry the correct depth and freq
%   This problem was incurred with the moving of enveloping to a separate function on either 3/4 or 3/18/03
%   and did not exist before these dates
% ALSO: eliminated all 2nd buffercycle stuff from 2-source
% ALSO: get_Stim had the same type of problem and always used stim_path and stim for each FN 
%   and always used freq(1) for each source.  Problem dating from 3/03

% June 20, 2003: in 2-source:
% changed sign of adding offset3 (was subtracting) to base location for calc of loc3


% Oct 07, 2003: in 2-source
% changed the if statements for getting files and modulating stim #2 and #3
% to ask for #2 and #3 instead of previously asking (incorrectly) about #1 

% Oct 14, 2003: in 2-source
% changed the main data collection loop to run numtrials+1 -
% first trial is just for loading and i+1 trial plays the ith stimulus
% previously this was all true, except the first trial was played without recording and, it seems, 
% that the spikes for each location were actually attributed to the i-1 location.
% and the first location's spikes were not recorded at all
% I think this could be checked in the data files to see if it is true.  
% (e.g. how many reps were played in one-location tests e.g. the long_b10 trials)

% Oct 16, 2003: in 2-source
% checked out data collection and it seems ok - also seems as though previous collection was correct 
% even though one loc was always not played (so data is ok, just shy one)
% added tempseq{} to 2-source and as 3rd argin to record_data3
% this will be a cell array with the randseq for each rep
% this can then be used with params.locations to tell exactly which location was played when

% Sept 2, 2004: in 2-source, space, space3, altIR
% in response to new HRTF file type (*.mat)
% added to globals, FN.HRTFfiletype[1-6]
% 1-6, in order:
%   space, ila, ita, loc, ephone, ephone2
%
% filetypes:    0) untested
%               1) traditional binary
%               2) new *.mat with TRF1 and TF2
%               999) non-readable
%
% created testHRTFfiletype.m to check which type and added this checking to
% start of xstim.m
% then within each engage* and setinfo*, many alterations were made to use
% either one filetype or the other. These generally involve testing
% FN.HRTFfiletype(x) and then either using the old code or using new code
% that uses eval to load the new filetype (note that importing dir
% conflicts with the MATLAB function dir, and you must first set dir=0 or
% some value.

% August, 2004: in 2-source and space
% added ABL-alone test

% Sept 24, 2004: in 2-source
% in looking at stimulus envelopes, discovered that ABLalone test
% incorrectly normalizes the two (or 3) sources to have the same amplitude
% this was corrected by doing the normalization only during the
% ILA and ITA tests


% Oct 14, 2004: in Space
% corrected ITA test to use proper TF...(ind,:) instead of TF...(ind) (so
% this was a problem only from Sept 2 and only for ITA tests (and probably
% resulted in inverted response plots)
% ALSO corrected set_info to update el and az for ITA tests - this must
% have been a problem for a while - but probably not major (ITA probably similar
% with any ILD)
% Oct 14, 2004: in 2_Source
% corrected set_info to update el and az for ITA tests - this must have
% been a problem for a while - but probably not major (ITA probably similar
% with any ILD)
% ALSO: cleaned up resetting of various params from space and 2_source menus
% ALSO: changed various XStimParams for modulation to be 3 element vectors
% instead of 3 separate struture elements
% ALSO: changed scaling in ILD-test to use mom instead of max to match the
% other tests

% April 2006 changed some things in altIR

% May 3, 2006 made ITDtest2
% this allows separate file stimuli to be played out to each ear
% direct clone of itdtest

% May 8, 2006 in ALTIR
% allowed saving or use of just the alterations (not the actual hrtfs)
% so that different tests (FC or ILA) can be run with the same alterations
% USING saved hrtfs or ALTerations forces the engageALTIR program to use
% the saved locations, alterations, etc.

% May 9, 2006 in XStim
% created script: Globals_FN_update, that updates the hrtf FNs depending on
% the birdnumber and also checks for HRTF_Filetype

% May 9, 2006 in ALTIR
% allowed averaging across 1/12th octave bands to effectively allow 1/12,
% 1/6, 1/4, 1/3, 1/2 octave bands

% October 8, 2007 in McSpace
% changed to allow repeat of the same stimulus for each rep repeatmode = 1
% and to allow use of the same stim b/wn runs (using stimfile)
% this use of stimfile is somewhat different than in other modules

% 
%%% missed alot

% June 8, 2009
% changed scaling on several modules to try to equalize them
% masked_space scaled * 1.732 so as to normalize to the 2nd moment of the
% stim (don't know how to do this easily on the TDT)
% Mc2source: scaled by 1.732 and changed default scaling to .5