%MaskedSpace: the GUI for Maskedspace tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;
GUI.locations1 = [];
GUI.locations2 = [];
% to start things off:
XStimParams.itdalone_flag = 0;
XStimParams.ildalone_flag = 0;
XStimParams.ABLalone_flag = 0;
XStimParams.space_flag = 1;
TDT.S232_status = 0;

F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.MaskedSpacefig'))
   temp = get(H.fig,'Position');
   F.space_l = temp(3) - 300; 
   F.space_wd = 400; 
   F.space_ht = 900;
   H.MaskedSpacefig = figure('Units','pixels',...
      'Position',[F.space_l 100 F.space_wd F.space_ht],...
      'Name','Virtual Auditory  MaskedSpace Measurement',...
      'NumberTitle','off');
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'Stimuli played for all picked locs through DLL.');

%reminder
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'Space Filters in DSPs: use *.eq HRIRs');

%Specify HRTF and Location files
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Specify Files');

%Fully-cued HRTF file
F.tot_ht = F.tot_ht + F.ind_ht;
H.spacefilepb = uicontrol('Parent',H.MaskedSpacefig,...
    'Style','pushbutton',...
    'Units','pixels',...
    'Position',[2 F.space_ht-F.tot_ht 195 F.ind_ht],...
    'BackgroundColor','red',...
    'ForegroundColor','white',...
    'FontWeight','bold',...
    'String', 'Select Fully-cued Filter File',...
    'Callback','setInfo_MaskedSpace');

H.spaceflag = uicontrol('Parent',H.MaskedSpacefig,...
    'Style','togglebutton',...
    'Position',[240 F.space_ht-F.tot_ht 120 F.ind_ht],...
    'Value',(XStimParams.space_flag),...
    'String','Push for ABLequal',...
    'BackgroundColor','yellow',...
    'ForegroundColor','blue',...
    'Callback','setInfo_MaskedSpace');

F.tot_ht = F.tot_ht + F.ind_ht;
H.spacefilehdr = uicontrol('Parent',H.MaskedSpacefig,...
   'Style','text',...
   'Position',[0 F.space_ht-F.tot_ht 120 F.ind_ht],...
   'String', 'Fully-cued HRTF File:');
H.spacefile = uicontrol('Parent',H.MaskedSpacefig,...
   'Style','text',...
   'Position',[120 F.space_ht-F.tot_ht F.space_wd-120 F.ind_ht],...
   'HorizontalAlignment','left',...
   'ForegroundColor','blue',...
   'String', FN.space_eq);


F.tot_ht = F.tot_ht + F.ind_ht*2;
%Set Stimulus Parameters
uicontrol('Style','text',...
    'Units','pixels',...
    'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
    'BackgroundColor','blue',...
    'ForegroundColor','white',...
    'FontWeight','bold',...
    'String', 'Set Stimulus Parameters');
F.tot_ht = F.tot_ht + F.ind_ht;    

% HiDynamic Range??
H.MaskedSpace_DynamicRangepb = uicontrol('Style','togglebutton',...
    'Units','pixels',...
    'Position',[180 F.space_ht-F.tot_ht F.space_wd-180 F.ind_ht],...
    'BackgroundColor','yellow',...
    'ForegroundColor','blue',...
    'String', 'push for High Dynamic Range',...
    'Callback','SetInfo_MaskedSpace');

H.MaskedSpace_DynamicRangeTxt = uicontrol('Style','text',...
    'Units','pixels',...
    'Position',[0 F.space_ht-F.tot_ht 180 F.ind_ht],...
    'BackgroundColor',[.8 .8 .8],...
    'String', 'SPL now 20dB below normal');
F.tot_ht = F.tot_ht + F.ind_ht;

F.tot_ht = F.tot_ht + F.ind_ht;
F.tot_ht = F.tot_ht + F.ind_ht;
F.tot_ht = F.tot_ht + F.ind_ht;

%ABL (atten)
F.tot_ht = F.tot_ht + 2*F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Atten (dB):');
H.MaskedSpace_ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','SetInfo_MaskedSpace');

%DUR
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Mask Dur (ms):');
H.MaskedSpace_maskDUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_stimdur2),...
   'Callback','SetInfo_MaskedSpace');
% mask add dB
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Mask add dB :');
H.MaskedSpace_mask_add_dB = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[282 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.mask_add_dB),...
   'Callback','SetInfo_MaskedSpace');


F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Probe Dur (ms):');
H.MaskedSpace_probeDUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_stimdur),...
   'Callback','SetInfo_MaskedSpace');
% probe add dB
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[200 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Probe add dB :');
H.MaskedSpace_probe_add_dB = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[282 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.probe_add_dB),...
   'Callback','SetInfo_MaskedSpace');

%ISI
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ISI (ms)');
H.MaskedSpace_ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.test_ISI),...
   'Callback','setinfo_MaskedSpace');

%NumReps
F.tot_ht = F.tot_ht + F.ind_ht;
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'String', '# Reps:');
H.MaskedSpace_numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setinfo_MaskedSpace');

F.tot_ht = F.tot_ht + F.ind_ht;


F.tot_ht = F.tot_ht + F.ind_ht;
    
%%%%%%%%%%%
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

F.tot_ht = F.tot_ht + F.ind_ht;

% increment test number
H.MaskedSpace_inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[250 F.space_ht-F.tot_ht 140 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_MaskedSpace');


%Engage TEST
H.engageMaskedSpace = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_MaskedSpace');

%Record Data?
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[85 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Record Data?');
H.MaskedSpace_recorddata = uicontrol('Style','checkbox',...
   'Units','pixels',...
   'Position',[185 F.space_ht-F.tot_ht 20 F.ind_ht],...
   'Callback','setInfo_MaskedSpace');
F.tot_ht = F.tot_ht + F.ind_ht;
H.MaskedSpace_FN = uicontrol('Style','text',...
   'Units','pixels',...
   'ForegroundColor','blue',...
   'Position',[85 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', FN.data);

%Reset
F.tot_ht = F.tot_ht + F.ind_ht;
H.resetMaskedSpace = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback','Reset_MaskedSpace');

%Pause TEST
F.ind_ht = 20; 
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.pauseMaskedSpace = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 80 F.ind_ht*2],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.exitMaskedSpace = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.space_wd-100 F.space_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_MaskedSpace');

%Status bar
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.MaskedSpace_status = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht F.space_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Status: setting parameters');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.space_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Remaining Reps:');
H.MaskedSpace_remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', get(H.MaskedSpace_numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 F.space_ht-F.tot_ht 60 F.ind_ht],...
   'String', 'Trials:');
H.MaskedSpace_remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[206 F.space_ht-F.tot_ht 40 F.ind_ht],...
   'String', '');

end %end GUI specification

setInfo_Maskedspace;