%Composite: the GUI for Composite tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************
global F

XStimParams.reset_flag = 0;
GUI.locations1 = [];
GUI.locations2 = [];
Test_num =0;                    % #tests for this session
XStimParams.reset_flag = 0;     % set on exit from called GUIs

F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
      ~exist1('H.ablfig') &...
      ~exist1('H.itdfig') &...
      ~exist1('H.ildfig') &...
      ~exist1('H.ildfreqfig') &...
      ~exist1('H.composite_fig'))
   temp = get(H.fig,'Position');
   F.composite_l = temp(3) - 300; 
   F.composite_wd = 400; 
   F.composite_ht = 700;
   H.composite_fig = figure('Units','pixels',...
      'Position',[F.composite_l 100 F.composite_wd F.composite_ht],...
      'Name','HRTF-based Composite Measurement',...
      'NumberTitle','off');
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht F.composite_wd F.ind_ht],...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'Virtual Auditory Composite Measurement');

%reminder
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht F.composite_wd F.ind_ht],...
   'ForegroundColor',[0 1 1],...
   'FontSize',12,...
   'FontWeight','bold',...
   'String', 'Plays L/R files from temp_stim_path');


F.tot_ht = F.tot_ht + F.ind_ht*2;
H.composite_ClearStimspb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[290 F.composite_ht-F.tot_ht 100 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'Clear Stimuli',...
   'Callback','SetInfo_Composite');

%ABL (atten)
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Atten (dB):');
H.composite_ABL = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.composite_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_ABL),...
   'Callback','SetInfo_Composite');

%DUR
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'Stim Dur (ms):');
H.composite_DUR = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.composite_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.curr_stimdur),...
   'Callback','SetInfo_Composite');

%ISI
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'ISI (ms):');
H.composite_ISI = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.composite_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.test_ISI));

%NumReps
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'String', '# Reps:');
H.composite_numreps = uicontrol('Style','edit',...
   'Units','pixels',...
   'Position',[82 F.composite_ht-F.tot_ht 60 F.ind_ht],...
   'String', num2str(XStimParams.numreps),...
   'Callback','setinfo_Composite');

%%%%%%%%%%% Choose test(s)
F.tot_ht = F.tot_ht + F.ind_ht*2;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht F.composite_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Choose Tests');
F.tot_ht = F.tot_ht + F.ind_ht;
H.composite_test_type = uicontrol('Style','popup',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 175 F.ind_ht],...
   'BackgroundColor','white',...
   'String', 'None|ABL|ITD|ILD|Space|Space2|AltIR|',...
   'Callback','setinfo_Composite');

%%%%%%%%%% list chosen tests
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'test');
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[120 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'String', 'data filename');
F.str_loc = F.tot_ht;         % height to start writing filenames ...
F.str_locStart = F.str_loc;

F.tot_ht = F.tot_ht + F.ind_ht*10;
% initialize filenames for Stimuli
H.composite_initFNpb = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'initFN',...
   'Callback','SetInfo_Composite');

H.composite_num_stims_txt = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[100 F.composite_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'no stimuli chosen');


%%%%%%%%%%% RUN TEST
F.tot_ht = F.tot_ht + 2*F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht F.composite_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Run Test');

F.tot_ht = F.tot_ht + F.ind_ht;

% increment test number
H.composite_inc_testnum = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[250 F.composite_ht-F.tot_ht 140 F.ind_ht],...
   'BackgroundColor','yellow',...
   'ForegroundColor','blue',...
   'FontWeight','bold',...
   'String', 'INCREMENT testnum',...
   'Callback','setInfo_Composite');


%Engage TEST
H.composite_engage = uicontrol('Style','pushbutton',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','green',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'ENGAGE',...
   'Callback','Engage_Composite(FNlist, Test_array)');

%Reset
F.tot_ht = F.tot_ht + F.ind_ht;
H.composite_reset = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.composite_wd-100 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','cyan',...
   'ForegroundColor','black',...
   'FontWeight','bold',...
   'String', 'Reset',...
   'Callback','Reset_Composite');

%Pause TEST
F.ind_ht = 20; 
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.composite_pause = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 80 F.ind_ht*2],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Pause');

%Exit
H.composite_exit = uicontrol('Style','togglebutton',...
   'Units','pixels',...
   'Position',[F.composite_wd-100 F.composite_ht-F.tot_ht 80 F.ind_ht],...
   'BackgroundColor','red',...
   'ForegroundColor','yellow',...
   'FontWeight','bold',...
   'String', 'EXIT',...
   'Callback','Exit_Composite');

%Status bar
F.tot_ht = F.tot_ht + F.ind_ht *2;
H.composite_status = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht F.composite_wd F.ind_ht],...
   'BackgroundColor','blue',...
   'ForegroundColor','white',...
   'FontWeight','bold',...
   'String', 'Status: setting parameters');

%Remaining Reps and Trials
F.tot_ht = F.tot_ht + F.ind_ht;
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[0 F.composite_ht-F.tot_ht 100 F.ind_ht],...
   'String', 'Remaining Reps:');
H.composite_remreps = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[102 F.composite_ht-F.tot_ht 40 F.ind_ht],...
   'String', get(H.composite_numreps,'String'));
uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[144 F.composite_ht-F.tot_ht 60 F.ind_ht],...
   'String', 'Trials:');
H.composite_remtrials = uicontrol('Style','text',...
   'Units','pixels',...
   'Position',[206 F.composite_ht-F.tot_ht 40 F.ind_ht],...
   'String', '');

end %end GUI specification

eval(['save ' FN.current_path 'H_composite H;']);

if 0
% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
   disp('Cannot initialize a primary process')
   return;
end

if(S232('APlock', 100, 0) == 0)
  disp('Cannot acquire lock on AP2 Card')
  s232('S2close');
  return;
end

if(S232('XBlock', 100, 0) == 0)
  disp('Cannot acquire lock on X Bus')
  s232('APunlock', 0);
  s232('S2close');
  return;
end
end

SetInfo_Composite;