function DATA = uitable1(col_headings, nRows)
global DATA H

%% Simple data entry table (GUI)
nCols = length(col_headings);
DATA=NaN*ones(nRows,nCols);
SCRN = get(0,'ScreenSize');
ht=SCRN(4)-SCRN(2); wd=SCRN(3)-SCRN(1);
indx=1/(nRows+2);
H.DataTable_fig = figure('Units','pixels',...
      'Position',[SCRN(1)+0.05*wd SCRN(2)+0.05*ht 0.5*wd 0.8*ht],...
      'Name','Data Table',...
      'NumberTitle','off',...
      'MenuBar','none');
  
%% Column Headings
for i=1:nCols
    H.DataTable_ColHeading(i) = uicontrol('Parent',H.DataTable_fig,...
        'Style','text',...
        'BackgroundColor','black',...
        'ForegroundColor','yellow',...
        'Units','normalized',...
        'Position',[(i-1)/nCols 1-indx 1/nCols indx],...
        'String', col_headings{i});
end

%% Data Entry Rows
for j=1:nRows
    for k=1:nCols
        H.DataTable_Matrix(j,k) = uicontrol('Parent',H.DataTable_fig,...
            'Style','edit',...
            'BackgroundColor','white',...
            'ForegroundColor','black',...
            'Units','normalized',...
            'Position',[(k-1)/nCols 1-(j+1)*indx 1/nCols indx],...
            'String','',...
            'Callback',@matrix_fill_callback);
    end
end

%% DONE PUSHBUTTON
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0 0 1 indx],...
    'BackgroundColor','green',...
    'ForegroundColor','white',...
    'FontWeight','bold',...
    'String', 'DONE',...
    'Callback','close(gcf)');

uiwait(H.DataTable_fig);

function matrix_fill_callback(hObject,eventdata)
global DATA H
[row col] = find(H.DataTable_Matrix == hObject);
tmp=get(hObject,'String');
DATA(row,col) = str2num(tmp);
