%space4: the GUI for space4 test

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

XStimParams.reset_flag = 0;
GUI.locations1 = [];
GUI.locations2 = [];
% to start things off:
XStimParams.itdalone_flag = 0;
XStimParams.ildalone_flag = 0;
XStimParams.ABLalone_flag = 0;
XStimParams.space_flag = 1;

F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
        ~exist1('H.ablfig') &...
        ~exist1('H.itdfig') &...
        ~exist1('H.ildfig') &...
        ~exist1('H.ildfreqfig') &...
        ~exist1('H.space4fig'))
    temp = get(H.fig,'Position');
    F.space4_l = temp(3) - 300; 
    F.space4_wd = 400; 
    F.space4_ht = 900;
    H.space4fig = figure('Units','pixels',...
        'Position',[F.space4_l 100 F.space4_wd F.space4_ht],...
        'Name','SPACE4: Nagel&Doupe: virtual auditory  space measurement',...
        'NumberTitle','off');
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht F.space4_wd F.ind_ht],...
        'ForegroundColor',[0 1 1],...
        'FontSize',12,...
        'FontWeight','bold',...
        'String', 'Stimuli written to disk on each rep before playing out.');
    
    %reminder
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht F.space4_wd F.ind_ht],...
        'ForegroundColor',[0 1 1],...
        'FontSize',12,...
        'FontWeight','bold',...
        'String', 'HRIR Filters in DSPs: use *.eq HRIRs');
    
    %Specify HRTF and Location files
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht F.space4_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Specify Files');
    
    %Fully-cued HRTF file
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.space4filepb = uicontrol('Parent',H.space4fig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.space4_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Select Fully-cued Filter File',...
        'Callback','setInfo_space4');
    uicontrol('Parent',H.space4fig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.space4_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Fully-cued Test');
    H.space4flag = uicontrol('Parent',H.space4fig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.space4_ht-F.tot_ht 30 F.ind_ht],...
        'Value',XStimParams.space_flag,...
        'Callback','setInfo_space4');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.space4filehdr = uicontrol('Parent',H.space4fig,...
        'Style','text',...
        'Position',[0 F.space4_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Fully-cued HRTF File:');
    H.space4file = uicontrol('Parent',H.space4fig,...
        'Style','text',...
        'Position',[120 F.space4_ht-F.tot_ht F.space4_wd-120 F.ind_ht],...
        'HorizontalAlignment','left',...
        'ForegroundColor','blue',...
        'String', FN.space_std);
    
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    %Set Stimulus Parameters
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht F.space4_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Set Stimulus Parameters');
    F.tot_ht = F.tot_ht + F.ind_ht;    
    
    
    uicontrol('Parent',H.space4fig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[2 F.space4_ht-F.tot_ht 110 F.ind_ht],...
        'BackgroundColor',[.8 .8 .8],...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Choose Stim Type');
    H.space4_stim_type = uicontrol('Parent',H.space4fig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[112 F.space4_ht-F.tot_ht 110 F.ind_ht],...
        'BackgroundColor','white',...
        'String',...
        'Tone|Gammatone||||NarrowBand Noise||BroadBand Noise|File|BBN - LNN||',...
        'Value',get(H.stim_type,'Value'),...
        'Callback','setinfo_space4');
    
    H.space4_stimFNpb = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[222 F.space4_ht-F.tot_ht 20 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'FN',...
        'Callback','setinfo_space4');
    H.space4_stimFN = uicontrol('Parent',H.space4fig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[242 F.space4_ht - F.tot_ht F.space4_wd-242 F.ind_ht],...
        'ForegroundColor','blue',...
        'String', FN.stim);
    

    F.tot_ht = F.tot_ht + F.ind_ht;
    H.space4_LimitXCpb = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[22 F.space4_ht-F.tot_ht 180 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','blue',...
        'String', 'push for XClimit test',...
        'Callback','setinfo_space4');
    
    H.space4_DynamicRangepb = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[222 F.space4_ht-F.tot_ht F.space4_wd-222 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','blue',...
        'String', 'push for High Dynamic Range',...
        'Callback','setinfo_space4');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.space4_LimitXCTxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[22 F.space4_ht-F.tot_ht 180 F.ind_ht],...
        'BackgroundColor',[.8 .8 .8],...
         'ForegroundColor',[.6 0 .6],...
       'String', 'XC b/wn freqs NOT limited');

    
    H.space4_DynamicRangeTxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[222 F.space4_ht-F.tot_ht F.space4_wd-222 F.ind_ht],...
        'BackgroundColor',[.8 .8 .8],...
         'ForegroundColor','blue',...
       'String', 'SPL now 20dB below normal');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    % current freq
    H.space4_curr_freqtxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 155 F.ind_ht],...
        'String', 'current frequency:');
    H.space4_curr_freq = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[155 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','white',...
        'String', num2str(XStimParams.curr_freq),...
        'Callback','setinfo_space4');

   H.space4_FNseriestxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[10 F.space4_ht-F.tot_ht 155 F.ind_ht],...
        'FontSize',12,...
        'BackgroundColor',[.8 .8 .8],...
         'ForegroundColor','blue',...
       'String', 'FN should be 1st in series of ten.');
    
    
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    %ABL (atten)
    F.tot_ht = F.tot_ht + 2*F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Atten (dB):');
    H.space4_ABL = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.space4_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.curr_ABL),...
        'Callback','SetInfo_space4');
    % hold ITD?
    H.space4_ITDtxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[165 F.space4_ht-F.tot_ht 115 F.ind_ht],...
        'String', 'Hold ITD constant',...
        'BackgroundColor',[.8 .8 .8]);
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[300 F.space4_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'ITD (us):');
    H.space4_ITD = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[360 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'BackgroundColor','white',...
        'String', num2str(XStimParams.curr_ITD),...
        'Callback','SetInfo_space4');
    
    %DUR
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Stim Dur (ms):');
    H.space4_DUR = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.space4_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.curr_stimdur),...
        'Callback','SetInfo_space4');
    
    %Hold ILD?
    H.space4_ILDtxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[165 F.space4_ht-F.tot_ht 115 F.ind_ht],...
        'String', 'Hold ILD constant',...
        'BackgroundColor',[.8 .8 .8]);
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[300 F.space4_ht-F.tot_ht 20 F.ind_ht],...
        'String', 'El');
    H.space4_el = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[320 F.space4_ht-F.tot_ht 30 F.ind_ht],...
        'BackgroundColor','white',...
        'String', num2str(XStimParams.el),...
        'Callback','SetInfo_space4');
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[350 F.space4_ht-F.tot_ht 20 F.ind_ht],...
        'String', 'Az');
    H.space4_az = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[370 F.space4_ht-F.tot_ht 30 F.ind_ht],...
        'BackgroundColor','white',...
        'String', num2str(XStimParams.az),...
        'Callback','SetInfo_space4');
    
    %ISI
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'ISI (ms):');
    H.space4_ISI = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.space4_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.test_ISI));
    %NumReps
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'String', '# Reps:');
    H.space4_numreps = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.space4_ht-F.tot_ht 60 F.ind_ht],...
        'String', num2str(XStimParams.numreps),...
        'Callback','setinfo_space4');
    
    % modulate  sound
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'Sq wave'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'File'
            mod_num = 4;
        case 'None'
            mod_num = 5;
        otherwise
            mod_num = 5;
    end
    uicontrol(        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.space4_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   Modulation:');
    H.space4testmod_type = uicontrol(        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.space4_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String',...
        'Tone|Sq wave|LP Noise|File|None',...
        'Value',mod_num,...
        'Callback','setInfo_space4');
    H.space4testmod_txt = uicontrol('Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', 'Freq:');
    H.space4testmod_freq = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[220 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'Callback','setInfo_space4');
    
    H.space4testmod_txtA = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[260 F.space4_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'depth');
    H.space4testmod_depth = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[290 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'Callback','setInfo_space4');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    H.space4testmod_txtB = uicontrol(        'Style','text',...
        'Units','pixels',...
        'Position',[260 F.space4_ht-F.tot_ht 30 F.ind_ht],...
        'String', 'phase');
    H.space4testmod_phase = uicontrol(        'Style','edit',...
        'Units','pixels',...
        'Position',[290 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'Callback','setInfo_space4');
    
    H.space4testmod_pb = uicontrol(        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.space4_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setInfo_space4');
    
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    % params for Nagel and Doupe-like stimuli
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   mu list:');
    H.space4_mu = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[80 F.space4_ht-F.tot_ht 140 F.ind_ht],...
        'String', num2str(XStimParams.mu),...
        'Callback','SetInfo_space4');
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[220 F.space4_ht - F.tot_ht 110 F.ind_ht],...
        'String', 'epoch duration (msec)');
    H.space4_epoch_duration = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[330 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.epoch_duration(1)),...
        'Callback','SetInfo_space4');
    
    
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht - F.tot_ht 80 F.ind_ht],...
        'String', '   sigma list:');
    H.space4_sigma = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[80 F.space4_ht-F.tot_ht 140 F.ind_ht],...
        'String', num2str(XStimParams.sigma),...
        'Callback','SetInfo_space4');
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[220 F.space4_ht - F.tot_ht 110 F.ind_ht],...
        'String', 'env repeat Prob');
    H.space4_focalProb = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[330 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.focalProb),...
        'Callback','SetInfo_space4');
    
    %%%%%%%%%%%
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht F.space4_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Run Test');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    % increment test number
    H.space4_inc_testnum = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[250 F.space4_ht-F.tot_ht 140 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', 'INCREMENT testnum',...
        'Callback','setInfo_space4');
    
    
    %Engage TEST
    H.engagespace4 = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','green',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'ENGAGE',...
        'Callback','Engage_space4');
    
    %Record Data?
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.space4_ht-F.tot_ht 100 F.ind_ht],...
        'String', 'Record Data?');
    H.space4_recorddata = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[185 F.space4_ht-F.tot_ht 20 F.ind_ht],...
        'Callback','setInfo_space4');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.space4data_FN = uicontrol('Style','text',...
        'Units','pixels',...
        'ForegroundColor','blue',...
        'Position',[85 F.space4_ht-F.tot_ht 100 F.ind_ht],...
        'String', FN.data);
    
    %Reset
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.resetspace4 = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[F.space4_wd-100 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','cyan',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Reset',...
        'Callback','Reset_space4');
    
    %Pause TEST
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht *2;
    H.pausespace4 = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 80 F.ind_ht*2],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Pause');
    
    %Exit
    H.exitspace4 = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[F.space4_wd-100 F.space4_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','yellow',...
        'FontWeight','bold',...
        'String', 'EXIT',...
        'Callback','Exit_space4');
    
    %Status bar
    F.tot_ht = F.tot_ht + F.ind_ht *2;
    H.space4_status = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht F.space4_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Status: setting parameters');
    
    %Remaining Reps and Trials
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 100 F.ind_ht],...
        'String', 'Remaining Reps:');
    H.space4_remreps = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[102 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', get(H.space4_numreps,'String'));
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[144 F.space4_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'Trials:');
    H.space4_remtrials = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[206 F.space4_ht-F.tot_ht 40 F.ind_ht],...
        'String', '');
    
    %Plotting
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht *2;
    H.space4_plotpsd = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[0 F.space4_ht-F.tot_ht 175 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Plot PSD');
    
    H.space4_plotwts = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[200 F.space4_ht-F.tot_ht 175 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Plot weights after ILA');
    
end %end GUI specification

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
    disp('Cannot initialize a primary process')
    return;
end

if(S232('APlock', 100, 0) == 0)
    disp('Cannot acquire lock on AP2 Card')
    s232('S2close');
    return;
end

if(S232('XBlock', 100, 0) == 0)
    disp('Cannot acquire lock on X Bus')
    s232('APunlock', 0);
    s232('S2close');
    return;
end

SetInfo_space4;