%
% Signal processing
% 
% bpdesign ?
% CLEANHRIR cleans the measured impulse response   
% ENERGY    Energy of vector x.
% ENERGY2   calculate energy of array, integrate power in window
% FADE      Fading function. Syntax h = FADE(h, b1, e1, b2, e2);
% fresample ?
% GENPINK   generation of pink noise stimuli convolved with HRIR 
% GENPULSE  generation of pulse stimuli convolved with HRIR 
% GENSTIM   generation of white noise stimuli convolved with HRIR 
% H_MAX_EN  A rectangular window of length N is shifted over
% lp_filt ?
% luxusfft ?
% MAKESIG  calculates signals for psychoacoustic test 
% MAX_ENV  calculates the maximum value and its position of the envelop
% MINPHASE calculates the minimum phase impulse response or transfer function
% remdemo
% RFFT     calculates the spectrum of a real valued time series
% RIFFT    inverse fft of symmetric spectrum 
% SHIFT    cyclic shift of vector x for n taps
% WINENERG Normalized signal energy inside a rectangular window

% Klaus Hartung
% 17.10.96
