%multisource: the GUI for multisource tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

GUI.locations1 = [];
GUI.locations2 = [];
XStimParams.reset_flag = 0;

F.pos_incr = 20;
F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
        ~exist1('H.ablfig') &...
        ~exist1('H.itdfig') &...
        ~exist1('H.ildfig') &...
        ~exist1('H.ildfreqfig') &...
        ~exist1('H.multi_sourcefig'))
    temp = get(H.fig,'Position');
    F.Two_source_l = temp(3) - 300; 
    F.Two_source_wd = 430; 
    F.Two_source_ht = 900;
    H.multi_sourcefig = figure('Units','pixels',...
        'Position',[F.Two_source_l 100 F.Two_source_wd F.Two_source_ht],...
        'Name','Multisource Measurement',...
        'NumberTitle','off');
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', 'Multisource');
    %reminder
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'String', 'Earphone Inverse Filters loaded separately to DSPs');
    
    F.tot_ht = F.tot_ht + F.ind_ht*2;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht*2],...
        'FontSize',12,...
        'ForegroundColor','cyan',...
        'String', '*.STD HRTFs recommended');

    
    %Specify HRTF and Location files
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Specify Files');
    
    %Fully-cued HRTF file
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.spacefilepb = uicontrol('Parent',H.multi_sourcefig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Two_source_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Select Fully-cued Filter File',...
        'Callback','setInfo_multisource');
    uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Fully-cued Test');
    H.spaceflag = uicontrol('Parent',H.multi_sourcefig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'Value',(XStimParams.space_flag),...
        'Callback','setInfo_multisource');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.spacefilehdr = uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Position',[0 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Fully-cued HRTF File:');
    H.spacefile = uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Position',[120 F.Two_source_ht-F.tot_ht F.Two_source_wd-120 F.ind_ht],...
        'HorizontalAlignment','left',...
        'ForegroundColor','blue',...
        'String', FN.space);
    uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'ABL-alone Test');
    H.ABLaloneflag = uicontrol('Parent',H.multi_sourcefig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'Value',(XStimParams.ABLalone_flag),...
        'Callback','setInfo_multisource');
    
    %ILDAlone filter file
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.ildalonepb = uicontrol('Parent',H.multi_sourcefig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Two_source_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Select ILDAlone Filter File',...
        'Callback','setinfo_multisource');
    
    uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'ILDAlone Test');
    H.ildaloneflag = uicontrol('Parent',H.multi_sourcefig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'Value',(XStimParams.ildalone_flag),...
        'Callback','setInfo_multisource');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.ildalonefilehdr = uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Position',[0 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'ILDAlone File:');
    H.ildalonefile = uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Position',[120 F.Two_source_ht-F.tot_ht F.Two_source_wd-120 F.ind_ht],...
        'HorizontalAlignment','left',...
        'ForegroundColor','blue',...
        'String', FN.ildalone);
    
    %ITDAlone filter file
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.itdalonepb = uicontrol('Parent',H.multi_sourcefig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Two_source_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Select ITDAlone Filter File',...
        'Callback','setinfo_multisource');
    
    uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'ITDAlone Test');
    H.itdaloneflag = uicontrol('Parent',H.multi_sourcefig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'Value',XStimParams.itdalone_flag,...
        'Callback','setInfo_multisource');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.itdalonefilehdr = uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Position',[0 F.Two_source_ht-F.tot_ht 100 F.ind_ht],...
        'String', 'ITDAlone File:');
    H.itdalonefile = uicontrol('Parent',H.multi_sourcefig,...
        'Style','text',...
        'Position',[100 F.Two_source_ht-F.tot_ht fig_wd-100 F.ind_ht],...
        'HorizontalAlignment','left',...
        'ForegroundColor','blue',...
        'String', FN.itdalone);
       
    F.tot_ht = F.tot_ht + F.ind_ht + F.ind_ht;
    
	%Other Stimulus Parameters
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Set Stimulus Parameters');
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     
%         uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'FontWeight','bold',...
%         'Position',[0 F.Two_source_ht - F.tot_ht 60 F.ind_ht],...
%         'String', 'stimulus');
	
% 	
% 	%First Stimulus types: popupmenu
%     H.Twosrc_stim_type = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','popup',...
%         'Units','pixels',...
%         'Position',[60 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
%         'BackgroundColor','white',...
%         'String',...
%         'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|None',...
%         'Value', get(H.stim_type,'Value'),...
%         'Callback','setinfo_Two_source');
%     
%     % only one will be displayed, either
%     H.Twosrc_stim_filenamepb = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','pushbutton',...
%         'Units','pixels',...
%         'Position',[180 F.Two_source_ht-F.tot_ht 25 F.ind_ht],...
% 		'Visible','off',...    
% 		'BackgroundColor','red',...
%         'ForegroundColor','white',...
%         'String', 'file',...
%         'Callback','setinfo_Two_source');
%     H.Twosrc_stim_filename = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[205 F.Two_source_ht-F.tot_ht 105 F.ind_ht],...
% 		'Visible','off',...  
% 		'ForegroundColor','blue',...
%         'String', FN.stim);
    % or
%     H.Twosrc_freq_txt = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[180 F.Two_source_ht-F.tot_ht 90 F.ind_ht],...
% 		'Visible','off',...   
% 		'String', '                     freq');
%     H.Twosrc_freq = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','edit',...
%         'Units','pixels',...
%         'Position',[270 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
% 		'Visible','off',...    
% 		'String', num2str(XStimParams.freq(1)),...
%         'Callback','setinfo_Two_source');
% 	H.stim_nostim_text = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[180 F.Two_source_ht-F.tot_ht 90 F.ind_ht],...
% 		'Visible','off',...   
% 		'String', 'no stim');
		
		
%     uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[340 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
%         'String', 'factor');
%     H.Twosrc_factor = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','edit',...
%         'Units','pixels',...
%         'Position',[370 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
%         'String', num2str(XStimParams.factor(1)),...
%         'Callback','setinfo_Two_source');
    
    % modulate 1st sound
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     switch XStimParams.mod_type
%         case 'Tone'
%             mod_num = 1;
%         case 'File'
%             mod_num = 2;
%         case 'LP Noise'
%             mod_num = 3;
%         case 'None'
%             mod_num = 4;
%         otherwise
%             mod_num = 1;
%     end
%     uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'FontWeight','bold',...
%         'Position',[0 F.Two_source_ht - F.tot_ht 40 F.ind_ht],...
%         'String', 'mod');
%     H.Twosrc_mod_type = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','popup',...
%         'Units','pixels',...
%         'Position',[40 F.Two_source_ht-F.tot_ht 100 F.ind_ht],...
%         'BackgroundColor','White',...
%         'String',...
%         'Tone|LP Noise|File|None',...
%         'Value',mod_num,...
%         'Callback','setinfo_Two_source');
%     H.Twosrc_mod_txt = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'HorizontalAlignment','right',...
%         'Position',[140 F.Two_source_ht-F.tot_ht 60 F.ind_ht],...
%         'String', 'mod freq ');
%     H.Twosrc_mod_freq = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','edit',...
%         'Units','pixels',...
%         'Position',[200 F.Two_source_ht-F.tot_ht 50 F.ind_ht],...
%         'String', num2str(XStimParams.mod_freq(1)),...
%         'Callback','setinfo_Two_source');
%      H.Twosrc_mod_txtA = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[270 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
%         'String', 'depth');
%     H.Twosrc_mod_depth = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','edit',...
%         'Units','pixels',...
%         'Position',[300 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.mod_depth(1)),...
%         'Callback','setinfo_Two_source');
%     H.Twosrc_mod_txtB = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[360 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
%         'String', 'phase');
%     H.Twosrc_mod_phase = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','edit',...
%         'Units','pixels',...
%         'Position',[400 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
%         'String', num2str(XStimParams.mod_phase(1)),...
%         'Callback','setinfo_Two_source');
%     
%     H.Twosrc_mod_pb = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','pushbutton',...
%         'Units','pixels',...
%         'Position',[140 F.Two_source_ht-F.tot_ht 25 F.ind_ht],...
%         'BackgroundColor','red',...
%         'ForegroundColor','white',...
%         'String', 'file',...
%         'Visible','off',...
%         'Callback','setinfo_Two_source');
%      H.Twosrc_mod_txtC = uicontrol('Parent',H.multi_sourcefig,...
%         'Style','text',...
%         'Units','pixels',...
% 		'ForegroundColor','blue',...
%         'Position',[170 F.Two_source_ht-F.tot_ht 100 F.ind_ht],...
%         'Visible','off',...
% 		'String', '');
% 		
		
    % button to bring up stimulus shape window
	F.tot_ht = F.tot_ht + F.ind_ht;
	F.tot_ht = F.tot_ht + F.ind_ht;
	
	H.source_sub1_gui_pb = uicontrol('Parent',H.multi_sourcefig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Two_source_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Set/View Stimulus Shape',...
        'Callback','setInfo_multisource');

	% button to bring up stimulus location window
	F.tot_ht = F.tot_ht + F.ind_ht;
	F.tot_ht = F.tot_ht + F.ind_ht;
 
	H.source_sub2_gui_pb = uicontrol('Parent',H.multi_sourcefig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Two_source_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Set/View Stimulus Locations',...
        'Callback','setInfo_multisource');

	% button to bring up stimulus parameter window
	F.tot_ht = F.tot_ht + F.ind_ht;
	F.tot_ht = F.tot_ht + F.ind_ht;
 
	H.source_sub3_gui_pb = uicontrol('Parent',H.multi_sourcefig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Two_source_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Set/View Stimulus Params',...
        'Callback','setInfo_multisource');
	
% 		
% 		
% 		% bandwidths
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     uicontrol('Style','text',...
%         'Units','pixels',...
%         'Position',[0 F.Two_source_ht-F.tot_ht 110 F.ind_ht],...
%         'String', 'Bandwidth(oct)   src1:');
%     H.bandwidth1 = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[112 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.bandwidth(1)),...
%         'Callback','setinfo_Two_source');
%     
%    
%     
%     % bandlimits
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     uicontrol('Style','text',...
%         'Units','pixels',...
%         'Position',[0 F.Two_source_ht-F.tot_ht 50 F.ind_ht],...
%         'String', 'limits  s1:');
%     H.bandlimits1 = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[52 F.Two_source_ht-F.tot_ht 50 F.ind_ht],...
%         'String', num2str(XStimParams.bandlimits(1)),...
%         'Callback','setinfo_Two_source');
%     H.bandlimits2 = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[102 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.bandlimits(2)),...
%         'Callback','setinfo_Two_source');
%     

    
    % constant ITD ?
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.ITDtxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht 90 F.ind_ht],...
        'BackgroundColor',[.8 .8 .8],...
        'String', 'ITD constant      ');
    
    % ITD
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[97 F.Two_source_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'ITD(us):');
    H.ITD = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[157 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'String', num2str(XStimParams.curr_ITD),...
        'Callback', 'setInfo_multisource');
    
    % constant ILD ?
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.ILDtxt = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht 90 F.ind_ht],...
        'BackgroundColor',[.8 .8 .8],...
        'String', 'ILD constant      ');
    
    % 1st source ILD
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[97 F.Two_source_ht-F.tot_ht 20 F.ind_ht],...
        'String', 'el');
    H.el = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[117 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'String', num2str(XStimParams.el),...
        'Callback', 'setInfo_multisource');
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[147 F.Two_source_ht-F.tot_ht 20 F.ind_ht],...
        'String', 'az');
    H.az = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[167 F.Two_source_ht-F.tot_ht 30 F.ind_ht],...
        'String', num2str(XStimParams.az),...
        'Callback', 'setInfo_multisource');
           
    %ABL
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Atten (dB):');
    H.ABL = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.curr_ABL),...
        'Callback', 'setInfo_multisource');
    
    %ISI
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[140 F.Two_source_ht-F.tot_ht 60 F.ind_ht],...
        'String', 'ISI (ms):');
    H.ISI = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[202 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.test_ISI),...
        'Callback', 'setInfo_multisource');
    
%     %DUR
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     uicontrol('Style','text',...
%         'Units','pixels',...
%         'Position',[0 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
%         'String', 'Stim Dur (ms):');
%     H.DUR = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[82 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.curr_stimdur),...
%         'Callback','setinfo_Two_source');
%     
    %NumReps
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[140 F.Two_source_ht-F.tot_ht 60 F.ind_ht],...
        'String', '# Reps:');
    H.numreps = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[202 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.numreps),...
        'Callback','setInfo_multisource');
    
    % run control
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Run Control');
    
    %Engage TEST
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.engageTwo_source = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','green',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'ENGAGE',...
        'Callback','Engage_multisource');
    
    %Record Data?
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.Two_source_ht-F.tot_ht 100 F.ind_ht],...
        'String', 'Record Data?');
    H.recorddata = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[185 F.Two_source_ht-F.tot_ht 20 F.ind_ht],...
        'Callback', 'setInfo_multisource');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.recorddata_FN = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.Two_source_ht-F.tot_ht 100 F.ind_ht],...
        'String', FN.data);
    
    % increment test number
    H.inc_testnum = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[250 F.Two_source_ht-F.tot_ht 140 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', 'INCREMENT testnum',...
        'Callback','setInfo_multisource');
    
    %Pause TEST
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    H.pauseTwo_source = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Pause');
   
     %plotVstrength
    H.plotVstr = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[100 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','cyan',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Plot Vstr',...
        'Callback', 'setInfo_multisource');

    %Reset
    H.resetTwo_source = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[200 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','cyan',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Reset',...
        'Callback','Reset_multisource');
    
    %Exit
    H.exitTwo_source = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[F.Two_source_wd-100 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','yellow',...
        'FontWeight','bold',...
        'String', 'EXIT',...
        'Callback','Exit_multisource');
    
    %Build/Play Trials
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    H.status = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht F.Two_source_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Status: setting parameters');
    
    %Remaining Reps and Trials
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Two_source_ht-F.tot_ht 120 F.ind_ht],...
        'String', 'Remaining reps:');
    H.remreps = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[122 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
        'String', get(H.numreps,'String'));
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[164 F.Two_source_ht-F.tot_ht 80 F.ind_ht],...
        'String', 'Trials:');
    H.remtrials = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[246 F.Two_source_ht-F.tot_ht 40 F.ind_ht],...
        'String', '');
    
end %end GUI specification

stimuli_dir = FN.temp_stim_path;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
    disp('Cannot initialize a secondary process')
    return;
end

if(S232('APlock', 100, 0) == 0)
    disp('Cannot acquire lock on AP2 Card')
    s232('S2close');
    return;
end

if(S232('XBlock', 100, 0) == 0)
    disp('Cannot acquire lock on X Bus')
    s232('APunlock', 0);
    s232('S2close');
    return;
end

setInfo_multisource;

