CONTENTS.M for directory TOOL  

  ASKYESNO gets a 'yes' (returns 1) or 'no'
	   (returns 0) answer from the user. Only the
	   first character of the input is recognized.
  CHECKFFT Check complex transfer function
  CHKFILE  checks for the existence of the specified file
  CLOSEALL closes up to 30 graphic windows.
  COF2BIN  writes the coefficients of two FIR filters to two binary files.
  COF2SR2  converts a coffile with filter coefficients to a series of 
	   SR2 files. 
  CONVERT  is a batch job to convert all result files from
	   psychoacoustic tests to MATLAB format.
  DERIVE   computes dy/dx
  DINPUT   Keyboard input with default value.
  ENERGY   Energy of a signal stored in a vector.
  ETC      Energy time curve
  FADE     Fading function. 
  FREQGRP  Upper cutoff frequencies fg and center frequencies fm of
	   Zwickers frequency groups.
  FSMOOTH  octave ore third octave smoothing of transferfunction H.
  GETSAMPL return sampling points for for monaural and interaural optimization.
  GRCNTRL  User menu for selecting plot windows.
  GRCNTRL_ Is called from GRCNTRL.
  HZ2BARK  Convert Hz to Bark.
  IRPLOT   Plot one or more real (time) signals.
  ISEVEN   return 1 if the input number is even, 0 else
  ISSTABLE Check polynom for roots outside or on the unit circle.
  LATTICE  calculates lattice filter reflection coefficients
  LINES    Plot discrete sequence data.
  MAGPLOT  Plot magnitude of one or more complex signals.
  MIXRAND  resorts the elements in a vector in a random way .
  MKLSDATA make data arrays for least-square approximation
  MKLSRDAT make data arrays for least-square approximation with
	   autocorrelation data
  MKSAMPLE Return nonuniformly spaced sampling points.
  MKSINSI1 writes a sine signal to the specified file using SI1 format. 
  MMSAMPLE Compute sampling points near the maxima and minima points
	   of log10(abs(H)).
  PHASPLOT Plot phase of one or more complex signals in degrees.
  PLTSTYLE Make correct plot style string
  READDATA Read measured impulse response from catalogue.
  READDEL  returns the delay times and the minimum delay time of the
	   impulse responses in the specified catalogue.
  READDIRS returns the available directions and the number of
	   directions stored in the specified catalogue.
  READHP   Read measured headphone impulse response for given catalogue.
  READLS   Read measured loudspeaker impulse response from catalogue.
  READSR1  reads SI1 files
  READSIG2 reads SIG2 files
  READSR1  reads SR1 files
  READSR2  reads SR2 files
  SAMPLFRQ returns the default sampling frequency.
  SELDIRS  displays the available directions (44!)
	   and enables the user to select special directions.
  SMOOTH   Smooth data vector x using M values on the left and 
	   right of each point.
  SQRPLOT  produces equal sized axis for a graph.
  STABLE   Polynomial stabilization.
  STRETCH  blows up the current graph axis by factor f.
  TGROUP   Group delay for vector H.
  TGRPDEMO shows the influence of noise to the computation
	   of the group delay.
  TGRPPLOT Plot group delay of one or more complex signals.
  USERGRID Draw grid lines
  WINENERG Normalized signal energy inside a rectangular window
  WRITESI1 Write data to file using SI1 format.
  WRITESR2 writes SR2 files 
  WRITETXT writes a text string to a file.
  ZPMAP    plot the poles and zeros of a transfer function 
