function LoadPlotDelayData()
% LoadPlotDelayData
% Loads Delay data from file and plots it...

global DData

[fileStr,pathStr,FilterIndex] = uigetfile('*.*','Select .Wav File');
if(FilterIndex==0), return, end
filepathStr=[pathStr fileStr];

load(filepathStr);

assignin('base','DATA',DATA);
assignin('base','FN',FN);
assignin('base','params',params);
assignin('base','seq',seq);

azimuths=zeros(1,1);
azimuthsTxt='';
elevations=zeros(1,1);
elevationsTxt='';
for locnum = 1:size(params.locations,2)
     azimuths(locnum) = params.locations(2,locnum);
     azimuthsTxt=[azimuthsTxt num2str(azimuths(locnum)) ', '];
     elevations(locnum) = params.locations(1,locnum);
     elevationsTxt=[elevationsTxt num2str(elevations(locnum)) ', '];
end
% disp(azimuths)
% disp(elevations)

DelayTimes=zeros(1,1);
DelayTimesTxt='';
mp=1;
for mt = 1:size(params.DelayTimes,2)
    if(~isnan(params.DelayTimes(mt)))
        DelayTimes(mp)=params.DelayTimes(mt);
        DelayTimesTxt=[DelayTimesTxt num2str(DelayTimes(mp)) ', '];
        mp=mp+1;
    end
end
%disp(DelayTimes);
OnRamps=zeros(1,1);
OnRampsTxt='';
mp=1;
for mt = 1:size(params.ramp_timeS_on,2)
    if(~isnan(params.ramp_timeS_on(mt)))
        OnRamps(mp)=params.ramp_timeS_on(mt);
        OnRampsTxt=[OnRampsTxt num2str(OnRamps(mp)) ', '];
        mp=mp+1;
    end
end
%disp(OnRamps);
OffRamps=zeros(1,1);
OffRampsTxt='';
mp=1;
for mt = 1:size(params.ramp_timeS_off,2)
    if(~isnan(params.ramp_timeS_off(mt)))
        OffRamps(mp)=params.ramp_timeS_off(mt);
        OffRampsTxt=[OffRampsTxt num2str(OffRamps(mp)) ', '];
        mp=mp+1;
    end
end
%disp(OffRamps);
LagExts=zeros(1,1);
LagExtsTxt='';
mp=1;
for mt = 1:size(params.lag_seg_ext,2)
    if(~isnan(params.lag_seg_ext(mt)))
        LagExts(mp)=params.lag_seg_ext(mt);
        LagExtsTxt=[LagExtsTxt num2str(LagExts(mp)) ', '];
        mp=mp+1;
    end
end
%disp(LagExts);
DelayMods=zeros(1,1);
DelayModsTxt='';
mp=1;
for mt = 1:size(params.DelayMods,2)
    if(~isnan(params.DelayMods(mt)))
        DelayMods(mp)=params.DelayMods(mt);
        DelayModsTxt=[DelayModsTxt num2str(DelayMods(mp)) ', '];
        mp=mp+1;
    end
end
%disp(DelayMods);

numreps=params.numreps;

c_az=azimuths(1);
c_el=elevations(1);
c_delay=DelayTimes(1);
c_OnRamp=OnRamps(1);
c_OffRamp=OffRamps(1);
c_LagExt=LagExts(1);
c_DelayMod=DelayMods(1);



if(findobj('Tag','Delay Data'))
    close('Delay Data');
end

Bpos=200; % bottom
Lpos=150; % left
Wpos=350; % width
Hpos=350; % height
tft=0;

DData.fig = figure('Units','pixels',...
  'Position',[Lpos Bpos Wpos Hpos],...
  'Name','Delay Data',...
  'Tag', 'Delay Data',...
  'NumberTitle','off',...
  'MenuBar','none',...
  'Color',[0.95 0.95 0.95],...
  'ToolBar','none');

tft=tft+20;
DData.txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 30 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', ['reps: ' num2str(numreps)]);
DData.reps = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[35 Hpos-tft 50 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', num2str(numreps));

DData.txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[100 Hpos-tft 200 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', ['file: ' fileStr]);

tft=tft+10;
tft=tft+20;
DData.el_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'elevation:');
DData.elev = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','el',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_el),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.el_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'elTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 100 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', elevationsTxt);
tft=tft+15;
DData.eloffset_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'center',...
   'String', ['(' num2str(params.offset_el(2)) ')']);

tft=tft+20;
DData.az_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'azimuth:');
DData.azim = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','DelayTime',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_az),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.az_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'delaysTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 100 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', azimuthsTxt);
tft=tft+15;
DData.azoffset_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'center',...
   'String', ['(' num2str(params.offset_az(2)) ')']);

tft=tft+10;
tft=tft+20;
DData.delay_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'delay (ms):');
DData.delay = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','DelayTime',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_delay),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.delay_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'delaysTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 100 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', DelayTimesTxt);

tft=tft+20;
DData.onset_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'onset (ms):');
DData.onset = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','OnRamp',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_OnRamp),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.onset_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'OnRampsTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 100 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', OnRampsTxt);

tft=tft+20;
DData.offset_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'offset (ms):');
DData.offset = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','OffRamp',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_OffRamp),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.offset_txt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'offsetTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 100 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', OffRampsTxt);

tft=tft+20;
DData.LagExtsTxt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'lag+ (ms):');
DData.LagExt = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','LagExt',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_LagExt),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.LagExtsTxt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'LagExtsTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 100 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', LagExtsTxt);

tft=tft+20;
DData.DelayModsTxt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'Units','pixels',...
   'Position',[5 Hpos-tft 80 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'right',...
   'String', 'mod:');
DData.DelayMod = uicontrol('Parent',DData.fig,...
   'Style','edit',...
   'Tag','DelayMod',...
   'Units','pixels',...
   'Position',[90 Hpos-tft 50 18],...
   'String', num2str(c_DelayMod),...
   'BackgroundColor',[1 1 1],...
   'Callback','PlotDData');
DData.DelayModsTxt = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 9,...
   'Tag', 'DelayModsTxt',...
   'Units','pixels',...
   'Position',[150 Hpos-tft 200 15],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'String', DelayModsTxt);

%disp('1=normal, 2=uncorrelated , 3=no lead segment, 4=no lag segment');
tft=tft+30;
DData.FoundTrial = uicontrol('Parent',DData.fig,...
   'Style','text',...
   'FontSize', 10,...
   'ForegroundColor', [0.75 0.1 0.1],...
   'FontWeight', 'Bold',...
   'Tag', 'DelayModsTxt',...
   'Units','pixels',...
   'Position',[20 Hpos-tft 200 20],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'center',...
   'String', 'not found');
set(DData.FoundTrial, 'Visible', 'off');

tft=40;
lfr=250;

DData.file = uicontrol('Parent',DData.fig,...
   'Style','pushbutton',...
   'Tag', 'DData_file',...
   'Units','pixels',...
   'Position',[lfr-50 Hpos-tft 60 20],...
   'String', 'file',...
   'ForegroundColor', [0 0 0],...
   'Callback','LoadPlotDelayData_CB');
DData.Plot = uicontrol('Parent',DData.fig,...
   'Style','pushbutton',...
   'Tag', 'DData_Plot',...
   'Units','pixels',...
   'Position',[lfr+20 Hpos-tft 60 20],...
   'String', 'plot',...
   'ForegroundColor', [0 0 0],...
   'Callback','LoadPlotDelayData_CB');

tft=tft+30;
DData.raster = uicontrol('Parent',DData.fig,...
   'Style','checkbox',...
   'Tag', 'DData_raster',...
   'Units','pixels',...
   'Position',[lfr Hpos-tft 150 18],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'Value', 1,...
   'String', 'raster');

tft=tft+30;
DData.PSTH = uicontrol('Parent',DData.fig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[lfr Hpos-tft 150 18],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'Value', 1,...
   'String', 'PSTH');

tft=tft+20;
DData.holdPSTH = uicontrol('Parent',DData.fig,...
   'Style','checkbox',...
   'Units','pixels',...
   'Position',[lfr+10 Hpos-tft 150 18],...
   'BackgroundColor',[0.95 0.95 0.95],...
   'HorizontalAlignment', 'left',...
   'Value', 0,...
   'String', 'overlay');

tft=tft+60;
DData.NamePSTH = uicontrol('Parent',DData.fig,...
   'Style','pushbutton',...
   'Tag', 'DData_NamePSTH',...
   'Units','pixels',...
   'Position',[lfr+20 Hpos-tft 60 20],...
   'String', 'name',...
   'ForegroundColor', [0 0 0],...
   'Callback','LoadPlotDelayData_CB');


clear FilterIndex