%Two_source: the GUI for Two_source tests

%*******************************************************************************
%	The Graphical User Interface
%*******************************************************************************

GUI.locations1 = [];
GUI.locations2 = [];
XStimParams.reset_flag = 0;

% defaults
XStimParams.space_flag = 1;
XStimParams.mod_type = 'None';
XStimParams.mod_num = 4;
stim_type_num = 1;  % 1= noise generated, 2 = noise from file 

global H;

F.pos_incr = 20;
F.tot_ht = 0;
F.ind_ht = 20; 
%Figure window
if(~exist1('H.searchfig') &...
        ~exist1('H.ablfig') &...
        ~exist1('H.itdfig') &...
        ~exist1('H.ildfig') &...
        ~exist1('H.ildfreqfig') &...
        ~exist1('H.Two_sourcefig'))
    temp = get(H.fig,'Position');
    F.Delay_l = temp(3) - 300; 
    F.Delay_wd = 400; 
    F.Delay_ht = 900;
    H.Delayfig = figure('Units','pixels',...
        'Position',[F.Delay_l 100 F.Delay_wd F.Delay_ht],...
        'Name','Simple Delay',...
        'color', [0.8 0.8 0.8],...
        'NumberTitle','off');
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht F.Delay_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Delay');
    
%     %reminder
     F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht F.Delay_wd F.ind_ht],...
        'ForegroundColor','blue',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Earphone Inverse Filters loaded separately to DSPs');
    
    %Specify HRTF and Location files
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht F.Delay_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Specify Files');
    
    %Fully-cued HRTF file
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.spacefilepb = uicontrol('Parent',H.Delayfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[2 F.Delay_ht-F.tot_ht 195 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Select Fully-cued Filter File',...
        'Callback','setInfo_Delay');
    
    uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[200 F.Delay_ht-F.tot_ht 120 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Fully-cued Test');
    H.spaceflag = uicontrol('Parent',H.Delayfig,...
        'Style','checkbox',...
        'Units','pixels',...
        'Position',[315 F.Delay_ht-F.tot_ht 30 F.ind_ht],...
        'Value',(XStimParams.space_flag),...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Callback','setInfo_Delay');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.spacefilehdr = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Position',[0 F.Delay_ht-F.tot_ht 120 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Fully-cued HRTF File:');
    H.spacefile = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Position',[120 F.Delay_ht-F.tot_ht F.Delay_wd-120 F.ind_ht],...
        'HorizontalAlignment','left',...
        'ForegroundColor','blue',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', FN.space);

    F.tot_ht = F.tot_ht + F.ind_ht + F.ind_ht;
    %Other Stimulus Parameters
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht F.Delay_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Set Stimulus Parameters');
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    %Stimulus type popupmenu
    uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht - F.tot_ht 60 F.ind_ht],...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Stimulus:');
    H.Delay_stim_type = uicontrol('Parent',H.Delayfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[60 F.Delay_ht-F.tot_ht 120 F.ind_ht],...
        'BackgroundColor','white',...
        'String',...
        'Rand Noise|Noise File',...
        'Value', stim_type_num,...
        'Callback','setinfo_Delay');
    
    %'Tone|Gammatone|Tone Stack|GammaTone Stack|BandPassed Noise|NarrowBand Noise|NarrowBand Noise Stack|BroadBand Noise|File|None',...
    
    % only one will be displayed, either
%     H.Delay_stim_filenamepb = uicontrol('Parent',H.Delayfig,...
%         'Style','pushbutton',...
%         'Units','pixels',...
%         'Position',[180 F.Delay_ht-F.tot_ht 25 F.ind_ht],...
%         'BackgroundColor','red',...
%         'ForegroundColor','blue',...
%         'String', 'FN',...
%         'Callback','setinfo_Delay');
    H.Delay_stim_filename = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[205 F.Delay_ht-F.tot_ht 105 F.ind_ht],...
        'ForegroundColor','blue',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'HorizontalAlignment', 'left',...
        'String', 'PEStim');
        %'String', FN.stim);
    % or
    H.Delay_freq_txt = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 90 F.ind_ht],...
        'Visible','off',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Frequency');
    H.Delay_freq = uicontrol('Parent',H.Delayfig,...
        'Style','edit',...
        'Units','pixels',...
        'Visible','off',...
        'Position',[270 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.freq(1)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    
%     uicontrol('Parent',H.Delayfig,...
%         'Style','text',...
%         'Units','pixels',...
%         'Position',[330 F.Delay_ht-F.tot_ht 30 F.ind_ht],...
%         'BackgroundColor', [0.8 0.8 0.8],...
%         'String', 'factor');
%     H.Delay_factor = uicontrol('Parent',H.Delayfig,...
%         'Style','edit',...
%         'Units','pixels',...
%         'Position',[360 F.Delay_ht-F.tot_ht 30 F.ind_ht],...
%         'String', num2str(XStimParams.factor(1)),...
%         'BackgroundColor', [0.9 0.9 0.9],...
%         'Callback','setinfo_Delay');
    
    % modulate 1st sound
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    switch XStimParams.mod_type
        case 'Tone'
            mod_num = 1;
        case 'File'
            mod_num = 2;
        case 'LP Noise'
            mod_num = 3;
        case 'None'
            mod_num = 4;
        otherwise
            mod_num = 1;
    end
    uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'FontWeight','bold',...
        'Position',[0 F.Delay_ht - F.tot_ht 80 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', '   Modulation:');
    H.Delay_mod_type = uicontrol('Parent',H.Delayfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[80 F.Delay_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor','White',...
        'String', 'Tone|LP Noise|File|None',...
        'Value', mod_num,...
        'Callback','setinfo_Delay');
    H.Delay_mod_txt = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'HorizontalAlignment','right',...
        'Position',[180 F.Delay_ht-F.tot_ht 50 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Mod Freq: ');
    H.Delay_mod_freq = uicontrol('Parent',H.Delayfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[230 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_freq(1)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    
    H.Delay_mod_txtA = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[270 F.Delay_ht-F.tot_ht 30 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'depth');
    H.Delay_mod_depth = uicontrol('Parent',H.Delayfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[300 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.mod_depth(1)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    H.Delay_mod_txtB = uicontrol('Parent',H.Delayfig,...
        'Style','text',...
        'Units','pixels',...
        'Position',[340 F.Delay_ht-F.tot_ht 30 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'phase');
    H.Delay_mod_phase = uicontrol('Parent',H.Delayfig,...
        'Style','edit',...
        'Units','pixels',...
        'Position',[370 F.Delay_ht-F.tot_ht 30 F.ind_ht],...
        'String', num2str(XStimParams.mod_phase(1)),...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Callback','setinfo_Delay');
    
    H.Delay_mod_pb = uicontrol('Parent',H.Delayfig,...
        'Style','pushbutton',...
        'Units','pixels',...
        'Position',[200 F.Delay_ht-F.tot_ht 25 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','blue',...
        'String', 'FN',...
        'Visible','off',...
        'Callback','setinfo_Delay');
    
   F.tot_ht = F.tot_ht + F.ind_ht;
   F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 240 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Location Offsets ');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[5 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Source 2  Elev: ');
    H.offset_el = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[85 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.offset_el(2)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[135 F.Delay_ht-F.tot_ht 45 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Azim: ');
    H.offset_az = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.offset_az(2)),...
        'BackgroundColor', [1 1 1],...
        'Callback','setinfo_Delay');
    
    
        
% uicontrol('Style','text',...
%         'BackgroundColor',[.7 .7 .7],...
%         'Units','pixels',...
%         'Position',[250 F.Delay_ht-F.tot_ht 120 F.ind_ht],...
%         'String', '  loc3 = loc + offset3/2');
%     

    
      

    % bandwidths
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 110 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Bandwidth(oct): ');
    H.bandwidth1 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[112 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.bandwidth(1)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    

    % bandlimits
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[10 F.Delay_ht-F.tot_ht 50 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'limits :');
    H.bandlimits1 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[62 F.Delay_ht-F.tot_ht 50 F.ind_ht],...
        'String', num2str(XStimParams.bandlimits(1)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    H.bandlimits2 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[112 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.bandlimits(2)),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    
    
    % Time Delay
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;

%         % delay time ms
%     uicontrol('Style','text',...
%         'Units','pixels',...
%         'Position',[0 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
%         'HorizontalAlignment', 'right',...
%         'String', 'Delay (ms): ');
%     H.delaytime = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[82 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.Delay_ms),...
%         'Callback', 'setinfo_Delay');
    
        % uncorrel
    H.uncorrel = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[10 F.Delay_ht-F.tot_ht 90 F.ind_ht],...
        'String',  'Uncorrelated',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Value', XStimParams.uncorrel,...
        'Callback', 'setinfo_Delay');
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'HorizontalAlignment', 'center',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Silent: ');
        % SilentDelay
    H.silentdelay = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[155 F.Delay_ht-F.tot_ht 70 F.ind_ht],...
        'String',  'Lead',...
        'Value', XStimParams.SilentDelay,...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Callback', 'setinfo_Delay');
    
         % SilentLag
    H.silentlag = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[215 F.Delay_ht-F.tot_ht 70 F.ind_ht],...
        'String',  'Lag',...
        'Value', XStimParams.SilentLag,...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Callback', 'setinfo_Delay');
    
    
        % randOnsetPerms
    H.randOnsetPerms = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[305 F.Delay_ht-F.tot_ht 70 F.ind_ht],...
        'String',  'Random',...
        'Value', XStimParams.randOnsetPerms,...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Callback', 'setinfo_Delay');
    
    %delays
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + 5;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'HorizontalAlignment', 'center',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'lag delays:');
    H.delay01 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[60 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(1)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay02 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(2)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay03 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(3)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay04 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(4)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay05 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[220 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(5)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay06 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[260 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(6)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay07 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[300 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(7)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay08 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[340 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(8)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'HorizontalAlignment', 'center',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', '(ms)');
    H.delay09 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[60 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(9)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay10 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(10)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay11 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(11)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay12 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(12)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay13 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[220 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(13)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay14 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[260 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(14)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay15 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[300 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(15)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.delay16 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[340 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.DelayTimes(16)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
        
        % Ramp times
%     F.tot_ht = F.tot_ht + F.ind_ht;
%     F.tot_ht = F.tot_ht + F.ind_ht/2;
%     uicontrol('Style','text',...
%         'Units','pixels',...
%         'Position',[0 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
%         'HorizontalAlignment', 'right',...
%         'String', 'Onset (ms): ');
%     H.onramptime = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[82 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.ramp_time_on),...
%         'Callback', 'setinfo_Delay');
%     uicontrol('Style','text',...
%         'Units','pixels',...
%         'Position',[130 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
%         'HorizontalAlignment', 'right',...
%         'String', 'Offset (ms): ');
%     H.offramptime = uicontrol('Style','edit',...
%         'Units','pixels',...
%         'Position',[212 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
%         'String', num2str(XStimParams.ramp_time_off),...
%         'Callback', 'setinfo_Delay');
        
        %rand ramps
        % 9 on and offs
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[310 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'HorizontalAlignment', 'center',...
        'String', 'Gate (source):  ');
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'HorizontalAlignment', 'right',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Onset(ms): ');
    H.onramp01 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[60 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_on(1)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.onramp02 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_on(2)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.onramp03 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_on(3)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.onramp04 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_on(4)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.onramp05 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[220 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_on(5)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.onramp06 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[260 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_on(6)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.DelayOnOff_mode = uicontrol('Parent',H.Delayfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[325 F.Delay_ht-F.tot_ht 50 F.ind_ht],...
        'BackgroundColor','white',...
        'String',...
        '1|1 & 2|2',...
        'Value', XStimParams.OnOff_mode,...
        'Callback','setinfo_Delay');
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'HorizontalAlignment', 'right',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Offset(ms): ');
    H.offramp01 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[60 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_off(1)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.offramp02 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_off(2)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.offramp03 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_off(3)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.offramp04 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_off(4)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.offramp05 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[220 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_off(5)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.offramp06 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[260 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.ramp_timeS_off(6)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');

        
    F.tot_ht = F.tot_ht + F.ind_ht;
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'HorizontalAlignment', 'right',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Lag+ (ms): ');
    H.lagext01 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[60 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(1)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext02 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(2)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext03 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(3)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext04 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[180 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(4)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext05 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[220 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(5)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext06 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[260 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(6)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext07 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[300 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(7)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    H.lagext08 = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[340 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.lag_seg_ext(8)),...
        'BackgroundColor', [1 1 1],...
        'Callback', 'setinfo_Delay');
    

    %ABL
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht-5 130 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', '70=50 dB on PA4');
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 130 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', '(unless -20 HB6 gain)');
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Atten (dB):');
    H.ABL = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.curr_ABL),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback', 'setinfo_Delay');
    
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[310 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'HorizontalAlignment', 'center',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'defaults:  ');
     
    %ISI
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'ISI (ms):');
    H.ISI = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[202 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.test_ISI),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback', 'setinfo_Delay');
        
    %DUR
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Stim Dur (ms):');
    H.DUR = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[82 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.curr_stimdur),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    
    %NumReps
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[140 F.Delay_ht-F.tot_ht 60 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', '# Reps:');
    H.numreps = uicontrol('Style','edit',...
        'Units','pixels',...
        'Position',[202 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'String', num2str(XStimParams.numreps),...
        'BackgroundColor', [0.9 0.9 0.9],...
        'Callback','setinfo_Delay');
    
    H.delay_defaults = uicontrol('Parent',H.Delayfig,...
        'Style','popup',...
        'Units','pixels',...
        'Position',[310 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','white',...
        'String', 'Onset PE|OnRamps|LagXs|NoLagSeg| |NaNs|OffRamps',...
        'Value', XStimParams.Delay_default,...
        'Callback','Delay_defaults');
    
    % run control
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht F.Delay_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Run Control');
    
    %Engage TEST
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.engageDelay = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','green',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'ENGAGE',...
        'Callback','Engage_Delay');
    
    %Record Data?
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.Delay_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'ForegroundColor','red',...
        'String', 'Record Data?');
    H.recorddata = uicontrol('Style','checkbox',...
        'Units','pixels',...
        'Position',[185 F.Delay_ht-F.tot_ht 20 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Callback', 'setinfo_Delay');
    F.tot_ht = F.tot_ht + F.ind_ht;
    H.recorddata_FN = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[85 F.Delay_ht-F.tot_ht 100 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'FontWeight','bold',...
        'String', FN.data);
    
    % increment test number
    H.inc_testnum = uicontrol('Style','pushbutton',...
        'Units','pixels',...
        'Position',[250 F.Delay_ht-F.tot_ht 140 F.ind_ht],...
        'BackgroundColor','yellow',...
        'ForegroundColor','blue',...
        'FontWeight','bold',...
        'String', 'INCREMENT testnum',...
        'Callback','setInfo_Delay');
    
    %Pause TEST
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    H.pauseDelay = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Pause');
   
     %plotVstrength
    H.plotVstr = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[100 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','cyan',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Plot Vstr',...
        'Callback', 'setInfo_Delay');

    %Reset
    H.resetDelay = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[200 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','cyan',...
        'ForegroundColor','black',...
        'FontWeight','bold',...
        'String', 'Reset',...
        'Callback','Reset_Delay');
    
    %Exit
    H.exitDelay = uicontrol('Style','togglebutton',...
        'Units','pixels',...
        'Position',[F.Delay_wd-100 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor','red',...
        'ForegroundColor','yellow',...
        'FontWeight','bold',...
        'String', 'EXIT',...
        'Callback','Exit_Delay');
    
    %Build/Play Trials
    F.ind_ht = 20; 
    F.tot_ht = F.tot_ht + F.ind_ht + F.pos_incr;
    H.status = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht F.Delay_wd F.ind_ht],...
        'BackgroundColor','blue',...
        'ForegroundColor','white',...
        'FontWeight','bold',...
        'String', 'Status: setting parameters');
    
    %Remaining Reps and Trials
    F.tot_ht = F.tot_ht + F.ind_ht;
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[0 F.Delay_ht-F.tot_ht 120 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Remaining reps:');
    H.remreps = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[122 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'BackgroundColor', [0.9 0.9 0.9],...
        'String', get(H.numreps,'String'));
    uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[164 F.Delay_ht-F.tot_ht 80 F.ind_ht],...
        'BackgroundColor', [0.8 0.8 0.8],...
        'String', 'Trials:');
    H.remtrials = uicontrol('Style','text',...
        'Units','pixels',...
        'Position',[246 F.Delay_ht-F.tot_ht 40 F.ind_ht],...
        'BackgroundColor', [0.9 0.9 0.9],...
        'String', '');
    
end %end GUI specification

stimuli_dir = FN.temp_stim_path;

% Initialize Application and get AP2 and XBUS locks
if(S232('S2init', 0, 'INIT_PRIMARY', 20000) == 0)
    disp('Cannot initialize a secondary process')
    return;
end

if(S232('APlock', 100, 0) == 0)
    disp('Cannot acquire lock on AP2 Card')
    s232('S2close');
    return;
end

if(S232('XBlock', 100, 0) == 0)
    disp('Cannot acquire lock on X Bus')
    s232('APunlock', 0);
    s232('S2close');
    return;
end

SetInfo_Delay;


%     'Delay_ms',                 10, ...
%     'SilentDelay',              0, ...
%     'uncorrel',                 0, ...