%Functions related to the caluclation of HRTF
% 
% ADDLOWW  merge the lower hemisphere to an upper hemisphere catalogue
% EQ_MIC   ?
% EQU      Equalization of  HRTF with inverse TF (e.g. headphone).
% EQU2     Equalization of  HRTF with inverse TF (e.g. headphone).
% EQU_LS   equalize HRTF with inverse loudspeaker TF.
% EQU_LS2  equalize HRTF with inverse loudspeaker TF.
% EQUALIZE equalize HRTF with inverse loudspeaker TF.
% HEAD2MAT merges heaphone-TF2 to matfile.
% HORIZON  ?
% LSEQUAL2 Compute random phase signals with loadspeaker equalization
% LSQFIRIN Least square inverse filter design with lowpass or bandpass-filtering 
% LSQINV2  Least square inverse filter design with lowpass or bandpass-filtering 
% LSQINV3  Least square inverse filter design with lowpass or bandpass-filtering 
% LSQINV4  Least square inverse filter design with lowpass or bandpass-filtering 
% LSQINV5  Least square inverse filter design with lowpass or bandpass-filtering 
% LSQINV6  Least square inverse filter design with lowpass or bandpass-filtering 
% MAT2MTL  convert matlab file to mtl-, bifi- or sigmaps-file
% MEDIANP
% MTL2MAT  converts mtl2 file to matfile
% OPTIHRTF ?
% OPTWIN   find the most powerful part 
% OPTWIN2  find the most powerful part 
% PREPLOW  correct directions for  upside-down measurements
% RAW2CLE1 remove reflections and noise from impulse response 
% RAW2CLEA remove reflections and noise from impulse response 
% RAWHEAD2 remove reflections and noise from headphone impulse response
% RAWHEAD3 remove reflections and noise from headphone impulse response
% RAWLS2CL removes reflections and noise from impulse response (HRTF_RAW -> HRTF)
% SC12MAT  converts sc1 file to matfile
% SC22MAT  converts sc2 files to matfile
% SPACEMAP derives weighting factors for ILD, ITD and monaural spectrum (LEVEL)
% TF2MAT   merges TF2 to matfile.

% Klaus Hartung
% 17.10.96
