function fig = spacePicker()
% modified version of Matt's spaceconsole
% allows picking of space
% must call modified globals_GUI first
% then desired locations are found in GUI.locations1
% Nov 27, 2001

global GUI
global H
global XStimParams

% define figure
H.pickerfig = figure('Color',[0.8 0.8 0.8], ...
    'DoubleBuffer','on', ...
    'MenuBar', 'none',...
    'Name','Space Picker', ...
    'NumberTitle','off', ...
    'PaperPosition',[18 180 576 432], ...
    'PaperUnits','points', ...
    'Position',[800 600 395 300],...					%[5 180 395 300],...
    'Resize', 'off',...
    'ResizeFcn','doresize(gcbf)', ...
    'ToolBar','none', ...
    'Units', 'pixels', ...
    'DefaultaxesCreateFcn','plotedit(gcbf,''promoteoverlay''); ');


% add/subtract pt buttons
H.picker_add_point1 = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
    'Units','pixels', ...
    'BackgroundColor','green', ...
    'Position',[10 160 90 20], ...
    'ForegroundColor','black',...
    'String','add pts', ...
    'Callback','SetInfo_spacePicker;');
H.picker_delete_point1 = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
    'Units','pixels', ...
    'Position',[10 130 90 20], ...
    'BackgroundColor',[.9 .9 .9],...
    'ForegroundColor','black',...
    'String','delete pts', ...
    'Callback','SetInfo_spacePicker;');

% set cursormode to diagonals
H.picker_falling_diagonal = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
    'Units','pixels', ...
    'Position',[10 100 90 20], ...
    'BackgroundColor',[.9 .9 .9],...
    'ForegroundColor','black',...
    'String','add falling diag', ...
    'Callback','SetInfo_spacePicker;');

H.picker_rising_diagonal = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
    'Units','pixels', ...
    'Position',[10 70 90 20], ...
    'BackgroundColor',[.9 .9 .9],...
    'ForegroundColor','black',...
    'String','add rising diag', ...
    'Callback','SetInfo_spacePicker;');

% remove edges pushbutton
H.picker_removeEdges = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
    'Units','pixels', ...
    'Position',[10 40 90 20], ...
    'BackgroundColor',[.9 .9 .9],...
    'ForegroundColor','black',...
    'String','remove edges', ...
    'Callback','SetInfo_spacePicker;');

% use last locations pushbutton
H.UseLastLocations = uicontrol('Parent',H.pickerfig, ...
    'Style','pushbutton',...
    'Units','pixels', ...
    'Value',GUI.UseLastLocations_flag,...
    'Position',[10 10 90 20], ...
    'BackgroundColor',[.9 .9 .9],...
    'ForegroundColor','black',...
    'String','Use last locs', ...
    'Callback','SetInfo_spacePicker;');

% error message
H.picker_error = uicontrol('Parent',H.pickerfig, ...
    'Units','pixels', ...
    'FontSize',12, ...
    'BackgroundColor',[.1 0.2 0.8], ...
    'ForegroundColor','yellow', ...
    'FontWeight','bold',...
    'Position',[2 220 100 60], ...
    'String','YOU MUST ENTER LOCATIONS', ...
    'Style','text',...
    'Visible','off');

% define axes
H.picker_one = axes('Parent',H.pickerfig, ...
    'Units','pixels', ...
    'ButtonDownFcn','spaceaxisX2CB', ...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',[1 1 1], ...
    'FontSize',8, ...
    'Position',[130 46 230 230], ...
    'Tag','spaceaxes', ...
    'XColor',[0 0 0], ...
    'XGrid','on', ...
    'XLim',[-90 90], ...
    'XLimMode','manual', ...
    'XTick',[-90:30:90], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YGrid','on', ...
    'YLim',[-90 90], ...
    'YLimMode','manual', ...
    'YTick',[-90:30:90], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);

% all button
H.picker_AllSpace = uicontrol('Parent',H.pickerfig, ...
    'Units','pixels', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'ListboxTop',0, ...
    'Position',[136 252 18 18], ...
    'String','All', ...
    'Callback','SetInfo_spacePicker;');

% clear button
H.picker_clear = uicontrol('Parent',H.pickerfig, ...
    'Units','pixels', ...
    'BackgroundColor',[0.75 0.75 0.75], ...
    'ListboxTop',0, ...
    'Position',[136 52 30 18], ...
    'String','Clear', ...
    'Callback','SetInfo_spacePicker;');

% choose resolution of points
switch XStimParams.GUIspaceres
    case 'max'
        val = 1;
    case '5deg'
        val = 2;
    case '10degOffset'
        val = 3;
    case '10deg'
        val = 4;
    case '20degOffset'
        val = 5;
    case '20deg'
        val = 6;
end

H.picker_resolution = uicontrol('Parent',H.pickerfig, ...
    'Units','pixels', ...
    'BackgroundColor',[0.752 0.752 0.7529], ...
    'ListboxTop',0, ...
    'Position',[284 52 70 18], ...
    'String',['Maximum       ';'5 deg.        ';'10 deg. offset';'10 deg.       ';'20 deg. offset';'20 deg.       '], ...
    'Style','popupmenu', ...
    'Value', val, ...
    'Callback','SetInfo_spacePicker;');

uicontrol('Parent',H.pickerfig, ...
    'Units','pixels', ...
    'BackgroundColor',[0.9 0.9 0.9], ...
    'ListboxTop',0, ...
    'Position',[285 72 65 15], ...
    'String','Resolution:', ...
    'Style','text');

SetInfo_spacePicker;
if nargout > 0, fig = H.pickerfig; end
