global TDT

% redone on 3/7/07 to make all SPLs similar
if 0
    TDT.Fs = 30000;             %Sampling rate for DA
    TDT.Fsdata = 1000;
    TDT.hrtffiltlen = 254;
    TDT.itdfiltlen = 255;
    TDT.ephonefiltlen = 254;
    TDT.ephonescale = 1.0;
    TDT.scalevalue = 2000;
    TDT.buf_pts = 90000;        % Npts in dynamically updated buffers
    TDT.hrtf_scale = .4;
end

TDT = struct(...
    'Fs',                   30000, ...
    'Fsdata',               1000, ...
    'hrtffiltlen',          254, ...
    'itdfiltlen',           255, ...
    'buf_pts',              90000, ...
    'ephonefiltlen',        254, ...
    'ephonescale',          1.0, ...
    'scaleFactor',          600, ...
    'freefield_Lfactor',     .83, ...
    'freefield_Rfactor',     .83, ...
    'hrtf_Lfactor',          .8347, ...
    'hrtf_Rfactor',          .8439, ...
    'hrtf_scale',           1.0 ...
    );

% values from 938
%    'freefield_Lfactor',     .6608, ...
%    'freefield_Rfactor',     .5498, ...
% these adjust freefield stimuli to be ~equal to that from 0,0 with hrtfs
% convolved through DSPs (*.eq) (broadband)
%
%    'hrtf_Lfactor',          .8347, ...
%    'hrtf_Rfactor',          .8439, ...
% these adjust headphone stimuli pre-convolved with hrtfs (*.std) to match those
% presented through DSPs (*.eq) at 0,0 (broadband)