% global_Mii.m
% contains global definitions for MII calls
% as constants within two structures: C_ and M_

global C_;
global M_;

C_ =	struct(...
'INIT' 	, 0,...
'CLOCK'  , 1,...
'START'  , 2,...
'STOP'	, 3,...
'STATUS' , 4,...
'INTERRUPT' , 5,...
'C8253'  	, 6,...
'C8255'  	, 7,...
'DATA'  	, 8,...
'MODE'  	, 9,...
'POLARITY' , 10,...
'CONTROL', 11,...
'CLEAR' 	, 12);

M_ = struct(...
'READ'   , 0,...
'SET'	 	, 1,...
'RAWSET' , 2,...
'PULSE'  , 3,...
'TIMER0' , 0,...
'TIMER1' , 1,...
'TIMER2' , 2,...
'CLEAR'  , 2,...
'ENABLE' , 1,...
'DISABLE', 0,...
'INPUT'  , 1,...
'OUTPUT' , 0,...
'BYTE'	, 0,...
'BIT'		, 1,...
'PST'	 	, 1,...
'INTERVAL' , 0,...
'EVENT'  , 0,...
'STIMULUS', 1,...
'NEGATIVE', 1,...
'POSITIVE' , 0,...
'HALFFULL' , 0,...
'DATA_AVAIL', 1,...
'AUTOSTEP' , 1,...
'NOSTEP' , 0,...
'MEMORY' , 3,...
'MANUAL' , 1,...
'AUTO'	, 0,...
'SOFTWARE', 0,...
'CLOCK'  , 1,...
'EXTERNAL', 2,...
'TRIGGER', 4,...
'HOST'	, 1,...
'BUFFER' ,0,...
'CIRCULAR', 1,...
'STOP'	, 0,...
'ADDRESS', 2,...
'GATED'  , 1,...
'TRIGGERED', 2,...
'TRIG_STOP', 3,...
'CONVERT', 4,...
'SEQUENCE', 5,...
'NORMAL' , 0,...
'REVERSED', 1,...
'TRIGOUT', 1,...
'DELAY'  , 1,...
'COUNT'  , 2,...
'SOURCE1', 0,...
'SOURCE2', 1,...
'LEFT'	, 0,...
'RIGHT'  , 1,...
'SINE'	, 0,...
'LOAD'	, 1,...
'RAMP'	, 0,...
'FLAT'	, 1);