% draw portion of main GUI to allow specification of 
% location script file

ind_ht = 20;
Xstim_control_pos = get(H.fig,'Position');
spacefig_l = Xstim_control_pos(3) - 300; 
spacefig_wd = 400; 
spacefig_ht = 950;
tot_ht = 250 + ind_ht;

% check for existence of Figure window
if (exist1('H.spacefig')) 
   if (~XStimParams.picker_flag)

%Location Script File
	H.locscriptfilehdr = uicontrol('Parent',H.spacefig,...
   	'Style','text',...
   	'Position',[0 spacefig_ht-tot_ht spacefig_wd ind_ht],...
   	'String', 'Location Script File:');
	tot_ht = tot_ht + ind_ht;
	H.locscriptfile = uicontrol('Parent',H.spacefig,...
   	'Style','text',...
   	'Position',[0 spacefig_ht-tot_ht spacefig_wd ind_ht],...
   	'HorizontalAlignment','left',...
   	'String', XStimParams.locscriptfile);
	tot_ht = tot_ht + ind_ht;
	uicontrol('Parent',H.spacefig,...
   	'Style','pushbutton',...
   	'Units','pixels',...
   	'Position',[2 spacefig_ht-tot_ht 195 ind_ht],...
   	'BackgroundColor','red',...
   	'ForegroundColor','white',...
   	'FontWeight','bold',...
   	'String', 'Select Location Script File',...
   	'Callback','locscriptfilediagbox');
   else
 	tot_ht = 250 + ind_ht*3;
	uicontrol('Parent',H.spacefig,...
   	'Style','text',...
   	'Units','pixels',...
      'Position',[0 spacefig_ht-tot_ht spacefig_wd ind_ht*3],...
      'BackgroundColor', [.8 .8 .8]);
  
   end
end