
global GUI
global H
global XStimParams
global FN

sp_AM_pos_incr = 20;
sp_AM_tot_ht = 0;
sp_AM_ind_ht = 20;
sp_AM_Two_source_wd = 300; 
sp_AM_Two_source_ht = 900;

% define figure
H.setparamsfig_AM = figure('Units', 'pixels',...
	'Position', [10 100 sp_AM_Two_source_wd sp_AM_Two_source_ht], ...
	'Name', 'Set/View Stimulus Params', ...
	'NumberTitle', 'off');
 
sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

for count2 = 1:XStimParams.com_num_ted

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht], ...
	'FontWeight','bold',...	
	'Visible','on',...   
	'String', ['Amplitude ' num2str(count2)]);

for count1 = 1:XStimParams.com_len_ted
	uicontrol('Parent',H.setparamsfig_AM,...
		'Style','text',...
		'Units','pixels',...
		'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht], ...
		'Visible','on',...   
		'String', ['Segment ' num2str(count1)]);
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht], ...
	'Visible','on',...   
	'String', ['Factor']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.amp_mat_ted(count2, 1, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position', [(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht], ...
			'Visible','on',...    
			'String', num2str(XStimParams.amp_mat_ted(count2, 1, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Dist']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.amp_mat_ted(count2, 2, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.amp_mat_ted(count2, 2, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Param1']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.amp_mat_ted(count2, 3, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.amp_mat_ted(count2, 3, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Param2']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.amp_mat_ted(count2, 4, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.amp_mat_ted(count2, 4, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht + 4;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'FontWeight','bold',...	
	'Visible','on',...   
	'String', ['Length ' num2str(count2)]);

for count1 = 1:XStimParams.com_len_ted
	uicontrol('Parent',H.setparamsfig_AM,...
		'Style','text',...
		'Units','pixels',...
		'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
		'Visible','on',...   
		'String', ['Segment ' num2str(count1)]);
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Factor']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.len_mat_ted(count2, 1, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.len_mat_ted(count2, 1, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Dist']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.len_mat_ted(count2, 2, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.len_mat_ted(count2, 2, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Param1']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.len_mat_ted(count2, 3, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.len_mat_ted(count2, 3, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

uicontrol('Parent',H.setparamsfig_AM,...
    'Style','text',...
	'Units','pixels',...
	'Position',[10 (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
	'Visible','on',...   
	'String', ['Param2']);

if XStimParams.com_len_ted > 0     
    for count1 = 1:XStimParams.com_len_ted
	   H.len_mat_ted(count2, 4, count1) = uicontrol('Parent',H.setparamsfig_AM,...
			'Style','edit',...
			'Units','pixels',...
			'Position',[(10 + (count1 * 75)) (sp_AM_Two_source_ht - sp_AM_tot_ht) 75 sp_AM_ind_ht],...
			'Visible','on',...    
			'String', num2str(XStimParams.len_mat_ted(count2, 4, count1)),...
			'Callback','setInfo_setParams_AM');
    end
end

sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;
sp_AM_tot_ht = sp_AM_tot_ht + sp_AM_ind_ht;

end


setInfo_setParams_AM;

 