% Grafic functions - transfer functions, interaural and monaural parameter plot
% 
% DISPDATA  displays the measured impulse responses and transfer-
% DISPWIND  displays the measured impulse responses and transfer-
% ETCPLOT   Plot one or more ETC (energy time curve) of real (time) signals.
% FLATPLOT  interpolated three dimensional colour, mesh or contour plot  
% IAPLOT    plot interaural transfer function on sphere
% HRTFPLOT  ? 
% IAPLOT    plot interaural transfer function on sphere
% LOGPLOT   Plot magnitude of one or more complex signals.
% LSPLOT    plot loudspeaker transfer functions
% MAG3DPLO  ? 
% MAGPLOT   Plot magnitude of one or more complex signals.
% MESEMLOG  ?
% OPTIMAGP  Plot magnitude of one or more complex signals.
% PHASPLOT  Plot phase of one or more complex signals in degrees.
% PHDEPLOT  Plot phase delay of one or more complex signals in seconds.
% POLARNET  ?
% SEMLOGX2  ?
% SETXR
% SPHEREIN  interpolation on a sphere
% SPHEREPL  interpolated three dimensional colour and/or contour plot on sphere
% SPPLOT    ?
% TG3DPLO   ?
 
% Klaus Hartung (hartung@aea.ruhr-uni-bochum.de)
% Lehrstuhl fuer allg. Elektrotechnik und Akustik
% Ruhr-Universitaet Bochum
% 44780 Bochum 
% 
% Date 17.10.1996

